### ISSUE TITLE
MD5 hash checksum fails backup when storing to S3

### ISSUE THREAD

**Issue by rkumar-pythian** [thelastpickle/cassandra-medusa#100]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952147)

When using AWS S3 to store medusa backup, it fails with the error of failed checksum 

`[2020-03-27 04:16:48,109] ERROR: This error happened during the backup: <ObjectHashMismatchError in <libcloud.storage.drivers.s3.S3USWestOregonStorageDriver object at 0x7f3bf403f410>, value=MD5 hash 782ac22df7c2ec85673a6f4dacd561b1 checksum does not match 18943ee8efa47ff14e5dd7f49b103727, object = ip-**-**-**-**.us-west-2.compute.internal/data/system/local-7ad54392bcdd35a684174e047860b377/md-39-big-Filter.db>`

* Tried suggestion from Issue 58 to update the upload_object() function but that did not help.
* Tried solution for replacing the part of code, but that also did not help
`https://github.com/nicholasamorim/cassandra-medusa/commit/f23532c699eb73f0ebdadf31f9a02e9c7827eba2`

Updated the file : `/usr/local/lib/python3.7/site-packages/medusa/storage/concurrent.py
`
Backup using local disk as storage destination succeed, only facing issue when setting S3 as destination.
AWS S3 bucket is accessible using access keys (so no access issue).

Error faced during the

`[root@ip-**-**-**-** ~]# medusa -v backup --backup-name=backup_8
[2020-03-27 04:16:02,964] DEBUG: Loading configuration from /etc/medusa/medusa.ini
[2020-03-27 04:16:02,965] DEBUG: Logging to file options: LoggingConfig(enabled='1', file='/etc/medusa/medusa.log', format='[%(asctime)s] %(levelname)s: %(message)s', level='INFO', maxBytes='20000000', backupCount='50')
[2020-03-27 04:16:02,966] INFO: Monitoring provider is noop
[2020-03-27 04:16:02,966] DEBUG: Getting IAM Role:
[2020-03-27 04:16:02,969] DEBUG: IAM Role not found.
[2020-03-27 04:16:02,969] DEBUG: Reading AWS credentials from Environment Variables:
[2020-03-27 04:16:03,033] DEBUG: This server has systemd: True
[2020-03-27 04:16:03,034] WARNING: is ccm : 0
[2020-03-27 04:16:03,109] DEBUG: Blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql was not found in cache.
[2020-03-27 04:16:03,110] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql
[2020-03-27 04:16:03,166] DEBUG: Process psutil.Process(pid=17990, name='medusa', started='04:16:02') was set to use only idle IO and CPU resources
[2020-03-27 04:16:03,166] INFO: Creating snapshot
[2020-03-27 04:16:03,166] INFO: Saving tokenmap and schema
[2020-03-27 04:16:03,369] DEBUG: Checking datacenter...
[2020-03-27 04:16:03,369] DEBUG: Checking host 127.0.0.1 against localhost/127.0.0.1
[2020-03-27 04:16:04,127] DEBUG: Blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/tokenmap.json was not found in cache.
[2020-03-27 04:16:04,127] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/tokenmap.json
[2020-03-27 04:16:04,142] DEBUG: [Storage] Reading blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/tokenmap.json...
[2020-03-27 04:16:04,143] DEBUG: [Storage] Reading blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/tokenmap.json...
[2020-03-27 04:16:04,369] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql
[2020-03-27 04:16:04,385] DEBUG: [Storage] Reading blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql...
[2020-03-27 04:16:04,385] DEBUG: [Storage] Reading blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql...
[2020-03-27 04:16:04,574] DEBUG: Blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql was not found in cache.
[2020-03-27 04:16:04,574] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql
[2020-03-27 04:16:04,593] DEBUG: Blob ip-**-**-**-**.us-west-2.compute.internal/backup_8/meta/schema.cql last modification time is Fri, 27 Mar 2020 04:16:04 GMT
[2020-03-27 04:16:05,069] DEBUG: [Storage] Getting object index/latest_backup/ip-**-**-**-**.us-west-2.compute.internal/backup_name.txt
[2020-03-27 04:16:05,094] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/None/meta/differential
[2020-03-27 04:16:05,110] DEBUG: [Storage] Getting object ip-**-**-**-**.us-west-2.compute.internal/None/meta/incremental
[2020-03-27 04:16:05,129] INFO: Node ip-**-**-**-**.us-west-2.compute.internal does not have latest backup
[2020-03-27 04:16:05,129] INFO: Starting backup
[2020-03-27 04:16:05,129] DEBUG: Executing: nodetool -u ******* -pw ***** snapshot -t medusa-f34c77fa-1a94-4866-a8cd-abf27024867d
[2020-03-27 04:16:06,112] DEBUG: Getting IAM Role:
[2020-03-27 04:16:06,116] DEBUG: IAM Role not found.
[2020-03-27 04:16:06,116] DEBUG: Reading AWS credentials from Environment Variables:
[2020-03-27 04:16:06,117] INFO: Uploading /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/snapshots/medusa-f34c77fa-1a94-4866-a8cd-abf27024867d/md-39-big-Filter.db (16.000B)
[2020-03-27 04:16:06,117] DEBUG: Uploading ip-**-**-**-**.us-west-2.compute.internal/data/system/local-7ad54392bcdd35a684174e047860b377/md-39-big-Filter.db as single part
[2020-03-27 04:16:26,736] INFO: Uploading /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/snapshots/medusa-f34c77fa-1a94-4866-a8cd-abf27024867d/md-39-big-Data.db (5.133KiB)
[2020-03-27 04:16:26,736] DEBUG: Uploading ip-**-**-**-**.us-west-2.compute.internal/data/system/local-7ad54392bcdd35a684174e047860b377/md-39-big-Data.db as single part
[2020-03-27 04:16:47,214] DEBUG: Cleaning up snapshot
[2020-03-27 04:16:47,214] DEBUG: Executing: nodetool -u ****** -pw ******* clearsnapshot -t medusa-f34c77fa-1a94-4866-a8cd-abf27024867d
[2020-03-27 04:16:48,109] DEBUG: nodetool output: Requested clearing snapshot(s) for [all keyspaces] with snapshot name [medusa-f34c77fa-1a94-4866-a8cd-abf27024867d]

[2020-03-27 04:16:48,109] ERROR: This error happened during the backup: <ObjectHashMismatchError in <libcloud.storage.drivers.s3.S3USWestOregonStorageDriver object at 0x7f3bf403f410>, value=MD5 hash 782ac22df7c2ec85673a6f4dacd561b1 checksum does not match 18943ee8efa47ff14e5dd7f49b103727, object = ip-**-**-**-**.us-west-2.compute.internal/data/system/local-7ad54392bcdd35a684174e047860b377/md-39-big-Filter.db>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 274, in main
    cassandra, node_backup, storage, differential_mode, config)
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 320, in do_backup
    num_files = backup_snapshots(storage, manifest, node_backup, node_backup_cache, snapshot)
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 388, in backup_snapshots
    manifest_objects = storage.storage_driver.upload_blobs(needs_backup, dst_path)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/s3_storage.py", line 148, in upload_blobs
    multi_part_upload_threshold=int(self.config.multi_part_upload_threshold),
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 60, in with_storage
[cassandra]
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 83, in <lambda>
    storage, connection, src_file, dest, bucket, multi_part_upload_threshold
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 119, in __upload_file
    obj = _upload_single_part(connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(_dargs, *_dkw).call(f, _args, *_kw)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(_args, *_kwargs), attempt_number, False)
[cassandra]
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 127, in _upload_single_part
    str(src), container=bucket, object_name=object_name
  File "/usr/local/lib/python3.7/site-packages/libcloud/storage/drivers/s3.py", line 492, in upload_object
    storage_class=ex_storage_class)
  File "/usr/local/lib/python3.7/site-packages/libcloud/storage/drivers/s3.py", line 854, in _put_object
    object_name=object_name, driver=self)
libcloud.storage.types.ObjectHashMismatchError: <ObjectHashMismatchError in <libcloud.storage.drivers.s3.S3USWestOregonStorageDriver object at 0x7f3bf403f410>, value=MD5 hash 782ac22df7c2ec85673a6f4dacd561b1 checksum does not match 18943ee8efa47ff14e5dd7f49b103727, object = ip-**-**-**-**.us-west-2.compute.internal/data/system/local-7ad54392bcdd35a684174e047860b377/md-39-big-Filter.db>
[cassandra]`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-260) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-260

**Comment by BobbyJohansen** [comment]
Any plans for this on the roadmap?

**Comment by arodrime** [comment]
We are investigating something that might very well be related with Rick Wells, on slack here: https://the-asf.slack.com/archives/C0111B5KADA/p1594839796001400?thread_ts=1594137152.002800&cid=C0111B5KADA.

it seems that if you changed the chunksize for S3 from the 8MB default with:
```
aws configure set default.s3.multipart_chunksize 20MB
# Or in AWS config, in bytes
s3 =
     multipart_chunksize = 20MB 
```

Then you need to change also the value for this variable in medusa: https://github.com/thelastpickle/cassandra-medusa/blob/0.7/medusa/storage/abstract_storage.py#L30 (`MULTIPART_PART_SIZE_IN_MB`), to avoid hash errors.

We will patch to ensure values are matching, meanwhile, maybe you'd like to check this on your side, see if this can be the origin of the issue on your side @BobbyJohansen/@rkumar-pythian.

**Comment by rzvoncek** [comment]
Hello @rkumar-pythian ! I'm doing some grooming and dusting off old tickets. Over the years, we've iterated on the storage implementation a lot, and chances are this got resolved. Please let us know if you still happen to suffer some issues.
