### ISSUE TITLE
medusa restore node fails due to a incorrect file_path variable

### ISSUE THREAD

**Issue by mclpfr** [thelastpickle/cassandra-medusa#101]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952146)

```bash
debian@saas-cassandra-01:~$ sudo medusa restore-node --backup-name=backup-202003270911 
```

```
[2020-03-27 10:22:00,178] WARNING: is ccm : 0
[2020-03-27 10:22:00,183] INFO: Downloading data from backup to /tmp/medusa-restore-4bda53ee-cb0c-4e51-abf7-e771009b7651
[2020-03-27 10:22:00,330] INFO: Downloading backup data
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/medusa/medusacli.py", line 212, in restore_node
    verify, set(keyspaces), set(tables), use_sstableloader)
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_node.py", line 48, in restore_node
    keyspaces, tables)
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_node.py", line 81, in restore_node_locally
    download_data(config.storage, node_backup, fqtns_to_restore, destination=download_dir)
  File "/usr/local/lib/python3.5/dist-packages/medusa/download.py", line 47, in download_data
    storage.storage_driver.download_blobs(srcs, dst)
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/abstract_storage.py", line 71, in download_blobs
    max_workers=self.config.concurrent_transfers)
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 129, in download_blobs
    job.execute(list(src))
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 49, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 58, in with_storage
    return self.func(connection, iterable)
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 127, in <lambda>
    lambda connection, src_file: __download_blob(connection, src_file, str(dest), bucket_name),
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 151, in __download_blob
    blob.download(blob_dest, overwrite_existing=True)
  File "/usr/local/lib/python3.5/dist-packages/libcloud/storage/base.py", line 106, in download
    delete_on_failure)
  File "/usr/local/lib/python3.5/dist-packages/libcloud/storage/drivers/s3.py", line 468, in download_object
    success_status_code=httplib.OK)
  File "/usr/local/lib/python3.5/dist-packages/libcloud/storage/base.py", line 509, in _get_object
    return callback(**callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/libcloud/storage/base.py", line 587, in _save_object
    with open(file_path, 'wb') as file_handle:
**IsADirectoryError: [Errno 21] Is a directory: '/tmp/medusa-restore-4bda53ee-cb0c-4e51-abf7-e771009b7651/sandbox_james/deletedmessagemetadata-7c87e510519111eaba9ad3328ef5463b'**
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-261) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-261

**Comment by mclpfr** [comment]
My medusa.ini file:
[cassandra]
stop_cmd = /etc/init.d/cassandra stop
start_cmd = /etc/init.d/cassandra start
config_file = /etc/cassandra/cassandra.yaml
cql_username = xxxxxxx
cql_password = xxxxxxx
nodetool_username =  xxxxxx
nodetool_password =  xxxxxx
nodetool_password_file_path = /etc/cassandra/jmxremote.password
nodetool_host = saas-cassandra-01
nodetool_port = 7199

; Command ran to verify if Cassandra is running on a node. Defaults to "nodetool version"
check_running = nodetool version

[storage]
storage_provider = s3_rgw
bucket_name = xxxx-xxxxxx-xxxxxx
key_file = /etc/medusa/ceph-credentials
host = xxxxxxxxxxxxxxx
secure = true
port = 443

; Path of the local storage bucket (used only with 'local' storage provider)
;base_path = /path/to/backups

; Any prefix used for multitenancy in the same bucket
;prefix = clusterA

;fqdn = <enforce the name of the local node. Computed automatically if not provided.>

; Number of days before backups are purged. 0 means backups don't get purged by age (default)
max_backup_age = 7
; Number of backups to retain. Older backups will get purged beyond that number. 0 means backups don't get purged by count (default)
max_backup_count = 7
; Both thresholds can be defined for backup purge.

; Used to throttle S3 backups/restores:
transfer_max_bandwidth = 50MB/s

; Max number of downloads/uploads. Not used by the GCS backend.
concurrent_transfers = 1

; Size over which S3 uploads will be using the awscli with multi part uploads. Defaults to 100MB.
multi_part_upload_threshold = 104857600

[monitoring]
;monitoring_provider = <Provider used for sending metrics. Currently either of "ffwd" or "local">

[ssh]
username = debian
key_file = /home/debian/.ssh/id_rsa_sandbox
;port = <SSH port for use for restoring clusters. Default to port 22.

[checks]
;health_check = <Which ports to check when verifying a node restored properly. Options are 'cql' (default), 'thrift', 'all'.>
;query = <CQL query to run after a restore to verify it went OK>
;expected_rows = <Number of rows expected to be returned when the query runs. Not checked if not specified.>
;expected_result = <Coma separated string representation of values returned by the query. Checks only 1st row returned, and only if specified>

[logging]
; Controls file logging, disabled by default.
enabled = 1
file = medusa.log
level = INFO

; Control the log output format
format = [%(asctime)s] %(levelname)s: %(message)s

; Size over which log file will rotate
maxBytes = 20000000

; How many log files to keep
backupCount = 50

**Comment by mclpfr** [comment]
Thanks a lot for your help

**Comment by mclpfr** [comment]
Hi,
I found a solution for my case and share here.
The fix concern "_save_object" function between line 369 and 372
We have this :
```
if not base_name:
       file_path = pjoin(destination_path, obj.name)
else:
        file_path = destination_path
```
The fix is :
```
if not base_name:
     file_path = pjoin(destination_path, obj.name)
else:
     file_name = obj.name
     data = file_name.split('/')[-1]
     file_path = ''.join((file_path, '/', data))
```
file_path is now an object and the process backup can continue

**Comment by adejanovski** [comment]
Hi @mclpfr,

which file did you modify precisely?
The backup code has been modified yesterday to use streams. It would be good to check if that fixed your issue as well.

Thanks!

**Comment by mclpfr** [comment]
In my case this is base.py on /usr/local/lib/python3.5/dist-packages/libcloud/storage/
Ok i will check 
Thanks

**Comment by mclpfr** [comment]
After some tests, this issue is still present and seems to concern libcloud scripts.
Thanks anyway
