### ISSUE TITLE
Problem with the restore 

### ISSUE THREAD

**Issue by TryToWork** [thelastpickle/cassandra-medusa#109]
Hello, 

Restore process crashes due to the fact that we have a mount point.

```
[root@node1~]# df -h
Filesystem                                     Size  Used Avail Use% Mounted on
...
/dev/mapper/vg01-lv_cassandra_commitlog_tst     10G   48M   10G   1% /var/lib/cassandra/commitlog
/dev/mapper/vg01-lv_cassandra_savedcaches_tst  8.0G   33M  8.0G   1% /var/lib/cassandra/saved_caches
```

> rm: cannot remove ‘/var/lib/cassandra/commitlog’: Device or resource busy
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/medusa/medusacli.py", line 212, in restore_node
    verify, set(keyspaces), set(tables), use_sstableloader)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/medusa/restore_node.py", line 48, in restore_node
    keyspaces, tables)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/medusa/restore_node.py", line 88, in restore_node_locally
    clean_path(cassandra.commit_logs_path)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/medusa/restore_node.py", line 214, in clean_path
    subprocess.check_output(['sudo', '-u', p.owner(), 'rm', '-rf', str(p)])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/gevent/subprocess.py", line 348, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['sudo', '-u', 'cassandra', 'rm', '-rf', '/var/lib/cassandra/commitlog']' returned non-zero exit status 1.

Are you thinking of adding a fix please?

**Comment by arodrime** [comment]
Hello @TryToWork :).

**Workaround**: I think using a parent as a mounting point is the easiest workaround: #26. The path you mount and the path to folders are both configurable. I admit it would be nice to have this working by 'default' for people splitting commit logs from data, thus using mounting as you did might be quite common,  I'm not sure. @adejanovski or @ossarga any thoughts on this one?

> Are you thinking of adding a fix please?

Not really, it's something we decided **not to work on** in #26. We could consider addressing this, it's not in our priorities I'd say. But you're the second person coming with this problem. Let's see if you (and more people) would really need this.

**Do you want to give it a try?**
If you want to @TryToWork on this (see what I did there ;-)), an idea of patch was discussed in #26. We can resume this talk here if you're willing to discuss/code that change and open a PR.

**Comment by TryToWork** [comment]
Thanks for your answer.

I will go and see with the people concerned if we can modify the existing clusters for check your solution.

**Comment by arodrime** [comment]
@TryToWork, any new on this? Did it work for you? 

If so, do you think about anything that would help other people not to fall into the same issue and we could do about it (document this, some fix or anything else)?

**Comment by TryToWork** [comment]
Yes it's work if you create a folder inside the mount point but we can't modify our existing clusters ...

**Before :** 
[root@node1~]# df -h
Filesystem                                     Size  Used Avail Use% Mounted on
...
/dev/mapper/vg01-lv_cassandra_commitlog_tst     10G   48M   10G   1% /var/lib/cassandra/commitlog
/dev/mapper/vg01-lv_cassandra_savedcaches_tst  8.0G   33M  8.0G   1% /var/lib/cassandra/saved_caches

**cassandra.yaml :** 
commitlog :/var/lib/cassandra/commitlog/commitlog
saved_caches:/var/lib/cassandra/saved_caches/saved_caches

**After :** 
[root@node1~]# df -h
Filesystem                                     Size  Used Avail Use% Mounted on
...
/dev/mapper/vg01-lv_cassandra_commitlog_tst     10G   48M   10G   1% /var/lib/cassandra/commitlog
/dev/mapper/vg01-lv_cassandra_savedcaches_tst  8.0G   33M  8.0G   1% /var/lib/cassandra/saved_caches

mkdir  /var/lib/cassandra/commitlog/commitlog
mkdir  /var/lib/cassandra/saved_caches/saved_caches

**cassandra.yaml :** 
commitlog :/var/lib/cassandra/commitlog/commitlog
saved_caches:/var/lib/cassandra/saved_caches/saved_caches

**Comment by arodrime** [comment]
#168 should fix this.

Closing the issue. Feel free to reopen if that's not the case.
