### ISSUE TITLE
Unknown host Traceback (most recent call last):

### ISSUE THREAD

**Issue by vijaythakur-plasma** [thelastpickle/cassandra-medusa#118]
I just did a setup for latest medusa.
Following error is seen when we take backup:

root@c2m:~# PATH=$PATH:/etc/c2m/cassandra/bin medusa backup --backup-name=18042020 
[2020-04-18 10:58:04,329] INFO: Monitoring provider is noop
[2020-04-18 10:58:04,337] WARNING: is ccm : 0
[2020-04-18 10:58:04,423] INFO: Creating snapshot
[2020-04-18 10:58:04,423] INFO: Saving tokenmap and schema
[2020-04-18 11:06:43,616] **ERROR: This error happened during the backup: [Errno 1] Unknown host
Traceback (most recent call last):**
  File "/usr/local/lib/python3.6/dist-packages/medusa/backup.py", line 252, in main
    schema, tokenmap = get_schema_and_tokenmap(cassandra)
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value

**Configuration:** 
C*.yaml
listen_address: 192.168.x.x
rpc_address: 192.168.x.x

/etc/hosts:
127.0.0.1 localhost
127.0.1.1 cassandra
192.168.x.x  cassandra 
192.168.x.x localhost

Please guide me what is the missing step.

**Comment by arodrime** [comment]
Hello @vijaythakur-plasma, we have this ASF slack channel where the #cassandra-medusa community is answering questions and doing support: http://s.apache.org/slack-invite 

Would you please make sure there that this is actually a bug and not a misusage as you seem to think? Probably share there the configuration you use (medusa.ini file) and the commands you are running.

If you think we do have a bug, please let us know here, we will work on it. The other way around, please let us know if things work fine after you received support so we can close this ticket.

Thanks!

**Comment by adejanovski** [comment]
Seems like a network configuration issue.
@vijaythakur-plasma, I'll close this issue for now. Feel free to reopen if you're still experiencing this problem.
