### ISSUE TITLE
Zero byte file causes medusa to crash with S3 Storage

### ISSUE THREAD

**Issue by srjacobs** [thelastpickle/cassandra-medusa#144]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952129)

When encountering a zero byte file medusa crashes at `_upload_single_part` in medusa/storage/aws_s3_storage/concurrent.py
The error was 

```
[2020-05-26 02:14:11,122] INFO: Uploading /var/lib/cassandra/data/sync/users-d50a6620152211e88427c50743c8fa22/snapshots/medusa-e972039b-a9a1-474a-8651-5fb850556c35/md-69766-big-SI_idx_user_email.db (0.000B)

[2020-05-26 02:14:32,794] ERROR: This error happened during the backup: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
```

By switching the config option multi_part_upload_threshold to 0 then it would follow the other code path to `_upload_multi_part` and the backup completes successfully.

This is most likely a bug in libcloud rather than Medusa.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-276) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-276

**Comment by hpdsvg** [comment]
I am also running into this issue. Here is log snippet. Is there any workaround or fix for this issue?

```
INFO:root:Uploading /var/lib/cassandra/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/snapshots/medusa-k8ssandra-backup/md-46-big-SI_[redacted]_typeName_idx.db (0.000B)
[2021-12-01 23:39:40,802] INFO: Uploading /var/lib/cassandra/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/snapshots/medusa-k8ssandra-backup/md-46-big-SI_[redacted]_typeName_idx.db (0.000B)
DEBUG:root:Uploading [redacted].k8s.local/cassandra-dc2-default-sts-5/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/md-46-big-SI_[redacted]_typeName_idx.db as single part
[2021-12-01 23:39:40,803] DEBUG: Uploading [redacted].k8s.local/cassandra-dc2-default-sts-5/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/md-46-big-SI_[redacted]_typeName_idx.db as single part
DEBUG:urllib3.connectionpool:Resetting dropped connection: s3-us-east-2.amazonaws.com
[2021-12-01 23:40:00,875] DEBUG: Resetting dropped connection: s3-us-east-2.amazonaws.com
DEBUG:urllib3.connectionpool:Resetting dropped connection: s3-us-east-2.amazonaws.com
[2021-12-01 23:40:41,150] DEBUG: Resetting dropped connection: s3-us-east-2.amazonaws.com
DEBUG:urllib3.connectionpool:Resetting dropped connection: s3-us-east-2.amazonaws.com
[2021-12-01 23:42:01,439] DEBUG: Resetting dropped connection: s3-us-east-2.amazonaws.com
DEBUG:urllib3.connectionpool:Resetting dropped connection: s3-us-east-2.amazonaws.com
[2021-12-01 23:44:01,771] DEBUG: Resetting dropped connection: s3-us-east-2.amazonaws.com
ERROR:root:This error happened during the backup: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>[redacted]</AWSAccessKeyId><StringToSign>[redacted]</StringToSign><SignatureProvided>[redacted]</SignatureProvided><StringToSignBytes>[redacted]</StringToSignBytes><CanonicalRequest>PUT\n/[redacted]/[redacted].k8s.local/cassandra-dc2-default-sts-5/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/md-46-big-SI_[redacted]_typeName_idx.db\n\naccept-encoding:gzip,deflate\ncontent-type:application/octet-stream\nhost:s3-us-east-2.amazonaws.com,s3-us-east-2.amazonaws.com\nuser-agent:libcloud/3.3.1 (Amazon S3 (us-east-2))\nx-amz-content-sha256:UNSIGNED-PAYLOAD\nx-amz-date:20211201T234401Z\nx-amz-storage-class:STANDARD\n\naccept-encoding;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class\nUNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>[redacted]</CanonicalRequestBytes><RequestId>2GA0B4XV4HA786XN</RequestId><HostId>[redacted]</HostId></Error>'
[2021-12-01 23:44:02,096] ERROR: This error happened during the backup: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>[redacted]</AWSAccessKeyId><StringToSign>[redacted]</StringToSign><SignatureProvided>[redacted]</SignatureProvided><StringToSignBytes>[redacted]</StringToSignBytes><CanonicalRequest>PUT\n/[redacted]/[redacted].k8s.local/cassandra-dc2-default-sts-5/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/md-46-big-SI_[redacted]_typeName_idx.db\n\naccept-encoding:gzip,deflate\ncontent-type:application/octet-stream\nhost:s3-us-east-2.amazonaws.com,s3-us-east-2.amazonaws.com\nuser-agent:libcloud/3.3.1 (Amazon S3 (us-east-2))\nx-amz-content-sha256:UNSIGNED-PAYLOAD\nx-amz-date:20211201T234401Z\nx-amz-storage-class:STANDARD\n\naccept-encoding;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class\nUNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>[redacted]</CanonicalRequestBytes><RequestId>2GA0B4XV4HA786XN</RequestId><HostId>[redacted]</HostId></Error>'
Traceback (most recent call last):
  File "/home/cassandra/medusa/backup_node.py", line 345, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/home/cassandra/medusa/storage/s3_base_storage.py", line 102, in upload_blobs
    multi_part_upload_threshold=int(self.config.multi_part_upload_threshold),
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 83, in <lambda>
    storage, connection, src_file, dest, bucket, multi_part_upload_threshold
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 119, in __upload_file
    obj = _upload_single_part(connection, src, bucket, full_object_name)
  File "/home/cassandra/.local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/cassandra/.local/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/cassandra/.local/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/cassandra/.local/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/cassandra/.local/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/cassandra/medusa/storage/s3_compat_storage/concurrent.py", line 127, in _upload_single_part
    str(src), container=bucket, object_name=object_name
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 549, in upload_object
    storage_class=ex_storage_class)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 903, in _put_object
    headers=headers, file_path=file_path, stream=stream)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/base.py", line 837, in _upload_object
    response.parse_error()
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 138, in parse_error
    raise InvalidCredsError(self.body)
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/common/base.py", line 300, in body
    return self.response.body
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/common/base.py", line 293, in response
    self.parse_error()
  File "/home/cassandra/.local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 138, in parse_error
    raise InvalidCredsError(self.body)
libcloud.common.types.InvalidCredsError: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>[redacted]</AWSAccessKeyId><StringToSign>[redacted]</StringToSign><SignatureProvided>[redacted]</SignatureProvided><StringToSignBytes>[redacted]</StringToSignBytes><CanonicalRequest>PUT\n/[redacted]/[redacted].k8s.local/cassandra-dc2-default-sts-5/data/[redacted]/[redacted]-7011fec04d5111ec9c679b4f099150d2/md-46-big-SI_[redacted]_typeName_idx.db\n\naccept-encoding:gzip,deflate\ncontent-type:application/octet-stream\nhost:s3-us-east-2.amazonaws.com,s3-us-east-2.amazonaws.com\nuser-agent:libcloud/3.3.1 (Amazon S3 (us-east-2))\nx-amz-content-sha256:UNSIGNED-PAYLOAD\nx-amz-date:20211201T234401Z\nx-amz-storage-class:STANDARD\n\naccept-encoding;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-storage-class\nUNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>[redacted]</CanonicalRequestBytes><RequestId>2GA0B4XV4HA786XN</RequestId><HostId>[redacted]</HostId></Error>'
DEBUG:root:Cleaning up snapshot

```

**Comment by rzvoncek** [comment]
This got fixed in https://github.com/thelastpickle/cassandra-medusa/issues/533.
