### ISSUE TITLE
Restoring issue. Medusa needs excessive file system permissions.

### ISSUE THREAD

**Issue by house-of-vanity** [thelastpickle/cassandra-medusa#164]
Hi, I've faced an issue with restoring whole cluster.
When all the sstables are downloaded to host from bucket medusa tries to cleaning /srv/cassandra/commitlog by executing `sudo -u cassandra rm -rf /srv/cassandra/commitlog` which deletes entire directory not only the content. Due to permissions medusa fails this step. Note that cassandra doesn't create this directory themself and it's not assumed that cassandra has an access to this directory and only its content should be RW.
Maybe it's better to remove its content by executing `sudo -u cassandra rm -rf /srv/cassandra/commitlog/*` ?

```
[2020-06-19 14:03:59,662] INFO: Stopping Cassandra
[2020-06-19 14:03:59,674] DEBUG: Cleaning (/srv/cassandra/commitlog)
rm: cannot remove '/srv/cassandra/commitlog': Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 33, in <module>
    sys.exit(load_entry_point('cassandra-medusa==0.6.0', 'console_scripts', 'medusa')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cassandra_medusa-0.6.0-py3.6.egg/medusa/medusacli.py", line 211, in restore_node
    verify, set(keyspaces), set(tables), use_sstableloader)
  File "/usr/local/lib/python3.6/dist-packages/cassandra_medusa-0.6.0-py3.6.egg/medusa/restore_node.py", line 48, in restore_node
    keyspaces, tables)
  File "/usr/local/lib/python3.6/dist-packages/cassandra_medusa-0.6.0-py3.6.egg/medusa/restore_node.py", line 88, in restore_node_locally
    clean_path(cassandra.commit_logs_path)
  File "/usr/local/lib/python3.6/dist-packages/cassandra_medusa-0.6.0-py3.6.egg/medusa/restore_node.py", line 230, in clean_path
    subprocess.check_output(['sudo', '-u', p.owner(), 'rm', '-rf', str(p)])
  File "/usr/local/lib/python3.6/dist-packages/gevent-20.6.2-py3.6-linux-x86_64.egg/gevent/subprocess.py", line 404, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['sudo', '-u', 'cassandra', 'rm', '-rf', '/srv/cassandra/commitlog']' returned non-zero exit status 1.
```

**Comment by arodrime** [comment]
This seems related to #26, #109. You're the third one complaining about this, we are now working on this fix.

**Comment by arodrime** [comment]
#168 should fix this. We will cut a new release of medusa soon.

Closing the issue. Feel free to reopen if that does not fix the problem.
