### ISSUE TITLE
Increase connection/retry time out for S3 download

### ISSUE THREAD

**Issue by chidhambaram7** [thelastpickle/cassandra-medusa#181]
I have been testing this tool for quite sometime and it is simple and works well.
I was facing connection timeout/retry timeout exception while restoring 4TB of data into 6 node cluster with `transfer_max_bandwidth = 500MB/s` and `concurrent_transfers =16`. I have manged to completed restore after increasing `MAX_UP_DOWN_LOAD_RETRIES `at https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/aws_s3_storage/concurrent.py#L29
`MAX_ATTEMPTS` https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/restore_node.py#L34, 
`max_retries` at https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/aws_s3_storage/awscli.py#L71
https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/aws_s3_storage/awscli.py#L81

The below config worked for me.
`MAX_UP_DOWN_LOAD_RETRIES = 20` - Multiple attempt to download data from S3
`MAX_ATTEMPTS = 200` - this help when non seed node finishes restore before seed node
`max_retries=20` - Multiple attempt to download data from S3

Also, medusa and medusa-wrapper command is not accessible while doing operations so, I have created a soft link to make it  work `ln -s /usr/local/bin/medusa-wrapper /usr/bin/medusa-wrapper && ln -s /usr/local/bin/medusa /usr/bin/medusa`

**Comment by ivanmp91** [comment]
I'm not sure if is the same issue or not, but also I'm having trouble with restoring large data. In my case I'm trying to restore 12TB of data in a cluster of 9 nodes. The full command used to restore the a backup:

`medusa restore-cluster --backup-name=202008121530 --temp-dir=/opt/cassandra/doc/ --keep-auth`

and medusa config:

```
[cassandra]
stop_cmd = sudo systemctl stop cassandra
start_cmd = sudo systemctl start cassandra
config_file = /opt/cassandra/conf/cassandra.yaml
cql_username = xxxxxx
cql_password = xxxxxxxx
check_running = nodetool version
resolve_ip_addresses = True
[storage]
storage_provider = s3
bucket_name = my-s3-bucket
prefix = cassandra-production-us-east-1
max_backup_age = 3
max_backup_count = 0
transfer_max_bandwidth = 500MB/s
concurrent_transfers = 6
multi_part_upload_threshold = 104857600
[monitoring]
[ssh]
[checks]
[logging]
```

The restore process just starts well, but after 15-20 minutes some nodes start failing, this is the full stack trace:

```
[2020-08-12 18:17:02,224] DEBUG: https://s3.amazonaws.com:443 "GET /my-s3-bucket/cassandra-production-us-east-1/ip-172-22-172-82.ec2.internal/data/convertkit/events_table-a27d734057ad11e9abd40513aa198e3c/mc-97897-bi
g-Digest.crc32?Version=2006-03-01 HTTP/1.1" 200 10
[2020-08-12 18:17:05,449] DEBUG: https://s3.amazonaws.com:443 "HEAD /my-s3-bucket HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/medusa/medusacli.py", line 215, in restore_node
    verify, set(keyspaces), set(tables), use_sstableloader)
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_node.py", line 48, in restore_node
    keyspaces, tables)
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_node.py", line 82, in restore_node_locally
    download_data(config.storage, node_backup, fqtns_to_restore, destination=download_dir)
  File "/usr/local/lib/python3.7/site-packages/medusa/download.py", line 47, in download_data
    storage.storage_driver.download_blobs(srcs, dst)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/s3_storage.py", line 174, in download_blobs
    multi_part_upload_threshold=int(self.config.multi_part_upload_threshold),
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 158, in download_blobs
    job.execute(list(src))
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 154, in <lambda>
    storage, connection, src_file, str(dest), bucket, multi_part_upload_threshold
  File "/usr/local/lib/python3.7/site-packages/medusa/storage/aws_s3_storage/concurrent.py", line 173, in __download_blob
    blob = connection.get_object(bucket.name, str(src))
  File "/usr/local/lib/python3.7/site-packages/libcloud/storage/drivers/s3.py", line 364, in get_object
    response = self.connection.request(object_path, method='HEAD')
  File "/usr/local/lib/python3.7/site-packages/libcloud/common/base.py", line 616, in request
    headers=headers, stream=stream)
  File "/usr/local/lib/python3.7/site-packages/libcloud/http.py", line 232, in request
    verify=self.verification
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

In my case reducing the settings for `concurrent_transfers = 2` and `transfer_max_bandwidth = 300MB/s` just worked, although restore time increases dramatically.

**Comment by adejanovski** [comment]
This was merged into `master`
