### ISSUE TITLE
Unable to Restore Backup (too many values to unpack (expected 5))

### ISSUE THREAD

**Issue by mario-deluna** [thelastpickle/cassandra-medusa#186]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952100)

Hi there, thank you for your work on this tool!

Unfortunately im currently unable to restore a backup I keep running into the same issue.

Creating the backup seems to work fine. (Im using s3 Storage)
I can see all the backup files on s3 also I get the following output:

```
[2020-08-04 11:15:29,474] INFO: Updating backup index
[2020-08-04 11:15:30,194] INFO: Backup done
[2020-08-04 11:15:30,194] INFO: - Started: 2020-08-04 11:15:11
                        - Started extracting data: 2020-08-04 11:15:13
                        - Finished: 2020-08-04 11:15:30
[2020-08-04 11:15:30,194] INFO: - Real duration: 0:00:16.800644 (excludes time waiting for other nodes)
[2020-08-04 11:15:30,195] INFO: - 328 files, 95.92 MB
[2020-08-04 11:15:30,195] INFO: - 64 files copied from host
[2020-08-04 11:15:30,195] INFO: - 264 copied from previous backup (main3)
```

But running any command that has to read a backup, like `restore-node`, `restore-cluster` or `status` fails with the same error:

```
ValueError: too many values to unpack (expected 5)
```

Stacktrace of `restore-cluster`:

```
root@activity-service-stage-01:/var/www# medusa restore-cluster --backup-name=pjas-as-01 --seed-target localhost
[2020-08-04 13:07:46,089] INFO: Monitoring provider is noop
[2020-08-04 13:07:46,885] ERROR: This error happened during the cluster restore: too many values to unpack (expected 5)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 61, in orchestrate
    cluster_backup = storage.get_cluster_backup(backup_name)
  File "/usr/local/lib/python3.8/dist-packages/medusa/storage/__init__.py", line 380, in get_cluster_backup
    for cluster_backup in self.list_cluster_backups():
  File "/usr/local/lib/python3.8/dist-packages/medusa/storage/__init__.py", line 318, in list_cluster_backups
    node_backups = sorted(
  File "/usr/local/lib/python3.8/dist-packages/medusa/storage/__init__.py", line 177, in list_node_backups
    _, _, _, backup_name, tokenmap_file = backup_index_entry.split('/')
ValueError: too many values to unpack (expected 5)
```

Stacktrace of `status`:

```
ubuntu@pjas-activity-service:~$ medusa status --backup-name main3
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/medusa/medusacli.py", line 225, in status
    medusa.status.status(medusaconfig, backup_name)
  File "/usr/local/lib/python3.6/dist-packages/medusa/status.py", line 30, in status
    cluster_backup = storage.get_cluster_backup(backup_name)
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 380, in get_cluster_backup
    for cluster_backup in self.list_cluster_backups():
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 320, in list_cluster_backups
    key=lambda b: (b.name, b.started)
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 177, in list_node_backups
    _, _, _, backup_name, tokenmap_file = backup_index_entry.split('/')
ValueError: too many values to unpack (expected 5)
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-294) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-294

**Comment by rzvoncek** [comment]
This seems to duplicate #212. 
Even though this issue is older, I'll mark it as duplicate. The other one has some conversation in it, which probably makes it a better starting point.

**Comment by rzvoncek** [comment]
We resolved the other issue, considering this closed too.
