### ISSUE TITLE
Purge backup does not delete orphan data files

### ISSUE THREAD

**Issue by srjacobs** [thelastpickle/cassandra-medusa#188]
I think with S3 storage, if a prefix is specified, that the code in `get_file_paths_from_storage` does not take into account that prefix and so finds no files as candidates for purging.

I have files that are no longer in any manifests that are still in the data.  14 days of backups and months worth of data files - and this is a for a table that changed compaction strategy more than 14 days ago.

**Comment by adejanovski** [comment]
Good catch @srjacobs,

We'll try to fix this ASAP.

**Comment by srjacobs** [comment]
For the moment I have changed the line in purge.py:150 from
     `data_directory = "{}/data".format(fqdn)`
to
    `data_directory = "{}{}/data".format(storage.prefix_path, fqdn)`
and it is clearing out files from the data directory now.
I don't know if it's enough or if it has other ramifications.
It should probably rely somehow getting the data directory from the actual NodeBackup object via `data_path`

**Comment by ivanmp91** [comment]
I think we're facing with the same issue too. The purge process is failing with the following error:

```
stderr: [2021-01-05 02:15:12,730] INFO: Monitoring provider is noop
[2021-01-05 02:15:12,731] INFO: Starting purge
[2021-01-05 02:15:13,492] INFO: Listing backups for ip-192-168-43-9.ec2.internal
[2021-01-05 02:15:18,453] INFO: 12 backups are candidate to be purged
[2021-01-05 02:15:18,453] INFO: Purging backup 202101010330 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:18,902] INFO: Purging backup 202101010530 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:19,447] INFO: Purging backup 202101010730 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:19,877] INFO: Purging backup 202101010930 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:20,383] INFO: Purging backup 202101011130 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:20,845] INFO: Purging backup 202101011330 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:21,346] INFO: Purging backup 202101011530 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:21,787] INFO: Purging backup 202101011730 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:22,248] INFO: Purging backup 202101011930 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:22,786] INFO: Purging backup 202101012130 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:23,251] INFO: Purging backup 202101012330 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:23,756] INFO: Purging backup 202101020130 from node ip-192-168-43-9.ec2.internal...
[2021-01-05 02:15:24,251] INFO: Cleaning up orphaned files for ip-192-168-43-9.ec2.internal...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/purge.py", line 45, in main
    purge_backups(storage, backups_to_purge)
  File "/usr/local/lib/python3.7/site-packages/medusa/purge.py", line 102, in purge_backups
    (cleaned_objects_count, cleaned_objects_size) = cleanup_obsolete_files(storage, fqdn)
  File "/usr/local/lib/python3.7/site-packages/medusa/purge.py", line 136, in cleanup_obsolete_files
    paths_in_manifest = get_file_paths_from_manifests_for_differential_backups(backups)
  File "/usr/local/lib/python3.7/site-packages/medusa/purge.py", line 162, in get_file_paths_from_manifests_for_differential_backups
    manifests = list(map(lambda backup: json.loads(backup.manifest), differential_backups))
  File "/usr/local/lib/python3.7/site-packages/medusa/purge.py", line 162, in <lambda>
    manifests = list(map(lambda backup: json.loads(backup.manifest), differential_backups))
  File "/usr/lib64/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2021-01-05 02:15:53,276] ERROR: This error happened during the purge: the JSON object must be str, bytes or bytearray, not NoneType
```

It looks like the backup metadata is deleted but the files are still there in s3. Is there any prevision for fixing that issue? Also once this is fixed, will it require any extra actions to delete the orphaned files from those old backups that were deleted or next purge would delete all these orphaned files from s3?
