### ISSUE TITLE
Medusa not installing via PIP

### ISSUE THREAD

**Issue by alvaropalmeirao** [thelastpickle/cassandra-medusa#207]
```
# sudo pip3 install cassandra-medusa[S3]
Collecting cassandra-medusa[S3]
  Downloading https://files.pythonhosted.org/packages/7d/87/121fdaba641fe2880bd80e4d8343f8e4f4371bc501fc0b7d4754d6f44b98/cassandra_medusa-0.7.1-py3-none-any.whl (110kB)
    100% |████████████████████████████████| 112kB 203kB/s 
Collecting parallel-ssh==1.9.1 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/7a/c4/e72c0af11bd55130f3f140c520be380ae24ff9f961daad16818ac6c23720/parallel_ssh-1.9.1-cp37-cp37m-manylinux1_x86_64.whl (174kB)
    100% |████████████████████████████████| 184kB 513kB/s 
Collecting Click>=6.7 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 689kB/s 
Collecting cassandra-driver>=3.14.0 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/af/a5/059844af25f0cc448a9c0d41bb2d9beb4a9d328a4a0094835af243a3ee3b/cassandra_driver-3.24.0-cp37-cp37m-manylinux1_x86_64.whl (3.8MB)
    100% |████████████████████████████████| 3.8MB 228kB/s 
Collecting ffwd>=0.0.2 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/08/62/55b6ecc62d5f25fbc4dfbc76d4a5390cf2085042c9a0550ab147b00ff157/ffwd-0.0.2.tar.gz
Collecting python-dateutil<2.8.1,>=2.1 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 593kB/s 
Collecting apache-libcloud>=2.8.0 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/cc/2d/ebd90ce51ee3cafe7d795571029be05841b553f296ee309abed057ddd5cd/apache_libcloud-3.2.0-py2.py3-none-any.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 288kB/s 
Collecting retrying>=1.3.3 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Collecting psutil>=5.4.7 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz (460kB)
    100% |████████████████████████████████| 460kB 629kB/s 
Collecting PyYAML>=5.1 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 690kB/s 
Collecting requests==2.22.0 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 827kB/s 
Collecting lockfile>=0.12.2 (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: pycrypto>=2.6.1 in /usr/lib/python3/dist-packages (from cassandra-medusa[S3]) (2.6.1)
Collecting awscli>=1.16.291; extra == "s3" (from cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/8d/d4/11e75e7f16b4427c5b7ed18838022dd2304adb2d44ae30acfad9f35774ce/awscli-1.18.149-py2.py3-none-any.whl (3.3MB)
    100% |████████████████████████████████| 3.3MB 343kB/s 
Collecting paramiko (from parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 1.4MB/s 
Collecting gevent>=1.1 (from parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/78/c4/0c59bf329240981fd3a228ac809a82d00d4b147a82555eb4dddba2d041aa/gevent-20.9.0.tar.gz (5.8MB)
    100% |████████████████████████████████| 5.8MB 120kB/s 
  Installing build dependencies ... done
Collecting ssh2-python>=0.17.0 (from parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/27/22/90452ef0261e9f6fbceb231210c1384993bc5f2ae33d893903078c52ce49/ssh2-python-0.20.0.tar.gz (535kB)
    100% |████████████████████████████████| 542kB 506kB/s 
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from cassandra-driver>=3.14.0->cassandra-medusa[S3]) (1.12.0)
Collecting geomet<0.3,>=0.1 (from cassandra-driver>=3.14.0->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/c9/81/156ca48f950f833ddc392f8e3677ca50a18cb9d5db38ccb4ecea55a9303f/geomet-0.2.1.post1-py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.22.0->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 433kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.22.0->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 416kB/s 
Collecting certifi>=2017.4.17 (from requests==2.22.0->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 576kB/s 
Collecting idna<2.9,>=2.5 (from requests==2.22.0->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 651kB/s 
Collecting colorama<0.4.4,>=0.2.5; python_version != "3.4" (from awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0 (from awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 528kB/s 
Collecting botocore==1.18.8 (from awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/b2/8e/e711e5a0191ae12a88e2e55294a3033f2f00ad847b8a3da15da3de2b5194/botocore-1.18.8-py2.py3-none-any.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 250kB/s 
Collecting rsa<=4.5.0,>=3.1.2; python_version != "3.4" (from awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/26/f8/8127fdda0294f044121d20aac7785feb810e159098447967a6103dedfb96/rsa-4.5-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
    100% |████████████████████████████████| 552kB 1.6MB/s 
Collecting bcrypt>=3.1.3 (from paramiko->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/52/a7/51ab6481ac355517696477889d8ab232106a0ddadda642c54e47a2ab40b9/bcrypt-3.2.0-cp36-abi3-manylinux1_x86_64.whl (63kB)
    100% |████████████████████████████████| 71kB 1.8MB/s 
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko->parallel-ssh==1.9.1->cassandra-medusa[S3]) (2.6.1)
Collecting pynacl>=1.0.1 (from paramiko->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/9d/57/2f5e6226a674b2bcb6db531e8b383079b678df5b10cdaa610d6cf20d77ba/PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961kB)
    100% |████████████████████████████████| 962kB 696kB/s 
Collecting zope.event (from gevent>=1.1->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/9e/85/b45408c64f3b888976f1d5b37eed8d746b8d5729a66a49ec846fda27d371/zope.event-4.5.0-py2.py3-none-any.whl
Collecting zope.interface (from gevent>=1.1->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/f3/21/8db61925409f4a4bac5fac19dbee26b735bd410b0f05f233058ace5511dc/zope.interface-5.1.0-cp37-cp37m-manylinux1_x86_64.whl (235kB)
    100% |████████████████████████████████| 245kB 1.4MB/s 
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent>=1.1->parallel-ssh==1.9.1->cassandra-medusa[S3]) (40.8.0)
Collecting greenlet>=0.4.17 (from gevent>=1.1->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Using cached https://files.pythonhosted.org/packages/b4/34/2c4ea49f9d41aaf664f72abb10880a56d3560398b74b3936055579188836/greenlet-0.4.17-cp37-cp37m-manylinux1_x86_64.whl
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.18.8->awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<=4.5.0,>=3.1.2; python_version != "3.4"->awscli>=1.16.291; extra == "s3"->cassandra-medusa[S3])
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 2.1MB/s 
Collecting cffi>=1.1 (from bcrypt>=3.1.3->paramiko->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Using cached https://files.pythonhosted.org/packages/26/d7/1c485a42d59d45f14f27bb93769e56142518c85ddf379dbdad7e42d0ffcd/cffi-1.14.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.1->bcrypt>=3.1.3->paramiko->parallel-ssh==1.9.1->cassandra-medusa[S3])
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Building wheels for collected packages: ffwd, retrying, psutil, PyYAML, gevent, ssh2-python
  Running setup.py bdist_wheel for ffwd ... done
  Stored in directory: /root/.cache/pip/wheels/05/5a/9f/9539cd6246b938aaab98820179d7d64256aa39593426c72bf4
  Running setup.py bdist_wheel for retrying ... done
  Stored in directory: /root/.cache/pip/wheels/d7/a9/33/acc7b709e2a35caa7d4cae442f6fe6fbf2c43f80823d46460c
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/39/a0/f5/c4fa280463e29aea07797acb5312358fefb067c1f4f98e11b1
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
  Running setup.py bdist_wheel for gevent ... done
  Stored in directory: /root/.cache/pip/wheels/66/89/6a/7438b05445edc27023a9d8935801d4e70ed962e02541e57fbd
  Running setup.py bdist_wheel for ssh2-python ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dd3hno18/ssh2-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-snvmbiqp --python-tag cp37:
  /bin/sh: 1: cmake: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-dd3hno18/ssh2-python/setup.py", line 34, in <module>
      build_ssh2()
    File "/tmp/pip-install-dd3hno18/ssh2-python/_setup_libssh2.py", line 24, in build_ssh2
      shell=True, env=os.environ)
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'cmake ../libssh2 -DBUILD_SHARED_LIBS=ON     -DENABLE_ZLIB_COMPRESSION=ON -DENABLE_CRYPT_NONE=ON     -DENABLE_MAC_NONE=ON -DCRYPTO_BACKEND=OpenSSL' returned non-zero exit status 127.
  
  ----------------------------------------
  Failed building wheel for ssh2-python
  Running setup.py clean for ssh2-python
Successfully built ffwd retrying psutil PyYAML gevent
Failed to build ssh2-python
Installing collected packages: pycparser, cffi, bcrypt, pynacl, paramiko, zope.event, zope.interface, greenlet, gevent, ssh2-python, parallel-ssh, Click, geomet, cassandra-driver, ffwd, python-dateutil, chardet, urllib3, certifi, idna, requests, apache-libcloud, retrying, psutil, PyYAML, lockfile, colorama, jmespath, botocore, s3transfer, pyasn1, rsa, docutils, awscli, cassandra-medusa
  Running setup.py install for ssh2-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dd3hno18/ssh2-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-16yk6cms/install-record.txt --single-version-externally-managed --compile:
    /bin/sh: 1: cmake: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dd3hno18/ssh2-python/setup.py", line 34, in <module>
        build_ssh2()
      File "/tmp/pip-install-dd3hno18/ssh2-python/_setup_libssh2.py", line 24, in build_ssh2
        shell=True, env=os.environ)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'cmake ../libssh2 -DBUILD_SHARED_LIBS=ON     -DENABLE_ZLIB_COMPRESSION=ON -DENABLE_CRYPT_NONE=ON     -DENABLE_MAC_NONE=ON -DCRYPTO_BACKEND=OpenSSL' returned non-zero exit status 127.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dd3hno18/ssh2-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-16yk6cms/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-dd3hno18/ssh2-python/
```

```
# cat /etc/debian_version
9.12
```

**Comment by vinovarov** [comment]
Basically this error says that you're missing `cmake`.

On Debian 9.13 I needed to install a few more packages before installing Medusa via pip3, it took some trial and error yesterday:

```
apt install python3-pip cmake openssl libssl-dev zlib1g-dev -y
```

(Medusa does not run even after that as of now, but at least it's installed)

**Comment by alvaropalmeirao** [comment]
True that worked, Thanks!
Now the error is other:
```No module named 'ssh2.error_codes'```

**Comment by vinovarov** [comment]
That's right: https://github.com/thelastpickle/cassandra-medusa/issues/208

Welcome to the club =)

**Comment by alvaropalmeirao** [comment]
Ahahah, i'll close this issue and follow that one. 
Thanks again.

**Comment by michaelsembwever** [comment]
ParallelSSH's ssh2-python version 0.20.0 breaks it.
```
pip3 install ssh2-python==0.19.0
```
should fix things for you.
