### ISSUE TITLE
restore-cluster failes  on 

### ISSUE THREAD

**Issue by sigalits** [thelastpickle/cassandra-medusa#234]
hello
I am trying to restore-cluster, and it failes with this message:
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 'v' ([v])">

any idea how can it be fixed , even manually at this point?
The log file doesn't have any extra information on this one.

Thanks
Sigalit

**Comment by sigalits** [comment]
adding more info got from the verbosity option:
2020-12-10 11:47:38,569] DEBUG: Creating MV rolemappingks.e
[2020-12-10 11:47:38,572] ERROR: This error happened during the cluster restore: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 'v' ([v])">
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_cluster.py", line 69, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_cluster.py", line 144, in execute
    self._restore_data()
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_cluster.py", line 363, in _restore_data
    self._restore_schema()
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_cluster.py", line 427, in _restore_schema
    self._create_or_recreate_schema_objects(session, keyspace, schema[keyspace])
  File "/usr/local/lib/python3.7/site-packages/medusa/restore_cluster.py", line 457, in _create_or_recreate_schema_objects
    session.execute(mv[1])
  File "/usr/local/lib/python3.7/site-packages/medusa/cassandra_utils.py", line 221, in execute
    return self.session.execute(query)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 'v' ([v])">

might be mview isssue?

**Comment by arodrime** [comment]
@sigalits - This seems related to #169 . We don't support MV properly yet it seems. We still have check and fix this.

We really welcome contributions and we are busy most of us on other priorities at the moment as MVs are still experimental and they are not widely used.

If you found the bug and want to fixed it, or you found your way around it and can share it, that would be great!

Anyway, let us know what's the status there.
