### ISSUE TITLE
Problem restoring to the same cluster - cassandra-medusa (0.8.0.dev0)

### ISSUE THREAD

**Issue by bkrajmalnik1** [thelastpickle/cassandra-medusa#241]
Hello,

I am running Medusa on CentOS.
Single node restores are working without issue.
However, a cluster-wide restore is failing.
By checking a debug level log from medusa, I can see that on all 3 nodes the data files are moved from the backup repository to the data directory, and the commitlogs are removed.
I ran the medusa on the seed node, and did not pass an explicit seed-node parameter, so it inferred itself as the seed node.
From medusa.log, we see the following:

[2020-12-21 17:11:46,856] INFO: No --seeds specified so we will not wait for any
[2020-12-21 17:11:46,856] INFO: Starting Cassandra
[2020-12-21 17:11:46,857] DEBUG: Starting Cassandra with ['sudo', 'systemctl', 'start', 'cassandra']
[2020-12-21 17:11:46,916] DEBUG: Cleaning (/tmp/medusa-restore-e84b3ad0-16d2-4fe3-b2c2-8a3b7d516c72)
[2020-12-21 17:11:46,917] DEBUG: Remove folder /tmp/medusa-restore-e84b3ad0-16d2-4fe3-b2c2-8a3b7d516c72 and content

On the other nodes, I see the following:

[2020-12-21 17:11:47,221] DEBUG: This server has systemd: True
[2020-12-21 17:11:47,222] WARNING: is ccm : 0
[2020-12-21 17:11:47,521] DEBUG: The node cass01.testdomain.local is not up yet...
[2020-12-21 17:11:47,521] INFO: No seeds are up yet, will wait a minute
[2020-12-21 17:12:47,543] DEBUG: This server has systemd: True
[2020-12-21 17:12:47,544] WARNING: is ccm : 0
[2020-12-21 17:12:47,838] DEBUG: The node cass01.testdomain.local is not up yet...
[2020-12-21 17:12:47,838] INFO: No seeds are up yet, will wait a minute

Looking at the code, it appears that it is checking by executing this code

def is_open(host, port):
    timeout = 3
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(timeout)
    is_accessible = False
    try:
        s.connect((host, port))
        s.shutdown(socket.SHUT_RDWR)
        is_accessible = True
    except socket.error as e:
        logging.debug('Port {} close on host {}'.format(port, host), exc_info=e)
        is_accessible = False
    finally:
        s.close()
        return is_accessible

and it appears to just be stuck somewhere.
I have verified that I can telnet from the non-seed nodes to the system without issue

# telnet cass01.testdomain.local 9042
Trying 10.254.254.81...
Connected to cass01.testdomain.local.

# telnet cass01.testdomain.local 9160
Trying 10.254.254.81...
Connected to cass01.testdomain.local.

Below is a list of all installed modules

# pip3 list --format=columns
Package          Version

- - -
apache-libcloud  3.2.0
bcrypt           3.2.0
cassandra-driver 3.24.0
cassandra-medusa 0.8.0.dev0
certifi          2020.11.8
cffi             1.14.3
chardet          3.0.4
click            7.1.2
cryptography     3.2.1
ffwd             0.0.2
geomet           0.2.1.post1
gevent           20.9.0
greenlet         0.4.17
idna             2.8
lockfile         0.12.2
parallel-ssh     1.9.1
paramiko         2.7.2
pip              9.0.3
psutil           5.7.3
pycparser        2.20
pycrypto         2.6.1
PyNaCl           1.4.0
python-dateutil  2.8.0
PyYAML           5.3.1
requests         2.22.0
retrying         1.3.3
setuptools       39.2.0
six              1.15.0
ssh2-python      0.19.0
urllib3          1.25.11
wheel            0.35.1
zope.event       4.5.0
zope.interface   5.2.0

**Comment by Speissi** [comment]
I'm seeing same behaviour while trying to restore backups on a cluster. Verified that the ports are open and nodes can talk with each other and the seed node has Cassandra up and running. However still getting `No seeds are up yet, will wait a minute` messages in the log and restore process stuck at that point.

**Comment by m934030039** [comment]
We encountered this issue, too.
Here is our goal below
Cluster restore for 6 nodes (3 x seed nodes and 3 s non-seed nodes) from S3 via Medusa.
Here is the symptom from my observation.
Phase1: (OK), initial cluster restore
Phase2: (OK), restore data
Phase3: (???), cassandra.service cannot be started up for ALL nodes. (only seed nodes are up)
             The STDOUT keep repeating below but cassandra.service had been already up (cass-0[1..3] are seed nodes)
             # nodetool status list UN status for 3 seed nodes. 
[skip]
[2021-02-05 23:37:11,249] DEBUG: This server has systemd: True
[2021-02-05 23:37:11,250] WARNING: is ccm : 0
[2021-02-05 23:37:11,264] DEBUG: The node cass-01.example.org is not up yet...
[2021-02-05 23:37:11,269] DEBUG: This server has systemd: True
[2021-02-05 23:37:11,269] WARNING: is ccm : 0
[2021-02-05 23:37:11,284] DEBUG: The node cass-02.example.org is not up yet...
[2021-02-05 23:37:11,288] DEBUG: This server has systemd: True
[2021-02-05 23:37:11,289] WARNING: is ccm : 0
[2021-02-05 23:37:11,303] DEBUG: The node cass-03.example.org is not up yet...
[2021-02-05 23:37:11,303] INFO: No seeds are up yet, will wait a minute
[2021-02-05 23:38:11,370] DEBUG: This server has systemd: True
[2021-02-05 23:38:11,370] WARNING: is ccm : 0
[2021-02-05 23:38:11,385] DEBUG: The node cass-01.example.org is not up yet...
[2021-02-05 23:38:11,391] DEBUG: This server has systemd: True
[2021-02-05 23:38:11,391] WARNING: is ccm : 0
[2021-02-05 23:38:11,405] DEBUG: The node cass-02.example.org is not up yet...
[2021-02-05 23:38:11,410] DEBUG: This server has systemd: True
[2021-02-05 23:38:11,411] WARNING: is ccm : 0
[2021-02-05 23:38:11,425] DEBUG: The node cass-03.example.org is not up yet...
so l#1: user manually run command line # systemctl start cassandra.service
sol #2: This is not recommended. In cassandra.yaml, to add all nodes ip addr for seeds parameters
      - seeds: "${allCassNodesIpAddr}"

**Comment by m934030039** [comment]
The same issue during the cluster-restore, only seed nodes (cass-01/02/03) were brought up but others were not.
Finally, STDOUT is ERROR: Some nodes failed to restore. Exiting

More details below

[2021-03-16 23:14:43,311] DEBUG: Command started
[2021-03-17 14:16:42,453] ERROR: Job executing "mkdir -p /backup/restore/medusa-job-b8c64e9d-1ed5-43b4-aedc-2413ee11c989; cd /backup/restore/medusa-job-b8c64e9d-1ed5-43b4-aedc-2413ee11c989 && /usr/local/bin/medusa-wrapper sudo /usr/local/bin/medusa --fqdn=%s -vvv restore-node --in-place  %s --no-verify --backup-name s3.full.backup --temp-dir /backup/restore   " ran and finished with errors on following nodes: ['cass-04.example.org', 'cass-05.example.org', 'cass-06.example.org', 'cass-07.example.org', 'cass-08.example.org', 'cass-09.example.org', 'cass-10.example.org'][2021-03-17 14:16:42,455] ERROR: Some nodes failed to restore. Exiting
[2021-03-17 14:16:42,455] ERROR: This error happened during the cluster restore: Some nodes failed to restore. ExitingTraceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 68, in orchestrate    restore.execute()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 144, in execute    self._restore_data()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 335, in _restore_data    raise Exception(err_msg)
Exception: Some nodes failed to restore. Exiting

Medusa Log on Failed Node:

[2021-03-17 10:03:09,960] DEBUG: The node cass-01.example.org is not up yet...
[2021-03-17 10:03:09,972] DEBUG: This server has systemd: True
[2021-03-17 10:03:09,973] WARNING: is ccm : 0
[2021-03-17 10:03:09,987] DEBUG: The node cass-02.example.org is not up yet...
[2021-03-17 10:03:09,999] DEBUG: This server has systemd: True
[2021-03-17 10:03:09,999] WARNING: is ccm : 0
[2021-03-17 10:03:10,014] DEBUG: The node cass-03.example.org is not up yet...
[2021-03-17 10:03:10,014] INFO: No seeds are up yet, will wait a minute
[2021-03-17 10:04:10,051] ERROR: Gave up waiting for seeds, aborting the restore

**Comment by adejanovski** [comment]
It looks like there's an exception that we're not catching [in this method](https://github.com/thelastpickle/cassandra-medusa/blob/v0.8.0/medusa/cassandra_utils.py#L684-L698). This is hiding us the real issue...
Otherwise we'd get [the following logging](https://github.com/thelastpickle/cassandra-medusa/blob/v0.8.0/medusa/cassandra_utils.py#L694):  `logging.debug('Port {} close on host {}'.format(port, host), exc_info=e)`

A question though: is the native port (9042 by default) accessible between nodes? Medusa will check if the port is opened to ensure the node have restarted.
Another question: is client encryption turned on in your cluster?

**Comment by bkrajmalnik1** [comment]
Hi Alexander,

As you can see from my initial report, I was able to open a connection to both 9042 and 9160.  Also, I am not using, in this initial deployment, client encryption (in which case I believe it would connect to 9142?)

**Comment by m934030039** [comment]
Alexander,

>A question though: is the native port (9042 by default) accessible between
nodes? Medusa will check if the port is opened to ensure the node have
restarted.
(Sheng 03/19): Yes, it only works for up and running nodes after Medusa did
cluster restore action.
We are using command line to test connectivity below

*      # cqlsh --ssl  ${remoteHostIpaddr}*

NOTE:  Firewalld is disabled and configures the cqlshrc file properly below.

cqlshrc file below
[authentication]
username = ${userName}
password = ${passWord}

[connection]
hostname = ${localHostIpaddr}
port = 9042

[ssl]
certfile = /full/path/to/certFile.crt
validate = true

>Another question: is client encryption turned on in your cluster?
(Sheng 03/19): Yes, we did. Here is the part of the configuration below
In cassandra.yaml file.
[SNIP]
[/SNIP]
server_encryption_options:
    internode_encryption: all
    keystore: /full/path/to/keyStore.jks
    keystore_password:  keyStorePassword
    truststore: /full/path/to/trustStore.jks
    truststore_password:  trustStorePassword

client_encryption_options:
    enabled: true

    optional: false
    keystore: / /full/path/to/keyStore.jks
    keystore_password:  keyStorePassword

    require_client_auth: false
    truststore: /full/path/to/trustStore.jks
    truststore_password: trustStorePassword
[SNIP]
[/SNIP

-Sheng

**Comment by adejanovski** [comment]
@m934030039, thanks for this additional information.
Since client encryption is enabled, the driver will connect through port 9142 by default which Medusa doesn't check. We need to seamlessly check both the native port and the native ssl port to see if any of them is listening, otherwise non seed nodes will never see seed nodes running. I guess we could double down here and also check the gossip ports (with and without encryption) as the native port may not be opened between nodes, but the gossip one surely is.

I'll see if we can handle this change shortly.

**Comment by m934030039** [comment]
> The same issue during the cluster-restore, only seed nodes (cass-01/02/03) were brought up but others were not. Finally, STDOUT is ERROR: Some nodes failed to restore. Exiting
> 
> More details below
> 
> [2021-03-16 23:14:43,311] DEBUG: Command started [2021-03-17 14:16:42,453] ERROR: Job executing "mkdir -p /backup/restore/medusa-job-b8c64e9d-1ed5-43b4-aedc-2413ee11c989; cd /backup/restore/medusa-job-b8c64e9d-1ed5-43b4-aedc-2413ee11c989 && /usr/local/bin/medusa-wrapper sudo /usr/local/bin/medusa --fqdn=%s -vvv restore-node --in-place %s --no-verify --backup-name s3.full.backup --temp-dir /backup/restore " ran and finished with errors on following nodes: ['cass-04.example.org', 'cass-05.example.org', 'cass-06.example.org', 'cass-07.example.org', 'cass-08.example.org', 'cass-09.example.org', 'cass-10.example.org'][2021-03-17 14:16:42,455] ERROR: Some nodes failed to restore. Exiting [2021-03-17 14:16:42,455] ERROR: This error happened during the cluster restore: Some nodes failed to restore. ExitingTraceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 68, in orchestrate restore.execute() File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 144, in execute self._restore_data() File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 335, in _restore_data raise Exception(err_msg) Exception: Some nodes failed to restore. Exiting
> 
> Medusa Log on Failed Node:
> 
> [2021-03-17 10:03:09,960] DEBUG: The node cass-01.example.org is not up yet... [2021-03-17 10:03:09,972] DEBUG: This server has systemd: True [2021-03-17 10:03:09,973] WARNING: is ccm : 0 [2021-03-17 10:03:09,987] DEBUG: The node cass-02.example.org is not up yet... [2021-03-17 10:03:09,999] DEBUG: This server has systemd: True [2021-03-17 10:03:09,999] WARNING: is ccm : 0 [2021-03-17 10:03:10,014] DEBUG: The node cass-03.example.org is not up yet... [2021-03-17 10:03:10,014] INFO: No seeds are up yet, will wait a minute [2021-03-17 10:04:10,051] ERROR: Gave up waiting for seeds, aborting the restore

Update: we tested cluster restore on Medusa version 0.11.2 and cassandra.service on ALL nodes will be bring up ans running. 

-Sheng
