### ISSUE TITLE
Problem in starting Backup

### ISSUE THREAD

**Issue by bprakash321** [thelastpickle/cassandra-medusa#273]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952076)

seeing a problem in starting Backup on a GCP ubuntu node.

Linux <hostname> 4.15.0-1084-gcp #95~16.04.1-Ubuntu SMP Thu Sep 10 03:45:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

/etc/medusa> medusa backup

[2021-02-02 19:52:56,132] INFO: Monitoring provider is noop

[2021-02-02 19:52:57,376] WARNING: is ccm : 0

[2021-02-02 19:52:57,377] ERROR: This error happened during the backup: invalid file: PosixPath('/etc/dse/cassandra/cassandra.yaml')

Traceback (most recent call last):

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/backup_node.py", line 163, in main

```
cassandra = Cassandra(config)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/cassandra_utils.py", line 313, in **init**

```
config_reader = CassandraConfigReader(cassandra_config.config_file)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/cassandra_utils.py", line 234, in **init**

```
with open(config_file, 'r') as f:
```

TypeError: invalid file: PosixPath('/etc/dse/cassandra/cassandra.yaml')

/etc/medusa> ls -lrt /etc/dse/cassandra/cassandra.yaml

-rw-r--r-- 1 cassandra cassandra 59360 May 15  2020 /etc/dse/cassandra/cassandra.yaml

/etc/medusa> medusa --config-file /etc/dse/cassandra/cassandra.yaml backup

Traceback (most recent call last):

  File "/usr/bin/medusa", line 8, in <module>

```
sys.exit(cli())
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/core.py", line 829, in **call**

```
return self.main(*args, **kwargs)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/core.py", line 782, in main

```
rv = self.invoke(ctx)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/core.py", line 1256, in invoke

```
Command.invoke(self, ctx)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/core.py", line 1066, in invoke

```
return ctx.invoke(self.callback, **ctx.params)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/core.py", line 610, in invoke

```
return callback(*args, **kwargs)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/click/decorators.py", line 21, in new_func

```
return f(get_current_context(), *args, **kwargs)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/medusacli.py", line 111, in cli

```
ctx.obj = medusa.config.load_config(args, config_file)
```

  File "/usr/share/cassandra-medusa/lib/python3.5/site-packages/medusa/config.py", line 147, in load_config

```
config.read_file(config_file.open())
```

  File "/usr/lib/python3.5/configparser.py", line 715, in read_file

```
self._read(f, source)
```

  File "/usr/lib/python3.5/configparser.py", line 1077, in _read

```
raise MissingSectionHeaderError(fpname, lineno, line)
```

configparser.MissingSectionHeaderError: File contains no section headers.

file: '/etc/dse/cassandra/cassandra.yaml', line: 9

"cluster_name: 'QP COM-Sterling Cache'\n"

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-242) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-242

**Comment by v3n1kk** [comment]
Hi, @bprakash321
This problem solving is installing python3.8 packages and later. 
apt install python3.8
apt-get install python3.8-dev
update-alternatives --remove python /usr/bin/python2
update-alternatives --install /usr/bin/python python /usr/bin/python3.8 10

I hope it will be helpful

**Comment by rzvoncek** [comment]
This seems to have been solved by @v3n1kk , marking as stale and closing eventually.
