### ISSUE TITLE
Hash differences when running "medusa verify" due to table size changes

### ISSUE THREAD

**Issue by pzoblisein** [thelastpickle/cassandra-medusa#274]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952073)

Hi,

We occasionally experience hash mismatches due to table size changes when running differential backups.

Generic error:

```
[2021-02-03 15:17:58,511] ERROR: Expected {'path': 'ip-1-2-3-4.eu-west-1.compute.internal/data/keyspace/tablename-hash/md-1234-big-Summary.db', 'MD5': '5636ff225cdfda5d17ba34775ccdb1d0', 'size': 46033} but got <Object: name=ip-1-2-3-4.eu-west-1.compute.internal/data/keyspace/tablename-hash/md-1234-big-Summary.db, size=70427, hash=a1241fd5b7f8347aa5f489f19ff62b7a, provider=Amazon S3 (eu-west-1) ...>
- Manifest validation: Failed!
```

Then a list/summary of blob differences:

```
- [ip-1-2-3-4.eu-west-1.compute.internal/data/keyspace/[tablename-hash/md-1234-big-Summary.db] Blob different
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/medusa/medusacli.py", line 235, in verify
    medusa.verify.verify(medusaconfig, backup_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/verify.py", line 52, in verify
    raise RuntimeError("Manifest validation failed")
RuntimeError: Manifest validation failed
```

Environment specifics:
OS version: 	Linux CentOS 7.6 3.10.0-957.10.1.el7.x86_64
Medusa version: cassandra-medusa (0.7.1)
Cassandra:	3.11.6
Cassandra nodes:12

AWS regions:    1
AWS AZ:         3
EC2 type:       i3.2xlarge

medusa.ini:

```
[cassandra]
stop_cmd = nodetool stopdaemon
start_cmd = systemctl start cassandra
config_file = /cassandra/conf/cassandra.yaml
cql_username = cassandra
cql_password = xxxxxxxxx
resolve_ip_addresses = True

[storage]
storage_provider = s3_eu_west

bucket_name = cassandra-medusa-backups-xxxxx
max_backup_age = 14
max_backup_count = 100
transfer_max_bandwidth = 128MB/s
concurrent_transfers = 4
multi_part_upload_threshold = 104857600

[monitoring]
[checks]
[logging]
enabled = 1
file = /cassandra/logs/medusa/medusa.log
level = INFO
format = [%(asctime)s] %(levelname)s: %(message)s
```

Last full backup summary:

```
- Started: 2021-01-31 06:15:05, Finished: 2021-01-31 07:32:40
- 12 nodes completed, 0 nodes incomplete, 0 nodes missing
- 355720 files, 8.07 TB
```

Four (4) diffs fail verification:
differential20210202-1215  FAILED verification - 270 tables with mismatch
differential20210202-1815  FAILED verification - 271 tables with mismatch
differential20210203-0015  FAILED verification - 270 tables with mismatch
differential20210203-0615  FAILED verification - 28 tables with mismatch

To be clear - the diffs backed up with out issue - summary from successful backup "differential20210202-1215":

```
[2021-02-02 12:45:29,831] INFO: Updating backup index
[2021-02-02 12:45:31,328] INFO: Backup done
[2021-02-02 12:45:31,328] INFO: - Started: 2021-02-02 12:15:02
                        - Started extracting data: 2021-02-02 12:15:06
                        - Finished: 2021-02-02 12:45:31
[2021-02-02 12:45:31,329] INFO: - Real duration: 0:30:25.243425 (excludes time waiting for other nodes)
[2021-02-02 12:45:31,371] INFO: - 31150 files, 721.48 GB
[2021-02-02 12:45:31,371] INFO: - 434 files copied from host
[2021-02-02 12:45:31,371] INFO: - 30716 copied from previous backup
```

But - when running "medusa verify --backup-name differential20210202-1215" - we get the size diffs and hash mismatch for 270 md-xxxx-big-Summary.db files (the 270 is from just this one differential).

Am not able to reproduce on demand.

Thanks for any insight that can be provided.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-240) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-240

**Comment by rzvoncek** [comment]
Hi @pzoblisein ! I know it's been too long, but better late than never. Have you ever managed to solve this? Or is there something else you're still struggling with?

But, Medusa has changed a lot since v0.7, so these issues might have been solved.
