### ISSUE TITLE
No such file or directory: 'nodetool'

### ISSUE THREAD

**Issue by akap97** [thelastpickle/cassandra-medusa#296]
when i run:
$  medusa backup --backup-name=<backup_name>
I get:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/medusa/backup_node.py", line 204, in main
    num_files, node_backup_cache = do_backup(
  File "/usr/local/lib/python3.8/dist-packages/medusa/backup_node.py", line 252, in do_backup
    with cassandra.create_snapshot(backup_name) as snapshot:
  File "/usr/local/lib/python3.8/dist-packages/medusa/cassandra_utils.py", line 442, in create_snapshot
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, universal_newlines=True)
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 326, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 305, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 808, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 1793, in _execute_child
    raise child_exception
FileNotFoundError: [Errno 2] No such file or directory: 'nodetool'

I have standalone cassandra installation so my nodetool executable path is:
~/apache-cassandra-3.11.10/bin/nodetool

**Comment by akap97** [comment]
exporting nodetool path solved the issue
