### ISSUE TITLE
Error during "list-backups" for S3

### ISSUE THREAD

**Issue by 319-dk** [thelastpickle/cassandra-medusa#307]
An error occurs when using "medusa list-backups" command.
I have tried installation from both APT and PIP.

No errors when running backup/restore-node commands.

### Entries from logfile: 
[2021-03-15 11:09:49,599] DEBUG: Loading storage_provider: s3_rgw
[2021-03-15 11:09:49,643] DEBUG: [Storage] Listing objects in index/backup_index

### Error when executing the "medusa list-backups" command:
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/medusa/medusacli.py", line 168, in list_backups
    medusa.listing.list_backups(medusaconfig, show_all)
  File "/usr/local/lib/python3.6/dist-packages/medusa/listing.py", line 41, in list_backups
    cluster_backups = get_backups(config, show_all)
  File "/usr/local/lib/python3.6/dist-packages/medusa/listing.py", line 29, in get_backups
    key=lambda b: b.started
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 346, in list_cluster_backups
    key=lambda b: (b.name, b.started)
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 182, in list_node_backups
    blobs_by_backup = self.group_backup_index_by_backup_and_node(backup_index_blobs)
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 290, in group_backup_index_by_backup_and_node
    key=name_and_fqdn
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 279, in name_and_fqdn
    return get_backup_name(blob), Storage.get_fqdn_from_any_index_blob(blob)
  File "/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py", line 311, in get_fqdn_from_any_index_blob
    assert match is not None, 'Encountered malformed index blob name {}'.format(blob_name)
AssertionError: Encountered malformed index blob name index/backup_index/

**Comment by 319-dk** [comment]
Working fine when using local storage btw.

**Comment by 319-dk** [comment]
Apparently blob_name in get_fqdn_from_any_index_blob contains an invalid path within the first two iterations, that can not be passed by the regex below.

INDEX_BLOB_NAME_PATTERN = re.compile('.*(tokenmap|schema|manifest|differential|incremental)_(.*)$')
INDEX_BLOB_WITH_TIMESTAMP_PATTERN = re.compile('.*(started|finished)_(.*)_([0-9]+).timestamp$')

/usr/local/lib/python3.6/dist-packages/medusa/storage/__init__.py



**blob_name:**
index/backup_index/
index/backup_index/backup01/
index/backup_index/backup01/differential_test.test.domain.dk
index/backup_index/backup01/finished_test.test.domain.dk_1619079517.timestamp
index/backup_index/backup01/manifest_test.test.domain.dk.json
index/backup_index/backup01/schema_test.test.domain.dk.cql
index/backup_index/backup01/started_test.test.domain.dk_1619079440.timestamp
index/backup_index/backup01/tokenmap_test.test.domain.dk.json
