### ISSUE TITLE
 Provider s3_compatible does not exist in libcloud

### ISSUE THREAD

**Issue by Alizarddrazila** [thelastpickle/cassandra-medusa#335]
Hello. I am using minio as a backup storage. When I do a backup, it fails. When checking the repository, there are minio files in it.

```
[root@test-cassandra1 ~]$ medusa backup --backup-name 123456 --mode full
[2021-04-20 08:42:56,624] INFO: Monitoring provider is noop
[2021-04-20 08:42:56,958] WARNING: is ccm : 0
[2021-04-20 08:42:56,984] INFO: Saving tokenmap and schema
[2021-04-20 08:42:57,607] INFO: Node test-cassandra1.somehost.com does not have latest backup
[2021-04-20 08:42:57,607] INFO: Starting backup
[2021-04-20 08:42:57,607] INFO: Creating snapshot
[2021-04-20 08:42:59,169] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-TOC.txt (92.000B)
[2021-04-20 08:42:59,227] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Summary.db (101.000B)
[2021-04-20 08:42:59,244] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Index.db (78.000B)
[2021-04-20 08:42:59,260] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Statistics.db (5.112KiB)
[2021-04-20 08:42:59,277] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Data.db (429.000B)
[2021-04-20 08:42:59,293] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Filter.db (24.000B)
[2021-04-20 08:42:59,310] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-Digest.crc32 (10.000B)
[2021-04-20 08:42:59,325] INFO: Uploading /var/lib/cassandra/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/snapshots/medusa-123456/md-54-big-CompressionInfo.db (51.000B)
[2021-04-20 08:42:59,343] INFO: Uploading /var/lib/cassandra/data/system/local-7ad54392bcdd35a684174e047860b377/snapshots/medusa-123456/md-256-big-TOC.txt (92.000B)
...............
[2021-04-20 08:43:14,415] ERROR: This error happened during the backup: Provider s3_compatible does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 211, in main
    cassandra, node_backup, storage, differential_mode, enable_md5, config, backup_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 261, in do_backup
    num_files = backup_snapshots(storage, manifest, node_backup, node_backup_cache, snapshot)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 347, in backup_snapshots
    raise e
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_base_storage.py", line 102, in upload_blobs
    multi_part_upload_threshold=int(self.config.multi_part_upload_threshold),
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 83, in <lambda>
    storage, connection, src_file, dest, bucket, multi_part_upload_threshold
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 116, in __upload_file
    obj = _upload_multi_part(storage, connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 135, in _upload_multi_part
    objects = awscli.cp_upload(srcs=[src], bucket_name=bucket.name, dest=object_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 88, in cp_upload
    cmd = self._create_s3_cmd()
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 114, in _create_s3_cmd
    cmd.extend(["--region", get_driver(self._config.storage_provider).region_name])
  File "/usr/local/lib/python3.6/site-packages/libcloud/storage/providers.py", line 108, in get_driver
    deprecated_constants=deprecated_constants)
  File "/usr/local/lib/python3.6/site-packages/libcloud/common/providers.py", line 82, in get_driver
    raise AttributeError('Provider %s does not exist' % (provider))
AttributeError: Provider s3_compatible does not exist
```

Perhaps my environment is somehow incorrectly configured?

Thanks.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-198) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-198

**Comment by adejanovski** [comment]
Right, I see where the problem is.
I'll push a fix shortly and issue a release.

**Comment by Alizarddrazila** [comment]
It's work. Thanks
