### ISSUE TITLE
Incomplete node backups and problem with backup-cluster

### ISSUE THREAD

**Issue by v3n1kk** [thelastpickle/cassandra-medusa#339]
Hello there!
I'm trying to backup nodes of my test cluster to s3 minio. I have 2 nodes test cluster. I'm executing a command on both nodes:
```
medusa backup --mode=full --backup-name=test1
....
[2021-04-22 11:18:54,460] INFO: Uploading /var/lib/cassandra/data/system/size_estimates-618f817b005f3678b8a453f3930b8e86/snapshots/medusa-test1/na-2-big-Data.db (5.276KiB)
[2021-04-22 11:18:56,291] INFO: Updating backup index
[2021-04-22 11:18:56,404] INFO: Backup done
[2021-04-22 11:18:56,405] INFO: - Started: 2021-04-22 11:18:48
                        - Started extracting data: 2021-04-22 11:18:49
                        - Finished: 2021-04-22 11:18:56
[2021-04-22 11:18:56,405] INFO: - Real duration: 0:00:07.143530 (excludes time waiting for other nodes)
[2021-04-22 11:18:56,406] INFO: - 312 files, 260.75 KB
[2021-04-22 11:18:56,406] INFO: - 312 files copied from host
[2021-04-22 11:18:56,406] INFO: - 0 copied from previous backup (2021042211)

```
It's looks like successful, but it's not
Then I see that this backups incompleted:

```
medusa status --backup-name=test1
test1 [Incomplete!]
- Started: 2021-04-22 11:18:49, Finished: never
- 2 nodes completed, 0 nodes incomplete, 2 nodes missing
- Missing nodes:
    192.168.56.134
    192.168.56.133
- 608 files, 511.90 KB
```

What's I'm doing wrong?

Also, I'm making backup-cluster and I have some problems:

```
medusa backup-cluster --backup-name=test
[2021-04-22 11:27:07,281] INFO: Monitoring provider is noop
[2021-04-22 11:27:07,932] INFO: Starting backup test
[2021-04-22 11:27:07,953] WARNING: is ccm : 0
[2021-04-22 11:27:08,042] ERROR: This error happened during the cluster backup: ('Unable to connect to any servers', {'127.0.1.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.1.1', 9042)]. Last error: Connection refused")})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/medusa/backup_cluster.py", line 61, in orchestrate
    backup.execute()
  File "/usr/local/lib/python3.8/dist-packages/medusa/backup_cluster.py", line 129, in execute
    with session_provider.new_session() as session:
  File "/usr/local/lib/python3.8/dist-packages/medusa/cassandra_utils.py", line 110, in new_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1667, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1703, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1690, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3488, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3533, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.1.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.1.1', 9042)]. Last error: Connection refused")})
[2021-04-22 11:27:08,047] ERROR: Something went wrong! Attempting to clean snapshots and exit.
[2021-04-22 11:27:08,047] INFO: Executing "nodetool clearsnapshot -t medusa-test" on following nodes {} with a parallelism/pool size of 1
[2021-04-22 11:27:08,048] INFO: Job executing "nodetool clearsnapshot -t medusa-test" ran and finished Successfully on all nodes.
[2021-04-22 11:27:08,048] INFO: All nodes successfully cleared their snapshot.
```

How I can change this parameter value 127.0.1.1 without changing rpc_address?
My cassandra.yaml involve these parameters:
```
seed_provider:
    # Addresses of hosts that are deemed contact points.
    # Cassandra nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "192.168.56.133:7000,192.168.56.134:7000"
...
listen_address: 192.168.56.134
...
rpc_address:

```

Another parameters are defaults and didn't change

Please, help me, I need to introduce backups to prod env, but I can't tested it completely
Thanks in advance!

**Comment by v3n1kk** [comment]
I figured it out. 
I had to add information about hosts to /etc/hosts. And this problem is gone.
