### ISSUE TITLE
ObjectHashMismatchError when uploading backup to S3 Minio

### ISSUE THREAD

**Issue by v3n1kk** [thelastpickle/cassandra-medusa#341]
Hi there!
I have some problems with uploading backup to S3 Minio.

```
medusa backup --backup-name=test_cassandra-2021-04-27 --mode=full
[2021-04-27 09:20:20,776] INFO: Monitoring provider is noop
[2021-04-27 09:20:21,161] WARNING: is ccm : 0
[2021-04-27 09:20:21,262] INFO: Saving tokenmap and schema
[2021-04-27 09:20:21,750] INFO: Node testnode1.unix.local does not have latest backup
[2021-04-27 09:20:21,751] INFO: Starting backup
[2021-04-27 09:20:21,751] INFO: Creating snapshot
[2021-04-27 09:20:24,383] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-TOC.txt (92.000B)
[2021-04-27 09:24:44,810] ERROR: This error happened during the backup: <ObjectHashMismatchError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faa61219fd0>, value=MD5 hash efcbe5b62bba3e537bc827136f8a091b-1 checksum does not match 61bffd3142add6ac2429794cfe837ffa, object = testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-TOC.txt>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_base_storage.py", line 96, in upload_blobs
    return medusa.storage.s3_compat_storage.concurrent.upload_blobs(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 82, in <lambda>
    lambda storage, connection, src_file: __upload_file(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 119, in __upload_file
    obj = _upload_single_part(connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 126, in _upload_single_part
    obj = connection.upload_object(
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/drivers/s3.py", line 545, in upload_object
    return self._put_object(container=container, object_name=object_name,
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/drivers/s3.py", line 922, in _put_object
    raise ObjectHashMismatchError(
libcloud.storage.types.ObjectHashMismatchError: <ObjectHashMismatchError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faa61219fd0>, value=MD5 hash efcbe5b62bba3e537bc827136f8a091b-1 checksum does not match 61bffd3142add6ac2429794cfe837ffa, object = testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-TOC.txt>
[2021-04-27 09:24:47,651] ERROR: This error happened during the backup: <ObjectHashMismatchError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faa61219fd0>, value=MD5 hash efcbe5b62bba3e537bc827136f8a091b-1 checksum does not match 61bffd3142add6ac2429794cfe837ffa, object = u236i43vc-cas01.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-TOC.txt>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 210, in main
    num_files, node_backup_cache = do_backup(
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 261, in do_backup
    num_files = backup_snapshots(storage, manifest, node_backup, node_backup_cache, snapshot)
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 347, in backup_snapshots
    raise e
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_base_storage.py", line 96, in upload_blobs
    return medusa.storage.s3_compat_storage.concurrent.upload_blobs(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 82, in <lambda>
    lambda storage, connection, src_file: __upload_file(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 119, in __upload_file
    obj = _upload_single_part(connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 126, in _upload_single_part
    obj = connection.upload_object(
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/drivers/s3.py", line 545, in upload_object
    return self._put_object(container=container, object_name=object_name,
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/drivers/s3.py", line 922, in _put_object
    raise ObjectHashMismatchError(
libcloud.storage.types.ObjectHashMismatchError: <ObjectHashMismatchError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7faa61219fd0>, value=MD5 hash efcbe5b62bba3e537bc827136f8a091b-1 checksum does not match 61bffd3142add6ac2429794cfe837ffa, object = testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-TOC.txt>
```

I tried changing `multipart_chunksize` in `/usr/local/lib/python3.8/site-packages/medusa/storage/abstract_storage.py`
 according to the issue here https://github.com/thelastpickle/cassandra-medusa/issues/100
It doesn't work. The errors the same.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-195) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-195

**Comment by adejanovski** [comment]
I'm not sure what's going on here as a `efcbe5b62bba3e537bc827136f8a091b-1` checksum is a multipart one although you're uploading a very small file, which is uploaded as single part. Libcloud seems confused then that you get a mutlipart hash from Minio...

Could you try setting the `multi_part_upload_threshold` to 0 in `medusa.ini` rather than tuning the chunk size and see if the backup passes correctly? 
Do you have any specific setting in your Minio cluster that could explain why single part uploads generate multi part hashes?

**Comment by v3n1kk** [comment]
I set up `multi_part_upload_threshold` to 0 and got a error AttributeError: Provider s3_compatible does not exist:

```
medusa -v backup --backup-name=test_cassandra-2021-04-27 --mode=full
[2021-04-27 10:20:17,252] DEBUG: Loading configuration from /etc/medusa/medusa.ini
[2021-04-27 10:20:17,253] INFO: Monitoring provider is noop
[2021-04-27 10:20:17,253] DEBUG: Loading storage_provider: s3_compatible
[2021-04-27 10:20:17,254] DEBUG: Reading credentials from /etc/medusa/credentials
[2021-04-27 10:20:17,611] DEBUG: This server has systemd: True
[2021-04-27 10:20:17,611] WARNING: is ccm : 0
[2021-04-27 10:20:17,671] DEBUG: Blob testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql was not found in cache.
[2021-04-27 10:20:17,672] DEBUG: [Storage] Getting object testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql
[2021-04-27 10:20:17,683] DEBUG: Process psutil.Process(pid=19848, name='medusa', status='running', started='10:20:16') was set to use only idle IO and CPU resources
[2021-04-27 10:20:17,683] INFO: Saving tokenmap and schema
[2021-04-27 10:20:17,885] DEBUG: Checking datacenter...
[2021-04-27 10:20:17,897] DEBUG: Resolved 10.79.xxx.xxx to 10.79.xxx.xxx
[2021-04-27 10:20:17,897] DEBUG: Checking host 10.79.xxx.xxx against 10.79.xxx.xxx/10.79.xxx.xxx
[2021-04-27 10:20:17,902] DEBUG: Resolved 10.79.xxx.xxx to 10.79.xxx.xxx
[2021-04-27 10:20:17,910] DEBUG: Resolved 10.79.xxx.xxx to 10.79.xxx.xxx
[2021-04-27 10:20:17,917] DEBUG: Resolved 10.79.xxx.xxx to 10.79.xxx.xxx
[2021-04-27 10:20:18,010] DEBUG: Blob testnode1.unix.local/test_cassandra-2021-04-27/meta/tokenmap.json was not found in cache.
[2021-04-27 10:20:18,011] DEBUG: [Storage] Getting object testnode1.unix.local/test_cassandra-2021-04-27/meta/tokenmap.json
[2021-04-27 10:20:18,020] DEBUG: [Storage] Reading blob testnode1.unix.local/test_cassandra-2021-04-27/meta/tokenmap.json...
[2021-04-27 10:20:18,020] DEBUG: [Storage] Reading blob testnode1.unix.local/test_cassandra-2021-04-27/meta/tokenmap.json...
[2021-04-27 10:20:18,056] DEBUG: [Storage] Getting object testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql
[2021-04-27 10:20:18,066] DEBUG: [Storage] Reading blob testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql...
[2021-04-27 10:20:18,067] DEBUG: [Storage] Reading blob testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql...
[2021-04-27 10:20:18,119] DEBUG: Blob testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql was not found in cache.
[2021-04-27 10:20:18,119] DEBUG: [Storage] Getting object testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql
[2021-04-27 10:20:18,149] DEBUG: Blob testnode1.unix.local/test_cassandra-2021-04-27/meta/schema.cql last modification time is Tue, 27 Apr 2021 10:20:17 GMT
[2021-04-27 10:20:18,168] DEBUG: [Storage] Getting object index/latest_backup/testnode1.unix.local/backup_name.txt
[2021-04-27 10:20:18,176] DEBUG: [Storage] Getting object testnode1.unix.local/None/meta/differential
[2021-04-27 10:20:18,183] DEBUG: [Storage] Getting object testnode1.unix.local/None/meta/incremental
[2021-04-27 10:20:18,190] INFO: Node testnode1.unix.local does not have latest backup
[2021-04-27 10:20:18,191] INFO: Starting backup
[2021-04-27 10:20:18,191] INFO: Creating snapshot
[2021-04-27 10:20:18,192] DEBUG: Executing: nodetool snapshot -t medusa-test_cassandra-2021-04-27
[2021-04-27 10:20:20,727] DEBUG: Backing up <medusa.cassandra_utils.SnapshotPath object at 0x7f322217df40>
[2021-04-27 10:20:20,728] DEBUG: destination path: testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c
[2021-04-27 10:20:20,728] DEBUG: Reading credentials from /etc/medusa/credentials
[2021-04-27 10:20:20,729] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-TOC.txt (92.000B)
[2021-04-27 10:20:20,729] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-TOC.txt as multi part
[2021-04-27 10:20:20,730] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-Summary.db (62.000B)
[2021-04-27 10:20:20,730] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-Summary.db as multi part
[2021-04-27 10:20:20,730] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-Data.db (358.000B)
[2021-04-27 10:20:20,731] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-Data.db as multi part
[2021-04-27 10:20:20,731] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-Filter.db (16.000B)
[2021-04-27 10:20:20,731] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-Filter.db as multi part
[2021-04-27 10:20:20,731] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-Statistics.db (4.729KiB)
[2021-04-27 10:20:20,731] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-Statistics.db as multi part
[2021-04-27 10:20:20,732] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-CompressionInfo.db (51.000B)
[2021-04-27 10:20:20,732] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-CompressionInfo.db as multi part
[2021-04-27 10:20:20,732] INFO: Uploading /storage/cassandra/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/snapshots/medusa-test_cassandra-2021-04-27/md-5-big-Digest.crc32 (10.000B)
[2021-04-27 10:20:20,732] DEBUG: Uploading testnode1.unix.local/test_cassandra-2021-04-27/data/system_auth/role_permissions-3afbe79f219431a7add7f5ab90d8ec9c/md-5-big-Digest.crc32 as multi part
[2021-04-27 10:20:20,733] ERROR: This error happened during the backup: Provider s3_compatible does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_base_storage.py", line 96, in upload_blobs
    return medusa.storage.s3_compat_storage.concurrent.upload_blobs(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 82, in <lambda>
    lambda storage, connection, src_file: __upload_file(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 116, in __upload_file
    obj = _upload_multi_part(storage, connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 135, in _upload_multi_part
    objects = awscli.cp_upload(srcs=[src], bucket_name=bucket.name, dest=object_name)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 88, in cp_upload
    cmd = self._create_s3_cmd()
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 114, in _create_s3_cmd
    cmd.extend(["--region", get_driver(self._config.storage_provider).region_name])
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/providers.py", line 107, in get_driver
    return _get_provider_driver(drivers=DRIVERS, provider=provider,
  File "/usr/local/lib/python3.8/site-packages/libcloud/common/providers.py", line 82, in get_driver
    raise AttributeError('Provider %s does not exist' % (provider))
AttributeError: Provider s3_compatible does not exist
[2021-04-27 10:20:20,760] DEBUG: Cleaning up snapshot
[2021-04-27 10:20:20,760] DEBUG: Executing: nodetool clearsnapshot -t medusa-test_cassandra-2021-04-27
[2021-04-27 10:20:23,571] DEBUG: nodetool output: Requested clearing snapshot(s) for [all keyspaces] with snapshot name [medusa-test_cassandra-2021-04-27]

[2021-04-27 10:20:23,571] ERROR: This error happened during the backup: Provider s3_compatible does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 210, in main
    num_files, node_backup_cache = do_backup(
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 261, in do_backup
    num_files = backup_snapshots(storage, manifest, node_backup, node_backup_cache, snapshot)
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 347, in backup_snapshots
    raise e
  File "/usr/local/lib/python3.8/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
    manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_base_storage.py", line 96, in upload_blobs
    return medusa.storage.s3_compat_storage.concurrent.upload_blobs(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 87, in upload_blobs
    return job.execute(list(src))
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 51, in execute
    return list(executor.map(self.with_storage, iterables))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 60, in with_storage
    return self.func(self.storage, connection, iterable)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 82, in <lambda>
    lambda storage, connection, src_file: __upload_file(
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 116, in __upload_file
    obj = _upload_multi_part(storage, connection, src, bucket, full_object_name)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/concurrent.py", line 135, in _upload_multi_part
    objects = awscli.cp_upload(srcs=[src], bucket_name=bucket.name, dest=object_name)
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 88, in cp_upload
    cmd = self._create_s3_cmd()
  File "/usr/local/lib/python3.8/site-packages/medusa/storage/s3_compat_storage/awscli.py", line 114, in _create_s3_cmd
    cmd.extend(["--region", get_driver(self._config.storage_provider).region_name])
  File "/usr/local/lib/python3.8/site-packages/libcloud/storage/providers.py", line 107, in get_driver
    return _get_provider_driver(drivers=DRIVERS, provider=provider,
  File "/usr/local/lib/python3.8/site-packages/libcloud/common/providers.py", line 82, in get_driver
    raise AttributeError('Provider %s does not exist' % (provider))
AttributeError: Provider s3_compatible does not exist

```

Minio server running with default settings from the image in docker. It's looking as working properly and I can upload there are other backups, like Postgres through WAL-G, for example.

**Comment by adejanovski** [comment]
yes, that's an identified and corrected bug actually. I've just triggered the release of 0.10.1 which will fix this issue.
I'm not suggesting specifically that there's a problem in your Minio install, just that there could be some settings that are not well handled by Libcloud and/or Medusa.

I'll run some tests locally using 0.10.0 to see if I can reproduce this specific problem and will report back.

**Comment by v3n1kk** [comment]
Thank you so much! I'm waiting for the new release and then send your feedback here then

**Comment by adejanovski** [comment]
Medusa 0.10.1 was released and should fix your second problem : `This error happened during the backup: Provider s3_compatible does not exist` 

The other one is still to be investigated properly.
You should now be able to perform backups that will only use the awscli by setting the `multi_part_upload_threshold` to 0.

**Comment by v3n1kk** [comment]
So, I tested a lot. 
Thanks for your answer, medusa 0.10.1 works correctly with the parameter `multi_part_upload_threshold = 0`
Unfortunately, in this case, backup taking a too long time with it. I was trying to find a problem in S3 minio, but can't find anything. 

I resolve my problem when just set up another server S3 Minio with similar settings and the problem is gone!
I will continue trying to find out what incorrect with my first S3. If I find anything - I'll write here below
