### ISSUE TITLE
Backup to s3 us-east-1

### ISSUE THREAD

**Issue by optplx** [thelastpickle/cassandra-medusa#372]
Hello, 
according to https://github.com/apache/libcloud/blob/trunk/libcloud/storage/types.py#L53, the storage_provider for the AWS us-east-1 region should be `s3`. However I have an issue when using this value in my config files:

```
 ERROR: This error happened during the cluster backup: Invalid or unsupported region: default
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/medusa/backup_cluster.py", line 50, in orchestrate
storage = Storage(config=config.storage)
File "/usr/local/lib/python3.7/dist-packages/medusa/storage/__init__.py", line 72, in __init__
self.storage_driver = self._connect_storage()
File "/usr/local/lib/python3.7/dist-packages/medusa/storage/__init__.py", line 92, in _connect_storage
s3_storage = S3Storage(self._config)
File "/usr/local/lib/python3.7/dist-packages/medusa/storage/abstract_storage.py", line 39, in __init__
self.driver = self.connect_storage()
File "/usr/local/lib/python3.7/dist-packages/medusa/storage/s3_storage.py", line 102, in connect_storage
aws_access_key_id, aws_secret_access_key, token=aws_security_token, region=region
File "/usr/local/lib/python3.7/dist-packages/libcloud/storage/drivers/s3.py", line 1134, in __init__
raise ValueError('Invalid or unsupported region: %s' % (region))
ValueError: Invalid or unsupported region: default
```
This comes from the region being set here https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/config.py#L111

It looks like this variable was not meant to be used this way, is it the correct way to go for the `us-east-1` region on AWS? Please note that for other regions we do not need this `region` parameter, it is discovered from the `storage_provider` instead

**Comment by optplx** [comment]
Adding some more details after digging, the difference between us-east-1 and the other regions is here https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/s3_storage.py#L99

For us-east-1, we do not override the region and we end up with the one from the config set to `default`.

I will open a PR to discuss the potential solutions here

**Comment by optplx** [comment]
as discussed in the PR, the new way of doing is by configuring as follow:
```
storage_provider = s3
region = <my_region>
```

The form `storage_provider = s3_<region_name>`  is actually the old way
