### ISSUE TITLE
medusa: backup over SSL

### ISSUE THREAD

**Issue by rss04** [thelastpickle/cassandra-medusa#381]
I am trying to backup cassandra node over SSL using self-signed certs . 
I am able to communicate with the cassandra cluster over SSL using nodetool, cqlsh and reaper. 
But, I am seeing the below error using Medusa . 
Can you please confirm if Medusa is working over SSL ?
Any help or advise or tips are really helpful . Thanks in advance.

Error:
$ medusa backup --backup-name=kitchen-test-medusa-bkp --mode=full
[2021-07-01 08:42:50,943] INFO: Monitoring provider is noop
[2021-07-01 08:42:51,783] WARNING: is ccm : 0
[2021-07-01 08:42:51,867] WARNING: ssl_storage_port is deprecated as of Apache Cassandra 4.x
[2021-07-01 08:42:51,894] INFO: Saving tokenmap and schema
[2021-07-01 08:51:12,489] ERROR: This error happened during the backup: ('Unable to connect to any servers', {'172.18.76.123:9042': PermissionError(1, "Tried connecting to [('172.18.76.123', 9042)]. Last error:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)")})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 188, in main
    schema, tokenmap = get_schema_and_tokenmap(cassandra)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 235, in get_schema_and_tokenmap
    with cassandra.new_session() as cql_session:
  File "/usr/local/lib/python3.7/site-packages/medusa/cassandra_utils.py", line 361, in new_session
    return self._cql_session_provider.new_session()
  File "/usr/local/lib/python3.7/site-packages/medusa/cassandra_utils.py", line 113, in new_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1667, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1703, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1690, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3488, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3533, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'172.18.76.123:9042': PermissionError(1, "Tried connecting to [('172.18.76.123', 9042)]. Last error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)")})
sh-4.2$`

medusa.ini config:
`
[cassandra]
stop_cmd = /etc/init.d/cassandra stop
start_cmd = /etc/init.d/cassandra start
config_file = /etc/cassandra/conf/cassandra.yaml
cql_username = cassandra
cql_password = cassandra
nodetool_username =  cassandra
nodetool_password =  cassandra
;nodetool_password_file_path = <path to nodetool password file>
nodetool_host = 10.0.0.10.1
;nodetool_port = <port number to use for nodetool>
certfile= /etc/cassandra/conf/certs/rootCA.pem
;<Client SSL: path to rootCa certificate>
usercert= /etc/cassandra/conf/certs/public.crt
;<Client SSL: path to user certificate>
userkey= /etc/cassandra/sslsetup/certs/priv.key
;<Client SSL: path to user key>
sstableloader_ts = /etc/cassandra/conf/certs/cassandra.truststore
;<Client SSL: full path to truststore>
sstableloader_tspw = cassandra
;<Client SSL: password of the truststore>
sstableloader_ks = /etc/cassandra/conf/certs/cassandra.keystore
;<Client SSL: full path to keystore>
sstableloader_kspw = cassandra
;<Client SSL: password of the keystore>

; Enable this to add the '--ssl' parameter to nodetool. The nodetool-ssl.properties is expected to be in the normal location
nodetool_ssl = true`

**Comment by rss04** [comment]
Its working my bad...will document the process

**Comment by akaeme** [comment]
+1, I'm having the same issue
