### ISSUE TITLE
delete-backup fails if an incomplete backup is present

### ISSUE THREAD

**Issue by spintower** [thelastpickle/cassandra-medusa#392]
Backup deletion fails if the cluster has an incomplete backup. If one of the hosts does not create a backup for some reason, medusa fails to read that backup's manifest and exits.

Backup `backup-20210804-1330` for host `host001` is missing:

```
host001:~$ /opt/medusa/bin/medusa status --backup-name backup-20210804-1330
backup-20210804-1330 [Incomplete!]
- Started: 2021-08-04 13:30:22, Finished: never
- 2 nodes completed, 1 nodes incomplete, 0 nodes missing
- Incomplete nodes:
    host001.domain.net
```

Now deleting **any** backup from the cluster fails when medusa cannot download the manifest for the missing backup:

```
[2021-08-19 21:18:49,414] INFO: Cleaning up orphaned files for host001.domain.net...

...

[2021-08-19 21:20:48,432] DEBUG: https://cassandrabackup.blob.core.windows.net:443 "HEAD /cassandra-backup/host001.domain.net/backup-20210804-1330/meta/manifest.json HTTP/1.1" 404 0
[2021-08-19 21:20:50,331] ERROR: This error happened during the delete of backup "backup-20210531-0730": the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/opt/medusa/lib/python3.8/site-packages/medusa/purge.py", line 212, in delete_backup
    purge_backups(storage, backups_to_purge, config.storage.backup_grace_period_in_days)
  File "/opt/medusa/lib/python3.8/site-packages/medusa/purge.py", line 103, in purge_backups
    (cleaned_objects_count, cleaned_objects_size) = cleanup_obsolete_files(storage,
  File "/opt/medusa/lib/python3.8/site-packages/medusa/purge.py", line 139, in cleanup_obsolete_files
    paths_in_manifest = get_file_paths_from_manifests_for_differential_backups(backups)
  File "/opt/medusa/lib/python3.8/site-packages/medusa/purge.py", line 178, in get_file_paths_from_manifests_for_differential_backups
    manifests = list(map(lambda backup: json.loads(backup.manifest), differential_backups))
  File "/opt/medusa/lib/python3.8/site-packages/medusa/purge.py", line 178, in <lambda>
    manifests = list(map(lambda backup: json.loads(backup.manifest), differential_backups))
  File "/opt/medusa/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

Outcome: the backup that needed to be deleted is deleted, but the an errors is deplayed and orphan files are not cleaned up.

**Comment by atallahade** [comment]
The same issue happened to me. I had to run `medusa purge` to cleanly remove the incomplete backups and unblock the removal of other backups. It would only work if the incomplete backups are old enough though.
