### ISSUE TITLE
Error medusa restore-cluster use "use-sstableloader"

### ISSUE THREAD

**Issue by relajado** [thelastpickle/cassandra-medusa#425]
Hi!
after creating a backup, it is not possible to restore with the use-sstableloader parameter

cassandra #3.11.9
cassandra-medusa[S3] #0.11.3

```
root@******:/# medusa backup-cluster  --backup-name test3 --mode full
root@******:/# medusa restore-cluster --backup-name test3 --use-sstableloader

[2021-11-16 11:20:50,682] INFO: Monitoring provider is noop
[2021-11-16 11:20:50,683] WARNING: Seed target was not provided, using the local hostname: ******
[2021-11-16 11:20:51,117] WARNING: is ccm : 0
[2021-11-16 11:20:51,173] INFO: Ensuring the backup is found and is complete
[2021-11-16 11:20:51,489] INFO: Restoring on the same cluster that was the backup was taken on (in place fashion)
[2021-11-16 11:20:51,493] INFO: Starting cluster restore...
[2021-11-16 11:20:51,494] INFO: Working directory for this execution: /tmp/medusa-job-e70e5ea7-75e0-457e-ae55-cfd719d5ec43
[2021-11-16 11:20:51,494] INFO: About to restore on ****** using {'source': ['******'], 'seed': False} as backup source
[2021-11-16 11:20:51,494] INFO: About to restore on ****** using {'source': ['******'], 'seed': False} as backup source
[2021-11-16 11:20:51,494] INFO: About to restore on ****** using {'source': ['******'], 'seed': False} as backup source
[2021-11-16 11:20:51,494] INFO: This will delete all data on the target nodes and replace it with backup test3.
Are you sure you want to proceed? (Y/n)Are you sure you want to proceed? (Y/n)Y
[2021-11-16 11:20:53,334] INFO: target seeds : []
[2021-11-16 11:20:53,335] INFO: target hosts : ['******', '******', '******']
[2021-11-16 11:20:53,335] INFO: Restoring schema on the target cluster
[2021-11-16 11:20:53,675] INFO: (Re)creating schema for keyspace history
[2021-11-16 11:21:11,178] ERROR: This error happened during the cluster restore: Error from server: code=2200 [Invalid query] message="unconfigured table message"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 69, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 150, in execute
    self._restore_data()
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 320, in _restore_data
    self._restore_schema()
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 387, in _restore_schema
    self._create_or_recreate_schema_objects(session, keyspace, schema[keyspace])
  File "/usr/local/lib/python3.8/dist-packages/medusa/restore_cluster.py", line 413, in _create_or_recreate_schema_objects
    session.execute(index[1])
  File "/usr/local/lib/python3.8/dist-packages/medusa/cassandra_utils.py", line 205, in execute
    return self.session.execute(query)
  File "cassandra/cluster.py", line 2618, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4894, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table message"
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1396) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1396
┆priority: Medium

**Comment by adejanovski** [comment]
Using the sstableloader is error prone indeed. Could you share the schema.cql file from this backup so we can understand what's going on?

**Comment by jsanda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/thelastpickle/cassandra-medusa/425?planning-poker) with ZenHub @adejanovski

**Comment by adejanovski** [comment]
@jsanda, I can't estimate without more information. I've labeled the issue as "stale" so we close it if it stays inactive for the next couple weeks.

**Comment by relajado** [comment]
Hey!
Copy permanently deleted :(

**Comment by adejanovski** [comment]
Thanks for the info @relajado, I'll go ahead and close the ticket.
