### ISSUE TITLE
Medusa don't use no_proxy environment

### ISSUE THREAD

**Issue by Alizarddrazila** [thelastpickle/cassandra-medusa#429]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952028)

On our host we have proxy. And it define in same environment:
http_proxy=http://proxy.our.domen:3128/
https_proxy=http://proxy.our.domen:3128/
no_proxy=.our.domen

When we start backup, it end with error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 174, in main
    storage = Storage(config=config.storage)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/__init__.py", line 72, in __init__
    self.storage_driver = self._connect_storage()
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/__init__.py", line 88, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/usr/local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 357, in get_container
    method='HEAD')
  File "/usr/local/lib/python3.6/site-packages/libcloud/common/base.py", line 623, in request
    headers=headers, stream=stream)
  File "/usr/local/lib/python3.6/site-packages/libcloud/http.py", line 232, in request
    verify=self.verification
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='s3.our.domen', port=443): Max retries exceeded with url: /our-backet (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))
```

As i think it use http(s)_proxy, but doesn't use no_proxy.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1393) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1393
┆priority: Medium

**Comment by rzvoncek** [comment]
Hello, we changed the storage backend implementation. In case this is still relevant, can you please try with medusa 0.19.1, and if you're still having problem, open a new issue? Thanks!
