### ISSUE TITLE
medusa backup results in error - No backup name supplied

### ISSUE THREAD

**Issue by bkrajmalnik1** [thelastpickle/cassandra-medusa#439]
Just installed 0.12.0 in a new VM for testing (previously running 0.8.0)

In 0.8.0, issuing medusa backup auto-generated a backup name in the form yyyymmddhh
In 0.12.0 I am forced to specify a backup name or else a it throws an error.

Stack trace is as follows:

# medusa backup
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/medusa/medusacli.py", line 132, in backup
    BackupMan.register_backup(backup_name, is_async=False)
  File "/usr/local/lib/python3.9/site-packages/medusa/backup_manager.py", line 104, in register_backup
    raise RuntimeError(BackupMan.NO_BACKUP_NAME_ERR_MSG)
RuntimeError: No backup name supplied

**Comment by alokhom** [comment]
maybe bucketName is not provided in your medusa config

**Comment by bkrajmalnik1** [comment]
bucket_name is set.  bucket_name specifies the directory under base_path

The issue is not with the location, but rather the backup file name.

The apparent issue is that it is not auto-generating a backup name if one is not provided.

**Comment by adejanovski** [comment]
We made some change and refactored the backup code. I guess the auto generation part was dropped as part of this.
Definitely something we need to bring back 👍
