### ISSUE TITLE
Medusa currently doesn't support Python3.10 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by andyfoston** [thelastpickle/cassandra-medusa#468]
When attempting to run medusa on Python 3.10 on Ubuntu 22.04, I get the following error:

```bash
$ medusa
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 5, in <module>
    from medusa.medusacli import cli
  File "/usr/local/lib/python3.10/dist-packages/medusa/medusacli.py", line 40, in <module>
    import medusa.backup_cluster
  File "/usr/local/lib/python3.10/dist-packages/medusa/backup_cluster.py", line 24, in <module>
    from medusa.orchestration import Orchestration
  File "/usr/local/lib/python3.10/dist-packages/medusa/orchestration.py", line 18, in <module>
    from pssh.clients.ssh import ParallelSSHClient
  File "/usr/local/lib/python3.10/dist-packages/pssh/clients/__init__.py", line 19, in <module>
    from .native.parallel import ParallelSSHClient
  File "/usr/local/lib/python3.10/dist-packages/pssh/clients/native/__init__.py", line 19, in <module>
    from .parallel import ParallelSSHClient
  File "/usr/local/lib/python3.10/dist-packages/pssh/clients/native/parallel.py", line 20, in <module>
    from .single import SSHClient
  File "/usr/local/lib/python3.10/dist-packages/pssh/clients/native/single.py", line 29, in <module>
    from ssh2.session import Session, LIBSSH2_SESSION_BLOCK_INBOUND, LIBSSH2_SESSION_BLOCK_OUTBOUND
  File "ssh2/session.pyx", line 1, in init ssh2.session
  File "ssh2/channel.pyx", line 1, in init ssh2.channel
  File "ssh2/sftp.pyx", line 1, in init ssh2.sftp
ImportError: /usr/local/lib/python3.10/dist-packages/ssh2/sftp_handle.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

It seems that the `python-ssh2` library added python 3.10 support in their release 0.27.0 https://github.com/ParallelSSH/ssh2-python/releases/tag/0.27.0, and Medusa has their dependency pinned to 0.22.0. Please can this pinning be changed to 0.27.0 to allow Medusa to run on Python 3.10?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1471) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1471
┆priority: Medium

**Comment by andyfoston** [comment]
I created the above PR for this. I didn't add a new suite to the `debian-build` stage for Jammy Jellyfish builds but I can add this though if needed?

**Comment by rzvoncek** [comment]
The related PR seems to be merged long time ago, so I'll go ahead and close this issue.
