### ISSUE TITLE
Attempting to use IAM_Role and medusa

### ISSUE THREAD

**Issue by rchannel** [thelastpickle/cassandra-medusa#47]
Ubuntu 16.04
python3.6

$medusa
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 7, in <module>
    from medusa.medusacli import cli
  File "/usr/local/lib/python3.5/dist-packages/medusa/medusacli.py", line 33, in <module>
    import medusa.backup
  File "/usr/local/lib/python3.5/dist-packages/medusa/backup.py", line 33, in <module>
    from medusa.index import add_backup_start_to_index, add_backup_finish_to_index, set_latest_backup_in_index
  File "/usr/local/lib/python3.5/dist-packages/medusa/index.py", line 21, in <module>
    import medusa.storage
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/__init__.py", line 32, in <module>
    from medusa.storage.google_storage import GoogleStorage
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/google_storage.py", line 26, in <module>
    from medusa.storage.abstract_storage import AbstractStorage
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/abstract_storage.py", line 25, in <module>
    import medusa.storage.concurrent
  File "/usr/local/lib/python3.5/dist-packages/medusa/storage/concurrent.py", line 161
    return f"{size:.{decimal_places}f}{unit}"
                                            ^
SyntaxError: invalid syntax

**Comment by pumpkiny9120** [comment]
Hi @rchannel , this was recently fixed https://github.com/thelastpickle/cassandra-medusa/commit/2632ad36f3df4a775e42343679315763e2ed91f1. It's possible that it's not in the last release.
I updated my Python and it worked.

**Comment by adejanovski** [comment]
Yes, python 3.5 support is only available in `master` and has yet to be released.

**Comment by rchannel** [comment]
I think you both missed the python version I was using.  But as it is ubuntu 16 I will try the master and see if it fixes.
