### ISSUE TITLE
Unable to take cluster backups using medusa

### ISSUE THREAD

**Issue by praveen-rajasekaran** [thelastpickle/cassandra-medusa#480]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952010)

I have a simple 3 node cluster with some sample data. I want to take backup of the cluster and restore it in different cluster.
I can take node backup and restore however cluster level backup never seems to be working. It is throwing the following error.

Cassandra version - 3.10
OS - Amazon linux 2 - centos

[2022-05-20 06:37:20,534] INFO: Creating snapshots on all nodes
[2022-05-20 06:37:20,534] INFO: Executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy snapshot -t medusa-samp" on following nodes ['nodecassandra-2.localdomain', 'nodecassandra-3.localdomain', 'nodecassandra-1.localdomain'] with a parallelism/pool size of 500
[2022-05-20 06:37:21,129] ERROR: Job executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy snapshot -t medusa-samp" ran and finished with errors on following nodes: ['nodecassandra-1.localdomain', 'nodecassandra-2.localdomain', 'nodecassandra-3.localdomain']
[2022-05-20 06:37:21,130] INFO: [nodecassandra-2.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] INFO: nodecassandra-2.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] INFO: [nodecassandra-3.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] INFO: nodecassandra-3.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] INFO: [nodecassandra-1.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] INFO: nodecassandra-1.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:21,130] ERROR: Some nodes failed to create the snapshot.
[2022-05-20 06:37:21,130] ERROR: This error happened during the cluster backup: Some nodes failed to create the snapshot.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/backup_cluster.py", line 64, in orchestrate
    backup.execute(cql_session_provider)
  File "/usr/local/lib/python3.7/site-packages/medusa/backup_cluster.py", line 146, in execute
    self._create_snapshots()
  File "/usr/local/lib/python3.7/site-packages/medusa/backup_cluster.py", line 163, in _create_snapshots
    raise Exception(err_msg)
Exception: Some nodes failed to create the snapshot.
[2022-05-20 06:37:21,131] ERROR: Something went wrong! Attempting to clean snapshots and exit.
[2022-05-20 06:37:21,131] INFO: Executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy clearsnapshot -t medusa-samp" on following nodes ['nodecassandra-2.localdomain', 'nodecassandra-3.localdomain', 'nodecassandra-1.localdomain'] with a parallelism/pool size of 1
[2022-05-20 06:37:22,290] ERROR: Job executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy clearsnapshot -t medusa-samp" ran and finished with errors on following nodes: ['nodecassandra-1.localdomain', 'nodecassandra-2.localdomain', 'nodecassandra-3.localdomain']
[2022-05-20 06:37:22,290] INFO: [nodecassandra-2.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:22,290] INFO: nodecassandra-2.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:22,290] INFO: [nodecassandra-3.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:22,290] INFO: nodecassandra-3.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:22,290] INFO: [nodecassandra-1.localdomain]	[err]	/bin/bash: nodetool: command not found
[2022-05-20 06:37:22,290] INFO: nodecassandra-1.localdomain-stderr: /bin/bash: nodetool: command not found
[2022-05-20 06:37:22,291] ERROR: Some nodes failed to clear the snapshot. Cleaning snapshots manually is recommended

-- I have added path variables for cassandra bin, nodetool
-- added CASSANDRA_HOME, CASSANDRA_CONF in /etc/profile.d/cassandra.sh
-- added ssh details in medusa.ini. Only given cassandra_conf path file, storage details and ssh details in medusa.ini 

Am i missing anything else ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1522) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1522
┆priority: Medium

**Comment by abonacin** [comment]
Hi @praveen-rajasekaran.
Look at these: https://github.com/thelastpickle/cassandra-medusa/issues/318 and https://github.com/thelastpickle/cassandra-medusa/issues/253
It cloud to be related with sudo. The workaround is set nodetool path on /etc/sudoers (using visudo) on secure_path.
Something like this:
Original:
`Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin`
Changed:
`Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/opt/cassandra/bin`

Look:
```
[root@ip-20-0-1-135 ~]# cat /etc/sudoers | grep secure
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
[root@ip-20-0-1-135 ~]# su - cassandra
[cassandra@ip-20-0-1-135 ~]$ nodetool -u cassandra -pw cassandra version
ReleaseVersion: 3.0.16
[cassandra@ip-20-0-1-135 ~]$ sudo nodetool -u cassandra -pw cassandra version
sudo: nodetool: command not found
[cassandra@ip-20-0-1-135 ~]$


[root@ip-20-0-1-135 ~]# cat /etc/sudoers | grep secure
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/opt/cassandra/bin
[root@ip-20-0-1-135 ~]# su - cassandra
[cassandra@ip-20-0-1-135 ~]$ nodetool -u cassandra -pw cassandra version
ReleaseVersion: 3.0.16
[cassandra@ip-20-0-1-135 ~]$ sudo nodetool -u cassandra -pw cassandra version
ReleaseVersion: 3.0.16
[cassandra@ip-20-0-1-135 ~]$
```

**Comment by praveen-rajasekaran** [comment]
Thanks, I was able to take cluster backup successfully after adding nodetool, medusa-wrapper paths in  secure_path /etc/sudoers file.

**Comment by Gustavo-Coutinho** [comment]
this should be a prerequisite listed in the docs, since the cassandra binaries might not be in `/bin/bash` in many cases. 

I had the same issue, and was only able to solve it by adding my cassandra bin diretory to my secure_path. Thanks so much @abonacin 🎉
