### ISSUE TITLE
backup-cluster (after deleting the backup with same name) throws error

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#500]
Hi - In the following scenario, backup-cluster throws an error.

1. Step 1 - take a backup
2. Step 2 - list all backup (verify backup does exists)
3. Step 3 - delete the backup
4. Step 4 - list all backup (verify backup does not exists)
5. Step 5 - take a backup, with same name which was deleted.

Is it a limitation in medusa for now. Can you please check once.

### Execution

**Step 1**
```
[root@node1-dc1 ~]# medusa backup-cluster --backup-name=data1 --mode=full
[2022-07-14 05:22:15,998] INFO: Resolving ip address
[2022-07-14 05:22:15,999] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:22:16,001] INFO: Monitoring provider is noop
[2022-07-14 05:22:16,002] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
[2022-07-14 05:22:16,002] INFO: Starting backup data1
[2022-07-14 05:22:16,036] WARNING: ssl_storage_port is deprecated as of Apache Cassandra 4.x
[2022-07-14 05:22:16,476] INFO: Resolving ip address 111.222.333.4
[2022-07-14 05:22:16,476] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:22:16,478] INFO: Resolving ip address 111.222.333.5
[2022-07-14 05:22:16,479] INFO: ip address to resolve 111.222.333.5
[2022-07-14 05:22:16,479] INFO: Resolving ip address 111.222.333.4
[2022-07-14 05:22:16,479] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:22:16,480] INFO: Resolving ip address 111.222.333.6
[2022-07-14 05:22:16,480] INFO: ip address to resolve 111.222.333.6
[2022-07-14 05:22:16,482] INFO: Creating snapshots on all nodes
[2022-07-14 05:22:16,482] INFO: Executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd snapshot -t medusa-data1" on following nodes ['node2-dc1.domain.com', 'node1-dc1.domain.com', 'node3-dc1.domain.com'] with a parallelism/pool size of 500
[2022-07-14 05:22:19,815] INFO: Job executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd snapshot -t medusa-data1" ran and finished Successfully on all nodes.
[2022-07-14 05:22:19,815] INFO: A snapshot medusa-data1 was created on all nodes.
[2022-07-14 05:22:19,815] INFO: Uploading snapshots from nodes to external storage
[2022-07-14 05:22:19,816] INFO: Executing "mkdir -p /tmp/medusa-job-ec892b9b-f9ed-4b52-9978-62306be4131f; cd /tmp/medusa-job-ec892b9b-f9ed-4b52-9978-62306be4131f && medusa-wrapper sudo medusa  -vvv backup-node --backup-name data1   --mode full" on following nodes ['node2-dc1.domain.com', 'node1-dc1.domain.com', 'node3-dc1.domain.com'] with a parallelism/pool size of 1
[2022-07-14 05:22:45,103] INFO: Job executing "mkdir -p /tmp/medusa-job-ec892b9b-f9ed-4b52-9978-62306be4131f; cd /tmp/medusa-job-ec892b9b-f9ed-4b52-9978-62306be4131f && medusa-wrapper sudo medusa  -vvv backup-node --backup-name data1   --mode full" ran and finished Successfully on all nodes.
[2022-07-14 05:22:45,103] INFO: A new backup data1 was created on all nodes.
[2022-07-14 05:22:45,104] INFO: Backup duration: 29
[2022-07-14 05:22:45,104] INFO: Backup of the cluster done.
```

**Step 2**
```
[root@node1-dc1 ~]# medusa list-backups --show-all
[2022-07-14 05:27:02,779] INFO: Resolving ip address
[2022-07-14 05:27:02,780] INFO: ip address to resolve 111.222.333.4
data1 (started: 2022-07-14 05:22:21, finished: 2022-07-14 05:22:44)
```

**Step 3**
```
[root@node1-dc1 ~]# medusa delete-backup --backup-name=data1 -a
[2022-07-14 05:28:00,026] INFO: Resolving ip address
[2022-07-14 05:28:00,027] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:28:00,032] INFO: Monitoring provider is noop
[2022-07-14 05:28:00,117] INFO: Deleting Backup(s) data1...
[2022-07-14 05:28:00,117] INFO: 3 backups are candidate to be purged
[2022-07-14 05:28:00,117] INFO: Purging backup data1 from node node2-dc1.domain.com...
[2022-07-14 05:28:00,431] INFO: Purging backup data1 from node node1-dc1.domain.com...
[2022-07-14 05:28:00,628] INFO: Purging backup data1 from node node3-dc1.domain.com...
[2022-07-14 05:28:00,826] INFO: Cleaning up orphaned files for node2-dc1.domain.com...
[2022-07-14 05:28:00,827] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
[2022-07-14 05:28:00,827] INFO: Cleaning up orphaned files for node1-dc1.domain.com...
[2022-07-14 05:28:00,828] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
[2022-07-14 05:28:00,828] INFO: Cleaning up orphaned files for node3-dc1.domain.com...
[2022-07-14 05:28:00,829] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
[2022-07-14 05:28:00,830] INFO: Purged 1257 objects with a total size of 2.00 MB
```

**Step 4**
```
[root@node1-dc1 ~]# medusa list-backups --show-all
[2022-07-14 05:28:35,750] INFO: Resolving ip address
[2022-07-14 05:28:35,750] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:28:35,755] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups

```
**Step 5**
```
[root@node1-dc1 ~]# medusa backup-cluster --backup-name=data1 --mode=full
[2022-07-14 05:28:46,908] INFO: Resolving ip address
[2022-07-14 05:28:46,908] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:28:46,912] INFO: Monitoring provider is noop
[2022-07-14 05:28:46,914] INFO: No backups found in index. Consider running "medusa build-index" if you have some backups
[2022-07-14 05:28:46,914] INFO: Starting backup data1
[2022-07-14 05:28:46,948] WARNING: ssl_storage_port is deprecated as of Apache Cassandra 4.x
[2022-07-14 05:28:47,377] INFO: Resolving ip address 111.222.333.4
[2022-07-14 05:28:47,378] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:28:47,379] INFO: Resolving ip address 111.222.333.5
[2022-07-14 05:28:47,380] INFO: ip address to resolve 111.222.333.5
[2022-07-14 05:28:47,380] INFO: Resolving ip address 111.222.333.4
[2022-07-14 05:28:47,380] INFO: ip address to resolve 111.222.333.4
[2022-07-14 05:28:47,381] INFO: Resolving ip address 111.222.333.6
[2022-07-14 05:28:47,381] INFO: ip address to resolve 111.222.333.6
[2022-07-14 05:28:47,382] INFO: Creating snapshots on all nodes
[2022-07-14 05:28:47,383] INFO: Executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd snapshot -t medusa-data1" on following nodes ['node2-dc1.domain.com', 'node1-dc1.domain.com', 'node3-dc1.domain.com'] with a parallelism/pool size of 500
[2022-07-14 05:28:49,727] INFO: Job executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd snapshot -t medusa-data1" ran and finished Successfully on all nodes.
[2022-07-14 05:28:49,728] INFO: A snapshot medusa-data1 was created on all nodes.
[2022-07-14 05:28:49,728] INFO: Uploading snapshots from nodes to external storage
[2022-07-14 05:28:49,729] INFO: Executing "mkdir -p /tmp/medusa-job-2f802190-5677-4090-a150-95314eb604db; cd /tmp/medusa-job-2f802190-5677-4090-a150-95314eb604db && medusa-wrapper sudo medusa  -vvv backup-node --backup-name data1   --mode full" on following nodes ['node2-dc1.domain.com', 'node1-dc1.domain.com', 'node3-dc1.domain.com'] with a parallelism/pool size of 1
[2022-07-14 05:28:56,387] ERROR: Job executing "mkdir -p /tmp/medusa-job-2f802190-5677-4090-a150-95314eb604db; cd /tmp/medusa-job-2f802190-5677-4090-a150-95314eb604db && medusa-wrapper sudo medusa  -vvv backup-node --backup-name data1   --mode full" ran and finished with errors on following nodes: ['node1-dc1.domain.com', 'node2-dc1.domain.com', 'node3-dc1.domain.com']
[2022-07-14 05:28:56,389] ERROR: Some nodes failed to upload the backup.
[2022-07-14 05:28:56,389] ERROR: This error happened during the cluster backup: Some nodes failed to upload the backup.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_cluster.py", line 64, in orchestrate
    backup.execute(cql_session_provider)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_cluster.py", line 150, in execute
    self._upload_backup()
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_cluster.py", line 177, in _upload_backup
    raise Exception(err_msg)
Exception: Some nodes failed to upload the backup.
[2022-07-14 05:28:56,390] ERROR: Something went wrong! Attempting to clean snapshots and exit.
[2022-07-14 05:28:56,390] INFO: Executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd clearsnapshot -t medusa-data1" on following nodes ['node2-dc1.domain.com', 'node1-dc1.domain.com', 'node3-dc1.domain.com'] with a parallelism/pool size of 1
[2022-07-14 05:29:01,037] INFO: Job executing "nodetool -Dcom.sun.jndi.rmiURLParsing=legacy -u nodetooluser -pw nodetoolpwd clearsnapshot -t medusa-data1" ran and finished Successfully on all nodes.
[2022-07-14 05:29:01,037] INFO: All nodes successfully cleared their snapshot.
```

**Comment by adejanovski** [comment]
Hi @kaushalkumar, could you check the medusa logs on each node showing what error made the upload fail?

**Comment by rzvoncek** [comment]
I tried to reproduce this, but I only ran into this if a backup failed (then the snapshot didn't get cleared). That's the behaviour we want (to be conservative about clearing snapshots). Otherwise I could not reproduce this.
