### ISSUE TITLE
restore-cluster - host-list mapping file with an empty last line throws error

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#505]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952002)

Hi - While restoring data using restore-cluster an error is observed if the last line in host-list mapping file is an empty line. The error is given below. Can you please check it.

```
[2022-07-18 11:15:33,374] ERROR: This error happened during the cluster restore: not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 71, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 153, in execute
    self.prepare_restore()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 148, in prepare_restore
    self._populate_hostmap()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 297, in _populate_hostmap
    seed, target, source = _line.split(self.config.storage.host_file_separator)
ValueError: not enough values to unpack (expected 3, got 1)
```

Regards,

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1672) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1672
┆priority: Medium

**Comment by adejanovski** [comment]
We should most probably ignore empty lines indeed.
I think the host list mapping technique is not something we should rely upon anymore as it was created back when Medusa couldn't compute mappings on its own. It can now, so using a seed host is most probably the best thing to do.
This, and the fact that there's a workaround (remove the blank line) make this work low priority.
