### ISSUE TITLE
grpc - status invocation fails with error

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#514]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951996)

Hi - While executing status command via grpc we see following error. The status command works via medusa cli. Can you please check

**Error**

```
ERROR:grpc._server:Exception calling application: 'NoneType' object has no attribute '_BackupMan__backups'
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/usr/local/lib/python3.6/site-packages/medusa/service/grpc/server.py", line 181, in BackupStatus
    record_status_in_response(response, request.backupName)
  File "/usr/local/lib/python3.6/site-packages/medusa/service/grpc/server.py", line 323, in record_status_in_response
    status = BackupMan.get_backup_status(backup_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_manager.py", line 73, in get_backup_status
    if backup_name not in BackupMan.__instance.__backups:
AttributeError: 'NoneType' object has no attribute '_BackupMan__backups'
[2022-08-02 10:00:44,745] ERROR: Exception calling application: 'NoneType' object has no attribute '_BackupMan__backups'
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/usr/local/lib/python3.6/site-packages/medusa/service/grpc/server.py", line 181, in BackupStatus
    record_status_in_response(response, request.backupName)
  File "/usr/local/lib/python3.6/site-packages/medusa/service/grpc/server.py", line 323, in record_status_in_response
    status = BackupMan.get_backup_status(backup_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_manager.py", line 73, in get_backup_status
    if backup_name not in BackupMan.__instance.__backups:
AttributeError: 'NoneType' object has no attribute '_BackupMan__backups'
```

Regards,

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1715) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1715
┆priority: Medium

**Comment by adejanovski** [comment]
This has been revamped recently and shouldn't occur anymore.
@kaushalkumar, feel free to reopen if you're still experiencing this with the latest releases.
