### ISSUE TITLE
medusa restore-cluster and sstableloader error

### ISSUE THREAD

**Issue by Anasme** [thelastpickle/cassandra-medusa#520]
Hello,

I'm tryin to restore 3 nodes backups (cluster backup) to 1 node.

I did a cluster-backup with medusa on s3 like this : 

```
medusa backup-cluster --backup-name="restore-test-001"
```

it success.

Then I tried to restore this backup to my single node :

```
medusa restore-cluster --backup-name="restore-test-001" --seed-target ops-cassandra-test
```

I got an error on the sstableloader step:

    [2022-09-09 11:59:43,498] INFO: Executing "mkdir -p /tmp/medusa-job-4237e8b8-1dbe-4c5a-9f99-8062c0bc6190; cd /tmp/medusa-job-4237e8b8-1dbe-4c5a-9f99-8062c0bc6190 && medusa-wrapper sudo medusa  --fqdn=%s -vvv restore-node --remote --keep-auth %s --no-verify --backup-name restore-test-001 --temp-dir /tmp --use-sstableloader --keyspace test " on following nodes ['ops-cassandra-test'] with a parallelism/pool size of 500
    [2022-09-09 12:06:48,513] ERROR: Job executing "mkdir -p /tmp/medusa-job-4237e8b8-1dbe-4c5a-9f99-8062c0bc6190; cd /tmp/medusa-job-4237e8b8-1dbe-4c5a-9f99-8062c0bc6190 && medusa-wrapper sudo medusa  --fqdn=%s -vvv restore-node --remote --keep-auth %s --no-verify --backup-name restore-test-001 --temp-dir /tmp --use-sstableloader --keyspace test " ran and finished with errors on following nodes: ['ops-cassandra-test']
    [2022-09-09 12:06:48,518] ERROR: Some nodes failed to restore. Exiting
    [2022-09-09 12:06:48,518] ERROR: This error happened during the cluster restore: Some nodes failed to restore. Exiting
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 71, in orchestrate
        restore.execute()
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 154, in execute
        self._restore_data()
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 372, in _restore_data
        raise RuntimeError(err_msg)
    RuntimeError: Some nodes failed to restore. Exiting```
    
    - stderr
    `All host(s) tried for query failed (tried: ops-cassandra-test/10.65.4.79:9042 (com.datastax.driver.core.exceptions.TransportException: [ops-cassandra-test/10.65.4.79:9042] Cannot connect))
    com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ops-cassandra-test/10.65.4.79:9042 (com.datastax.driver.core.exceptions.TransportException: [ops-cassandra-test/10.65.4.79:9042] Cannot connect))
    	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
    	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
    	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
    	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
    	at com.datastax.driver.core.Cluster.init(Cluster.java:214)
    	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
    	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
    	at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
    	at org.apache.cassandra.utils.NativeSSTableLoaderClient.init(NativeSSTableLoaderClient.java:71)
    	at org.apache.cassandra.io.sstable.SSTableLoader.stream(SSTableLoader.java:188)
    	at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:79)
    	at org.apache.cassandra.tools.BulkLoader.main(BulkLoader.java:51)
    Exception in thread "main" org.apache.cassandra.tools.BulkLoadException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ops-cassandra-test/10.65.4.79:9042 (com.datastax.driver.core.exceptions.TransportException: [ops-cassandra-test/10.65.4.79:9042] Cannot connect))
    	at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:96)
    	at org.apache.cassandra.tools.BulkLoader.main(BulkLoader.java:51)
    Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ops-cassandra-test/10.65.4.79:9042 (com.datastax.driver.core.exceptions.TransportException: [ops-cassandra-test/10.65.4.79:9042] Cannot connect))
    	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
    	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
    	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
    	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
    	at com.datastax.driver.core.Cluster.init(Cluster.java:214)
    	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:387)
    	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:366)
    	at com.datastax.driver.core.Cluster.connect(Cluster.java:311)
    	at org.apache.cassandra.utils.NativeSSTableLoaderClient.init(NativeSSTableLoaderClient.java:71)
    	at org.apache.cassandra.io.sstable.SSTableLoader.stream(SSTableLoader.java:188)
    	at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:79)
    	... 1 more
    Traceback (most recent call last):
      File "/usr/local/bin/medusa", line 8, in <module>
        sys.exit(cli())
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
        return __callback(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 84, in new_func
        return ctx.invoke(f, obj, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
        return __callback(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/medusa/medusacli.py", line 271, in restore_node
        verify, set(keyspaces), set(tables), use_sstableloader, version_target)
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_node.py", line 54, in restore_node
        keyspaces, tables)
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_node.py", line 181, in restore_node_sstableloader
        cassandra.native_port)
      File "/usr/local/lib/python3.6/site-packages/medusa/restore_node.py", line 232, in invoke_sstableloader
        output = subprocess.check_output(sstableloader_args)
      File "/usr/local/lib64/python3.6/site-packages/gevent/subprocess.py", line 405, in check_output
        raise CalledProcessError(retcode, process.args, output=output)
    subprocess.CalledProcessError: Command '['sstableloader', '-d', 'ops-cassandra-test', '--conf-path', '/mnt/softwarefactory/cassandra/conf/cassandra.yaml', '--username', 'cassandra', '--password', 'cassandra', '--no-progress', '--port', '9042', '/tmp/medusa-restore-1970e907-b812-45d8-aa3a-0b7bea889776/system_distributed/parent_repair_history-deabd734b99d3b9c92e5fd92eb5abf14', '-ts', '/mnt/softwarefactory/cassandra/conf/ssl/cassandra.keystore', '-tspw', 'password', '-ks', '/mnt/softwarefactory/cassandra/conf/ssl/cassandra.truststore', '-kspw', 'password']' returned non-zero exit status 1.```

it seems the sstableloader cannot connect to cassandra, so I tried to launch the command bellow:

```
./bin/sstableloader \
     -d ops-cassandra-test \
     --conf-path /mnt/softwarefactory/cassandra/conf/cassandra.yaml \
     --username cassandra --password cassandra \
     --no-progress \
     --port 9042 \
     /tmp/medusa-restore-1970e907-b812-45d8-aa3a-0b7bea889776/system_distributed/parent_repair_history-deabd734b99d3b9c92e5fd92eb5abf14 \
     -ts /mnt/softwarefactory/cassandra/conf/ssl/cassandra.keystore \
     -tspw password \
     -ks /mnt/softwarefactory/cassandra/conf/ssl/cassandra.truststore \
     -kspw password
```

I got the same error of course (on port 9042), then I launched this:

```
./bin/sstableloader \
     -d ops-cassandra-test \
     --conf-path /mnt/softwarefactory/cassandra/conf/cassandra.yaml \
     --username cassandra --password cassandra \
     --no-progress \
     --port 9042 \
     /tmp/medusa-restore-1970e907-b812-45d8-aa3a-0b7bea889776/system_distributed/parent_repair_history-deabd734b99d3b9c92e5fd92eb5abf14
```

no more 9042 error connection but a this one now :

```
ERROR 13:13:44,993 [Stream #360cf620-3041-11ed-9403-19699e67fd46] Streaming error occurred on session with peer 10.65.4.79:7000
java.io.IOException: failed to connect to /10.65.4.79:7000 for streaming data
	at org.apache.cassandra.streaming.DefaultConnectionFactory.createConnection(DefaultConnectionFactory.java:55)
	at org.apache.cassandra.tools.BulkLoadConnectionFactory.createConnection(BulkLoadConnectionFactory.java:52)
	at org.apache.cassandra.streaming.async.NettyStreamingMessageSender.createChannel(NettyStreamingMessageSender.java:199)
	at org.apache.cassandra.streaming.async.NettyStreamingMessageSender.setupControlMessageChannel(NettyStreamingMessageSender.java:180)
	at org.apache.cassandra.streaming.async.NettyStreamingMessageSender.sendMessage(NettyStreamingMessageSender.java:245)
	at org.apache.cassandra.streaming.async.NettyStreamingMessageSender.initialize(NettyStreamingMessageSender.java:149)
	at org.apache.cassandra.streaming.StreamSession.start(StreamSession.java:363)
	at org.apache.cassandra.streaming.StreamCoordinator.startSession(StreamCoordinator.java:263)
	at org.apache.cassandra.streaming.StreamCoordinator.access$700(StreamCoordinator.java:37)
	at org.apache.cassandra.streaming.StreamCoordinator$HostStreamingData.connectAllStreamSessions(StreamCoordinator.java:309)
	at org.apache.cassandra.streaming.StreamCoordinator.connectAllStreamSessions(StreamCoordinator.java:108)
	at org.apache.cassandra.streaming.StreamCoordinator.connect(StreamCoordinator.java:102)
	at org.apache.cassandra.streaming.StreamResultFuture.createInitiator(StreamResultFuture.java:98)
	at org.apache.cassandra.streaming.StreamPlan.execute(StreamPlan.java:179)
	at org.apache.cassandra.io.sstable.SSTableLoader.stream(SSTableLoader.java:220)
	at org.apache.cassandra.tools.BulkLoader.load(BulkLoader.java:79)
	at org.apache.cassandra.tools.BulkLoader.main(BulkLoader.java:51)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /10.65.4.79:7000
```

I'm stuck here, I don't know what to do I tried to change the ip rpc with the ip bellow (10.65.4.79) , I can telnet on it on 7000 port...

cassandra.yaml:

```
rpc_address: 0.0.0.0
broadcast_rpc_address: "public_ip"
listen_address: ops-cassandra-test
```

cassandra version `4.0.4`
medusa version `0.13.4`

Tell me if you need more info.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1773) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1773
┆priority: Medium

**Comment by Anasme** [comment]
> Hello [Anasme]
> What exactly memory and could you please provide steps to fix this issue. I was increase
> MAX_HEAP_SIZE
> HEAP_NEWSIZE
> but still no hopes.
> Thanks.

Hello nguyenthai0107,
it was a test so it was a throwaway, I don't remember exactly what config I used, but I usually configure the xmx and xms in the jvm-server.options file in the heap section: 

```
#################
# HEAP SETTINGS #
#################

# Heap size is automatically calculated by cassandra-env based on this
# formula: max(min(1/2 ram, 1024MB), min(1/4 ram, 8GB))
# That is:
# - calculate 1/2 ram and cap to 1024MB
# - calculate 1/4 ram and cap to 8192MB
# - pick the max
#
# For production use you may wish to adjust this for your environment.
# If that's the case, uncomment the -Xmx and Xms options below to override the
# automatic calculation of JVM heap memory.
#
# It is recommended to set min (-Xms) and max (-Xmx) heap sizes to
# the same value to avoid stop-the-world GC pauses during resize, and
# so that we can lock the heap in memory on startup to prevent any
# of it from being swapped out.
-Xms8G
-Xmx8G
```

I use like ~ 1/3 memory of the server for heapspace jvm of cassandra, the rest being for the non-heap and the system

I hope this will help you.
