### ISSUE TITLE
Exception while invoking BackupStatus using grpc - after restart of pod

### ISSUE THREAD

**Issue by kaushalkumar** [thelastpickle/cassandra-medusa#530]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951973)

Hi - An error is thrown while invoking "backupStatus" API using grpc. This error is observed when this API is invoked after restart of the medusa container using which the backup was created.
The error is given below

```
[2022-09-29 09:44:19,298] ERROR: Exception calling application: 'NoneType' object has no attribute '_BackupMan__backups'
Traceback (most recent call last):
  File "/home/cassandra/.local/lib/python3.6/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/cassandra/medusa/service/grpc/server.py", line 181, in BackupStatus
    record_status_in_response(response, request.backupName)
  File "/home/cassandra/medusa/service/grpc/server.py", line 323, in record_status_in_response
    status = BackupMan.get_backup_status(backup_name)
  File "/home/cassandra/medusa/backup_manager.py", line 73, in get_backup_status
    if backup_name not in BackupMan.__instance.__backups:
AttributeError: 'NoneType' object has no attribute '_BackupMan__backups'
```

Looking into the code, it looks like BackupMan object is not iniitalized (via BackupStatus) and thus it throws an error.
Can you please look into this

Regards,
Kaushal

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1811) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1811
┆priority: Medium

**Comment by rzvoncek** [comment]
I believe this got fixed with https://github.com/thelastpickle/cassandra-medusa/pull/720.
