### ISSUE TITLE
backup on IBMCLOUD S3 failed

### ISSUE THREAD

**Issue by NLatarche** [thelastpickle/cassandra-medusa#550]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=17056245)

Even I have all the permission to list/read/write a S3 on ibmcloud , when I execute the backup I have this  error :

 medusa  --version
0.14.0

 medusa backup --backup-name=TestBackup --mode=full

[2022-12-28 09:09:30,595] INFO: Resolving ip address
[2022-12-28 09:09:30,595] INFO: ip address to resolve 10.244.118.186
[2022-12-28 09:09:30,597] INFO: Registered backup id TestBackup
[2022-12-28 09:09:30,597] INFO: Monitoring provider is noop
[2022-12-28 09:09:30,614] INFO: Found credentials in shared credentials file: /etc/medusa/medusa-ibm-credentials
[2022-12-28 09:09:31,337] ERROR: Issue occurred inside handle_backup Name: TestBackup Error: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7fde29f099e8>, container=bu002i003398, value=None>
[2022-12-28 09:09:31,337] INFO: Updated from existing status: -1 to new status: 2 for backup id: TestBackup
[2022-12-28 09:09:31,338] ERROR: Error occurred during backup: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7fde29f099e8>, container=bu002i003398, value=None>
Traceback (most recent call last):
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/medusa/backup_node.py", line 178, in handle_backup
    storage = Storage(config=config.storage)
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 75, in __init__
    self.storage_driver = self._connect_storage()
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 93, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/medusa/storage/s3_base_storage.py", line 72, in __init__
    super().__init__(config)
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/root/python3-virtualenv/lib64/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 360, in get_container
    container_name=container_name)
libcloud.storage.types.ContainerDoesNotExistError: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7fde29f099e8>, container=bu002i003398, value=None>

Any idea? 
Thank you

**Comment by NLatarche** [comment]
By commenting the line above in ..../libcloud/storage/drivers/s3.py, the backup is done successfully and also a test of restore of one table is ok.
Maybe something is not supported with the method HEAD on the COS IBMCLOUD 
 
 356             response = self.connection.request('/%s' % container_name,
 357                                                method='HEAD')
358          #   if response.status == httplib.NOT_FOUND:
 359          #       raise ContainerDoesNotExistError(value=None, driver=self,
 360          #                                        container_name=container_name)

**Comment by adejanovski** [comment]
I suspect there could be a problem with your settings.
While obfuscating the sensitive parts, could you share your medusa.ini file?

**Comment by NLatarche** [comment]
medusa.ini :


[storage]
storage_provider = s3_compatible
bucket_name = bu002i003398
key_file = /etc/medusa/medusa-ibm-credentials
; replace the following with your bucket's region and host
region = eu-fr2
host = bu002i003398.s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud:4203
secure = True
multi_part_upload_threshold = 0

[cassandra]
stop_cmd = sudo service dse stop
start_cmd = sudo service dse start
config_file = /apps/datastax/dse/resources/cassandra/conf/cassandra.yaml
cql_username = cassandra
cql_password =  5Ycivcf.4Vc7N6wgUZmB
nodetool_username =  cassandra
nodetool_password =  *****************
;nodetool_password_file_path = <path to nodetool password file>
;nodetool_host = <host name or IP to use for nodetool>
;nodetool_port = <port number to use for nodetool>
;certfile= <Client SSL: path to rootCa certificate>
;usercert= <Client SSL: path to user certificate>
;userkey= <Client SSL: path to user key>
;sstableloader_ts = <Client SSL: full path to truststore>
;sstableloader_tspw = <Client SSL: password of the truststore>
;sstableloader_ks = <Client SSL: full path to keystore>
;sstableloader_kspw = <Client SSL: password of the keystore>
;sstableloader_bin = <Location of the sstableloader binary if not in PATH>

; Enable this to add the '--ssl' parameter to nodetool. The nodetool-ssl.properties is expected to be in the normal location
;nodetool_ssl = true

; Command ran to verify if Cassandra is running on a node. Defaults to "nodetool version"
;check_running = nodetool version

; Disable/Enable ip address resolving.
; Disabling this can help when fqdn resolving gives different domain names for local and remote nodes
; which makes backup succeed but Medusa sees them as incomplete.
; Defaults to True.
resolve_ip_addresses = True

; When true, almost all commands executed by Medusa are prefixed with `sudo`.
; Does not affect the use_sudo_for_restore setting in the 'storage' section.
; See https://github.com/thelastpickle/cassandra-medusa/issues/318
; Defaults to True
use_sudo = True


[monitoring]
;monitoring_provider = <Provider used for sending metrics. Currently either of "ffwd" or "local">

[ssh]
;username = <SSH username to use for restoring clusters>
;key_file = <SSH key for use for restoring clusters. Expected in PEM unencrypted format.>
;port = <SSH port for use for restoring clusters. Default to port 22.
;cert_file = <Path of public key signed certificate file to use for authentication. The corresponding private key must also be provided via key_file parameter>

[checks]
;health_check = <Which ports to check when verifying a node restored properly. Options are 'cql' (default), 'thrift', 'all'.>
;query = <CQL query to run after a restore to verify it went OK>
;expected_rows = <Number of rows expected to be returned when the query runs. Not checked if not specified.>
;expected_result = <Coma separated string representation of values returned by the query. Checks only 1st row returned, and only if specified>
;enable_md5_checks = <During backups and verify, use md5 calculations to determine file integrity (in addition to size, which is used by default)>

[logging]
; Controls file logging, disabled by default.
; enabled = 0
; file = medusa.log
; level = INFO

; Control the log output format
; format = [%(asctime)s] %(levelname)s: %(message)s

; Size over which log file will rotate
; maxBytes = 20000000

; How many log files to keep
; backupCount = 50

[grpc]
; Set to true when running in grpc server mode.
; Allows to propagate the exceptions instead of exiting the program.
;enabled = False

[kubernetes]
; The following settings are only intended to be configured if Medusa is running in containers, preferably in Kubernetes.
;enabled = False
;cassandra_url = <URL of the management API snapshot endpoint. For example: http://127.0.0.1:8080/api/v0/ops/node/snapshots>

; Enables the use of the management API to create snapshots. Falls back to using Jolokia if not enabled.
;use_mgmt_api = True

**Comment by adejanovski** [comment]
The `host` setting doesn't look right (but it could be a lack of knowledge from me on IBM cloud).
We have a `port` setting if you want to use a custom port, and I'm not totally sure if you should have the bucket name in the host url.
Using `multi_part_upload_threshold = 0` is going to be inefficient if you have a lot of small files (which you probably do) as it'll rely only on the awscli for transfers.
I guess the settings aren't allowing libcloud to communicate correctly with the storage backend and setting that threshold to 0 is working around this as the settings work nicely for awscli.

First, try removing the port from the host and put it in its own setting, then if it doesn't fix it, try to modify the host setting again to remove the bucket name from it and use just `s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud`.

**Comment by NLatarche** [comment]
For the name of the host/port , I think it is specific to IBM ( we have a private ibm cloud) . 
I already tried to remove  bucket name  from the host but  it does not work.  I will try to remove the port and use a port setting separately and I let you know
for multi_part_upload_threshold greater than  0 it caused an error for me,  and I see in other issue that is because I have an sstable with size 0 bytes .  So after I modified it 0 , it's worked

**Comment by NLatarche** [comment]
Hi,

Still errors by :

--->**removing the port from the host and put it in its own setting**

host = bu002i003398.s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud
port = 4203
-------------

medusa  backup --backup-name=TestNourForPort  --mode=full
[2023-01-04 15:51:07,158] INFO: Resolving ip address
[2023-01-04 15:51:07,158] INFO: ip address to resolve 10.229.57.34
[2023-01-04 15:51:07,161] INFO: Registered backup id TestNourForPort
[2023-01-04 15:51:07,161] INFO: Monitoring provider is noop
[2023-01-04 15:51:07,190] INFO: Found credentials in shared credentials file: /etc/medusa/medusa-ibm-credentials
[2023-01-04 15:51:07,998] ERROR: Issue occurred inside handle_backup Name: TestNourForPort Error: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7f8283f93b38>, container=bu002i003398, value=None>
[2023-01-04 15:51:07,999] INFO: Updated from existing status: -1 to new status: 2 for backup id: TestNourForPort
[2023-01-04 15:51:07,999] ERROR: Error occurred during backup: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7f8283f93b38>, container=bu002i003398, value=None>
Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/backup_node.py", line 178, in handle_backup
    storage = Storage(config=config.storage)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 75, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 93, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/s3_base_storage.py", line 72, in __init__
    super().__init__(config)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 360, in get_container
    container_name=container_name)
libcloud.storage.types.ContainerDoesNotExistError: <ContainerDoesNotExistError in <medusa.libcloud.storage.drivers.s3_base_driver.S3BaseStorageDriver object at 0x7f8283f93b38>, container=bu002i003398, value=None>

#################################



---> ** by  removing the bucket name from the host name **


-----------------------

host = s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud
port = 4203

----------------------


(python3-virtualenv-cassandra) cassandra@s00vl9997934:~$  medusa  backup --backup-name=TestNourForBucket  --mode=full
[2023-01-04 15:53:58,494] INFO: Resolving ip address
[2023-01-04 15:53:58,495] INFO: ip address to resolve 10.229.57.34
[2023-01-04 15:53:58,496] INFO: Registered backup id TestNourForBucket
[2023-01-04 15:53:58,496] INFO: Monitoring provider is noop
[2023-01-04 15:53:58,514] INFO: Found credentials in shared credentials file: /etc/medusa/medusa-ibm-credentials
[2023-01-04 15:56:05,736] ERROR: Issue occurred inside handle_backup Name: TestNourForBucket Error: HTTPSConnectionPool(host='s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud', port=4203): Max retries exceeded with url: /bu002i003398 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f941a85a048>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2023-01-04 15:56:05,736] INFO: Updated from existing status: -1 to new status: 2 for backup id: TestNourForBucket
[2023-01-04 15:56:05,736] ERROR: Error occurred during backup: HTTPSConnectionPool(host='s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud', port=4203): Max retries exceeded with url: /bu002i003398 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f941a85a048>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f941a85a048>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud', port=4203): Max retries exceeded with url: /bu002i003398 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f941a85a048>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/backup_node.py", line 178, in handle_backup
    storage = Storage(config=config.storage)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 75, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/__init__.py", line 93, in _connect_storage
    s3_storage = S3BaseStorage(self._config)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/s3_base_storage.py", line 72, in __init__
    super().__init__(config)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/medusa/storage/abstract_storage.py", line 40, in __init__
    self.bucket = self.driver.get_container(container_name=config.bucket_name)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 357, in get_container
    method='HEAD')
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/common/base.py", line 623, in request
    headers=headers, stream=stream)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/libcloud/http.py", line 232, in request
    verify=self.verification
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/cassandra/python3-virtualenv-cassandra/lib64/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.direct.eu-fr2.cloud-object-storage.appdomain.cloud', port=4203): Max retries exceeded with url: /bu002i003398 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f941a85a048>: Failed to establish a new connection: [Errno 110] Connection timed out',))
