### ISSUE TITLE
Medusa Backup Failing during "Updating backup index"

### ISSUE THREAD

**Issue by tb2501** [thelastpickle/cassandra-medusa#575]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=26212274)

Hello, 

I'm encountering an interesting issue during Medusa's backup consistently for C* systems in which a high number of db files exists for the Node.

For my test, i'm simply attempting to perform a Medusa Backup of 1 Cassandra Node from our cluster.

It constantly fails shortly after: Updating backup index

[2023-03-24 23:46:26,536] INFO: Updating backup index
[2023-03-24 23:54:47,022] ERROR: Issue occurred inside handle_backup Name: backup_test Error: <LibcloudError in <libcloud.storage.drivers.s3.S3StorageDriver object at 0x7fc18e30a518> 'Error initiating multipart upload'>
[2023-03-24 23:54:47,022] INFO: Updated from existing status: 0 to new status: 2 for backup id: backup_test
[2023-03-24 23:54:47,022] ERROR: Error occurred during backup: <LibcloudError in <libcloud.storage.drivers.s3.S3StorageDriver object at 0x7fc18e30a518> 'Error initiating multipart upload'>

I believe the issue is during the upload of the Manifest file, as we notice that file is always missing from our S3 bucket post the failure.

I tried also modifying /usr/local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py

Commenting out line 746 - 753, related to the api call being made to upload the manifest file.  The thought was, if I default to using single part upload instead of multi part, then we might not encounter the error.  I also added in a method for obtaining the status regardless if the upload is successful or not.

I'm running into a 400 error code as seen below.

Has anyone else encountering something similar, or have any advice on how we can move forward?

Log Snip post my slight modifications to s3.py.

[2023-04-20 04:54:13,859] INFO: Updating backup index
[2023-04-20 05:02:34,667] ERROR: Issue occurred inside handle_backup Name: backup_test 
Error: <LibcloudError in <libcloud.storage.drivers.s3.S3StorageDriver object at 0x7f05dc6ad710> 'Unexpected status code, status_code=400'>
[2023-04-20 05:02:34,667] INFO: Updated from existing status: 0 to new status: 2 for backup id: backup_test
[2023-04-20 05:02:34,667] ERROR: Error occurred during backup: <LibcloudError in <libcloud.storage.drivers.s3.S3StorageDriver object at 0x7f05dc6ad710> 'Unexpected status code, status_code=400'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 197, in handle_backup
    enable_md5_checks_flag, backup_name, config, monitoring)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 250, in start_backup
    cassandra, node_backup, storage, differential_mode, enable_md5, config, backup_name)
  File "/usr/local/lib/python3.6/site-packages/medusa/backup_node.py", line 299, in do_backup
    node_backup.manifest = json.dumps(manifest)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/node_backup.py", line 220, in manifest
    self._storage.storage_driver.upload_blob_from_string(self.manifest_path, manifest)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/site-packages/medusa/storage/abstract_storage.py", line 68, in upload_blob_from_string
    headers=headers,
  File "/usr/local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 758, in upload_object_via_stream
    storage_class=ex_storage_class)
  File "/usr/local/lib/python3.6/site-packages/libcloud/storage/drivers/s3.py", line 936, in _put_object
    driver=self)
libcloud.common.types.LibcloudError: <LibcloudError in <libcloud.storage.drivers.s3.S3StorageDriver object at 0x7f05dc6ad710> 'Unexpected status code, status_code=400'>

$ medusa --version
0.14.0

**Comment by adejanovski** [comment]
This issue was fixed in v0.16.0 when we revamped the storage backend and dropped libcloud.
