### ISSUE TITLE
Medusa GCS credentials doesn't work

### ISSUE THREAD

**Issue by gkiranch** [thelastpickle/cassandra-medusa#599]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=33583810)

Hi, i am testing medusa on GKE
I have created necessary iam role and provided permission and downloaded the credentials. 
I have created secret in kubernetes cluster with the credentials downloaded from GCP
When i try to deploy medusa, the container fails with below error 

MEDUSA_MODE = GRPC
sleeping for 0 sec
Starting Medusa gRPC service
WARNING:root:The CQL_USERNAME environment variable is deprecated and has been replaced by the MEDUSA_CQL_USERNAME variable
WARNING:root:The CQL_PASSWORD environment variable is deprecated and has been replaced by the MEDUSA_CQL_PASSWORD variable
WARNING:root:The CQL_USERNAME environment variable is deprecated and has been replaced by the MEDUSA_CQL_USERNAME variable
WARNING:root:The CQL_PASSWORD environment variable is deprecated and has been replaced by the MEDUSA_CQL_PASSWORD variable
INFO:root:Init service
[2023-07-18 15:59:08,295] INFO: Init service
DEBUG:root:Loading storage_provider: google_storage
[2023-07-18 15:59:08,295] DEBUG: Loading storage_provider: google_storage
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cassandra/medusa/service/grpc/server.py", line 349, in <module>
    server.serve()
  File "/home/cassandra/medusa/service/grpc/server.py", line 65, in serve
    medusa_pb2_grpc.add_MedusaServicer_to_server(MedusaService(config), self.grpc_server)
  File "/home/cassandra/medusa/service/grpc/server.py", line 104, in __init__
    self.storage = Storage(config=self.config.storage)
  File "/home/cassandra/medusa/storage/__init__.py", line 75, in __init__
    self.storage_driver = self._connect_storage()
  File "/home/cassandra/medusa/storage/__init__.py", line 81, in _connect_storage
    google_storage = GoogleStorage(self._config)
  File "/home/cassandra/medusa/storage/abstract_storage.py", line 39, in __init__
    self.driver = self.connect_storage()
  File "/home/cassandra/medusa/storage/google_storage.py", line 39, in connect_storage
    with io.open(os.path.expanduser(self.config.key_file), 'r', encoding='utf-8') as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/medusa-secrets/credentials'

I have the secret available in the namespace, re-verified the name and it is correct. 

I have tested similar setup in AWS S3 and it works as expected.

**Comment by adejanovski** [comment]
Hi, 

Are you using Medusa with k8ssandra-operator or with your own custom orchestration?
Here's it's not finding the `/etc/medusa-secrets/credentials` file, so it means it's not mounted at this path with this name.
Do you have some manifests (pod + secret) that we could check to figure out what's wrong?
