### ISSUE TITLE
No such file or directory: 'nodetool'

### ISSUE THREAD

**Issue by vijaythakur-plasma** [thelastpickle/cassandra-medusa#60]
Hi,
I am using cassandra 3.11  with cassandra-medusa 0.4.1 
Cassandra located :/usr/share/cassandra

It showing: 

:~# medusa backup --backup-name=22012020
[2020-01-22 16:38:38] INFO: Monitoring provider is noop
[2020-01-22 16:38:38] WARNING: is ccm : 0
[2020-01-22 16:38:38] INFO: Creating snapshot
[2020-01-22 16:38:38] INFO: Saving tokenmap and schema
[2020-01-22 16:38:38] INFO: Node local does not have latest backup
[2020-01-22 16:38:38] INFO: Starting backup
[2020-01-22 16:38:38] ERROR: This error happened during the backup: [Errno 2] **No such file or directory: 'nodetool'**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 274, in main
    cassandra, node_backup, storage, differential_mode, config)
  File "/usr/local/lib/python3.7/site-packages/medusa/backup.py", line 318, in do_backup
    with cassandra.create_snapshot() as snapshot:
  File "/usr/local/lib/python3.7/site-packages/medusa/cassandra_utils.py", line 336, in create_snapshot
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, universal_newlines=True)
  File "/usr/local/lib/python3.7/site-packages/gevent/subprocess.py", line 270, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gevent/subprocess.py", line 249, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/site-packages/gevent/subprocess.py", line 627, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/site-packages/gevent/subprocess.py", line 1505, in _execute_child
    raise child_exception
FileNotFoundError: [Errno 2] No such file or directory: 'nodetool'

**Comment by adejanovski** [comment]
Hi @vijaythakur-plasma,

it looks like the user which runs medusa doesn't have `nodetool` in its path.
Are you running Medusa on a Cassandra node? Where is `nodetool` located and could you try adding it to the user's path?

**Comment by dmitry-saprykin** [comment]
Hi @vijaythakur-plasma,

I had the same issue.
PATH=$PATH:/usr/share/cassandra/bin medusa backup --backup-name=22012020 worked well for me.
