### ISSUE TITLE
Node 1 is failing to start cassandra after restore-cluster

### ISSUE THREAD

**Issue by ei-show** [thelastpickle/cassandra-medusa#633]
Restore cassandra consisting of three nodes using restore-cluster from gcs.

<details>
  <summary>Click me to medusa log & cfg</summary>

``` sh
$ medusa restore-cluster --backup-name=202307291944 --host-list /etc/medusa/mapping.txt -y --keyspace kong
[2023-09-04 23:03:12,650] INFO: Resolving ip address
[2023-09-04 23:03:12,651] INFO: ip address to resolve 10.100.10.3
[2023-09-04 23:03:12,655] INFO: Monitoring provider is noop
[2023-09-04 23:03:14,525] INFO: Ensuring the backup is found and is complete
[2023-09-04 23:03:14,525] INFO: Restore will happen on new hardware
[2023-09-04 23:03:14,526] INFO: Resolving ip address dest-cassandra-01
[2023-09-04 23:03:14,526] INFO: ip address to resolve dest-cassandra-01
[2023-09-04 23:03:14,533] INFO: Resolving ip address source-cassandra-01
[2023-09-04 23:03:14,533] INFO: ip address to resolve source-cassandra-01
[2023-09-04 23:03:14,548] INFO: Resolving ip address dest-cassandra-02
[2023-09-04 23:03:14,548] INFO: ip address to resolve dest-cassandra-02
[2023-09-04 23:03:14,553] INFO: Resolving ip address source-cassandra-02
[2023-09-04 23:03:14,553] INFO: ip address to resolve source-cassandra-02
[2023-09-04 23:03:14,564] INFO: Resolving ip address dest-cassandra-03
[2023-09-04 23:03:14,564] INFO: ip address to resolve dest-cassandra-03
[2023-09-04 23:03:14,569] INFO: Resolving ip address source-cassandra-03
[2023-09-04 23:03:14,569] INFO: ip address to resolve source-cassandra-03
[2023-09-04 23:03:14,580] INFO: Starting Restore on all the nodes in this list: /etc/medusa/mapping.txt
[2023-09-04 23:03:14,581] INFO: Starting cluster restore...
[2023-09-04 23:03:14,581] INFO: Working directory for this execution: /tmp/medusa-job-89e91cf4-fc14-4c0c-bb66-0cdee7abbf85
[2023-09-04 23:03:14,581] INFO: About to restore on dest-cassandra-01 using {'source': ['source-cassandra-01'], 'seed': False} as backup source
[2023-09-04 23:03:14,581] INFO: About to restore on dest-cassandra-02 using {'source': ['source-cassandra-02'], 'seed': False} as backup source
[2023-09-04 23:03:14,581] INFO: About to restore on dest-cassandra-03 using {'source': ['source-cassandra-03'], 'seed': True} as backup source
[2023-09-04 23:03:14,581] INFO: This will delete all data on the target nodes and replace it with backup '202307291944'.
[2023-09-04 23:03:14,581] INFO: target seeds : ['dest-cassandra-03']
[2023-09-04 23:03:14,581] INFO: target hosts : ['dest-cassandra-01', 'dest-cassandra-02', 'dest-cassandra-03']
[2023-09-04 23:03:14,581] INFO: Stopping Cassandra on all nodes currently up
[2023-09-04 23:03:14,582] INFO: Executing "sudo service cassandra stop" on following nodes ['dest-cassandra-01', 'dest-cassandra-02', 'dest-cassandra-03'] with a parallelism/pool size of 500
[2023-09-04 23:03:20,897] INFO: Job executing "sudo service cassandra stop" ran and finished Successfully on all nodes.
[2023-09-04 23:03:20,897] INFO: Restoring data on dest-cassandra-01...
[2023-09-04 23:03:20,898] INFO: Restoring data on dest-cassandra-02...
[2023-09-04 23:03:20,898] INFO: Restoring data on dest-cassandra-03...
[2023-09-04 23:03:20,898] INFO: Executing "mkdir -p /tmp/medusa-job-89e91cf4-fc14-4c0c-bb66-0cdee7abbf85; cd /tmp/medusa-job-89e91cf4-fc14-4c0c-bb66-0cdee7abbf85 && medusa-wrapper sudo medusa  --fqdn=%s -vvv restore-node --remote  %s --no-verify --backup-name 202307291944 --temp-dir /tmp  --keyspace kong " on following nodes ['dest-cassandra-01', 'dest-cassandra-02', 'dest-cassandra-03'] with a parallelism/pool size of 500
[2023-09-04 23:06:24,187] INFO: Job executing "mkdir -p /tmp/medusa-job-89e91cf4-fc14-4c0c-bb66-0cdee7abbf85; cd /tmp/medusa-job-89e91cf4-fc14-4c0c-bb66-0cdee7abbf85 && medusa-wrapper sudo medusa  --fqdn=%s -vvv restore-node --remote  %s --no-verify --backup-name 202307291944 --temp-dir /tmp  --keyspace kong " ran and finished Successfully on all nodes.
[2023-09-04 23:06:24,187] INFO: Restore process is complete. The cluster should be up shortly.
[2023-09-04 23:06:24,188] INFO: Restore duration: 191
[2023-09-04 23:06:24,188] INFO: Successfully restored the cluster
```

## mapping.txt
```
False,dest-cassandra-01,source-cassandra-01
False,dest-cassandra-02,source-cassandra-02
True,dest-cassandra-03,source-cassandra-03
```

## medusa.log
```
~~~~~

[2023-09-04 23:05:18,403] DEBUG: Cleaning directory /cassandra-data/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09
[2023-09-04 23:05:18,421] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09 -> /cassandra-data/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09
[2023-09-04 23:05:18,458] DEBUG: Cleaning directory /cassandra-data/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f
[2023-09-04 23:05:18,476] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/indexes-0feb57ac311f382fba6d9024d305702f -> /cassandra-data/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f
[2023-09-04 23:05:18,512] DEBUG: Cleaning directory /cassandra-data/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6
[2023-09-04 23:05:18,530] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6 -> /cassandra-data/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6
[2023-09-04 23:05:18,566] DEBUG: Cleaning directory /cassandra-data/data/system_schema/types-5a8b1ca866023f77a0459273d308917a
[2023-09-04 23:05:18,584] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/types-5a8b1ca866023f77a0459273d308917a -> /cassandra-data/data/system_schema/types-5a8b1ca866023f77a0459273d308917a
[2023-09-04 23:05:18,619] DEBUG: Cleaning directory /cassandra-data/data/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895
[2023-09-04 23:05:18,637] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895 -> /cassandra-data/data/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895
[2023-09-04 23:05:18,673] DEBUG: Cleaning directory /cassandra-data/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f
[2023-09-04 23:05:18,690] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f -> /cassandra-data/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f
[2023-09-04 23:05:18,727] DEBUG: Cleaning directory /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f
[2023-09-04 23:05:18,747] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f -> /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f
[2023-09-04 23:05:18,789] DEBUG: Cleaning directory /cassandra-data/data/system_schema/views-9786ac1cdd583201a7cdad556410c985
[2023-09-04 23:05:18,809] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/views-9786ac1cdd583201a7cdad556410c985 -> /cassandra-data/data/system_schema/views-9786ac1cdd583201a7cdad556410c985
[2023-09-04 23:05:18,850] DEBUG: Cleaning directory /cassandra-data/data/system_schema/triggers-4df70b666b05325195a132b54005fd48
[2023-09-04 23:05:18,870] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/triggers-4df70b666b05325195a132b54005fd48 -> /cassandra-data/data/system_schema/triggers-4df70b666b05325195a132b54005fd48
[2023-09-04 23:05:18,916] DEBUG: Cleaning directory /cassandra-data/data/system_schema/functions-96489b7980be3e14a70166a0b9159450
[2023-09-04 23:05:18,940] DEBUG: Restoring /tmp/medusa-restore-3a73d4b3-4c45-419b-a3ce-ff563ad5c4fb/system_schema/functions-96489b7980be3e14a70166a0b9159450 -> /cassandra-data/data/system_schema/functions-96489b7980be3e14a70166a0b9159450

~~~~~

[2023-09-02 13:01:56,977] INFO: Verifying node state for host dest-cassandra-03 using check type cql
[2023-09-02 13:01:56,986] DEBUG: This server has systemd: True
[2023-09-02 13:01:57,159] DEBUG: Checking Cassandra health type: cql for host: dest-cassandra-03 release_ver: 3.11.9 native_port: 9042 storage_port: 7000, rpc_port: 9160
[2023-09-02 13:01:57,165] ERROR: Host 'dest-cassandra-03' is up, but port '9042' is closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 716, in is_open
    s.connect((host, port))
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
[2023-09-02 13:01:57,243] DEBUG: The node dest-cassandra-03 is not up yet...
[2023-09-02 13:01:57,247] ERROR: Host 'dest-cassandra-03' is up, but port '7000' is closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 716, in is_open
    s.connect((host, port))
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
[2023-09-02 13:01:57,247] DEBUG: The node dest-cassandra-03 is not up yet...
[2023-09-02 13:01:57,247] INFO: No seeds are up yet, will wait a minute
[2023-09-02 13:02:57,308] INFO: Verifying node state for host dest-cassandra-03 using check type cql
[2023-09-02 13:02:57,316] DEBUG: This server has systemd: True
[2023-09-02 13:02:57,490] DEBUG: Checking Cassandra health type: cql for host: dest-cassandra-03 release_ver: 3.11.9 native_port: 9042 storage_port: 7000, rpc_port: 9160
[2023-09-02 13:02:57,495] ERROR: Host 'dest-cassandra-03' is up, but port '9042' is closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 716, in is_open
    s.connect((host, port))
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
[2023-09-02 13:02:57,496] DEBUG: The node dest-cassandra-03 is not up yet...
[2023-09-02 13:02:57,500] ERROR: Host 'dest-cassandra-03' is up, but port '7000' is closed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 716, in is_open
    s.connect((host, port))
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused
[2023-09-02 13:02:57,500] DEBUG: The node dest-cassandra-03 is not up yet...
[2023-09-02 13:02:57,500] INFO: No seeds are up yet, will wait a minute
[2023-09-02 13:03:57,518] INFO: Verifying node state for host dest-cassandra-03 using check type cql
[2023-09-02 13:03:57,527] DEBUG: This server has systemd: True
[2023-09-02 13:03:57,699] DEBUG: Checking Cassandra health type: cql for host: dest-cassandra-03 release_ver: 3.11.9 native_port: 9042 storage_port: 7000, rpc_port: 9160
[2023-09-02 13:03:57,706] INFO: At least one seed is now up
[2023-09-02 13:03:57,706] INFO: Starting Cassandra
[2023-09-02 13:03:57,709] DEBUG: Starting Cassandra with sudo service cassandra start
[2023-09-02 13:03:57,789] DEBUG: Cleaning (/tmp/medusa-restore-49a5f319-5aae-4bf9-bb31-7571ecfec389)
[2023-09-02 13:03:57,789] DEBUG: Remove folder /tmp/medusa-restore-49a5f319-5aae-4bf9-bb31-7571ecfec389 and content

~~~~~
```

## cassandra.log

```
INFO  [main] 2023-09-03 00:35:01,382 StorageService.java:599 - Populating token metadata from system tables
INFO  [main] 2023-09-03 00:35:01,385 StorageService.java:606 - Token metadata:
INFO  [main] 2023-09-03 00:35:01,390 ColumnFamilyStore.java:406 - Initializing system_schema.keyspaces
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,393 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-14810-big (0.120KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,394 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-14809-big (0.446KiB)
INFO  [main] 2023-09-03 00:35:01,398 ColumnFamilyStore.java:406 - Initializing system_schema.tables
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,400 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-14795-big (2.063KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,401 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-14794-big (38.881KiB)
INFO  [main] 2023-09-03 00:35:01,405 ColumnFamilyStore.java:406 - Initializing system_schema.columns
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,408 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-11388-big (4.170KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,408 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-11387-big (4.171KiB)
DEBUG [SSTableBatchOpen:3] 2023-09-03 00:35:01,408 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-11389-big (4.170KiB)
DEBUG [SSTableBatchOpen:4] 2023-09-03 00:35:01,410 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/mc-11386-big (495.534KiB)
INFO  [main] 2023-09-03 00:35:01,414 ColumnFamilyStore.java:406 - Initializing system_schema.triggers
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,417 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/mc-3189-big (25.127KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,417 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/mc-3190-big (0.050KiB)
INFO  [main] 2023-09-03 00:35:01,422 ColumnFamilyStore.java:406 - Initializing system_schema.dropped_columns
DEBUG [CompactionExecutor:2] 2023-09-03 00:35:01,423 CompactionTask.java:255 - Compacted (47d82350-49a6-11ee-8f5b-5f263a22ecfc) 4 sstables to [/cassandra-data/data/system/local-7ad54392bcdd35a684174e047860b377/mc-261-big,] to level=0.  0.381KiB to 0.296KiB (~77% of origin
al) in 39ms.  Read Throughput = 9.567KiB/s, Write Throughput = 7.434KiB/s, Row Throughput = ~2/s.  4 total partitions merged to 1.  Partition merge counts were {4:1, }
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,424 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-2976-big (0.050KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,425 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/mc-2975-big (28.701KiB)
INFO  [main] 2023-09-03 00:35:01,428 ColumnFamilyStore.java:406 - Initializing system_schema.views
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,430 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-5-big (0.059KiB)
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,430 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/views-9786ac1cdd583201a7cdad556410c985/mc-6-big (0.050KiB)
INFO  [main] 2023-09-03 00:35:01,434 ColumnFamilyStore.java:406 - Initializing system_schema.types
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,436 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-5-big (0.059KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,436 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-6-big (0.050KiB)
INFO  [main] 2023-09-03 00:35:01,439 ColumnFamilyStore.java:406 - Initializing system_schema.functions
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,441 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/functions-96489b7980be3e14a70166a0b9159450/mc-5-big (0.059KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,441 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/functions-96489b7980be3e14a70166a0b9159450/mc-6-big (0.050KiB)
INFO  [main] 2023-09-03 00:35:01,444 ColumnFamilyStore.java:406 - Initializing system_schema.aggregates
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,446 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895/mc-6-big (0.050KiB)
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,446 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/aggregates-924c55872e3a345bb10c12f37c1ba895/mc-5-big (0.059KiB)
INFO  [main] 2023-09-03 00:35:01,451 ColumnFamilyStore.java:406 - Initializing system_schema.indexes
DEBUG [SSTableBatchOpen:2] 2023-09-03 00:35:01,453 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-1749-big (0.050KiB)
DEBUG [SSTableBatchOpen:1] 2023-09-03 00:35:01,453 SSTableReader.java:506 - Opening /cassandra-data/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/mc-1748-big (1.818KiB)
INFO  [main] 2023-09-03 00:35:01,454 ViewManager.java:137 - Not submitting build tasks for views in keyspace system_schema as storage service is not initialized
ERROR [main] 2023-09-03 00:35:01,483 CassandraDaemon.java:706 - Exception encountered during startup
INFO  [main] 2023-09-02 23:59:13,948 ViewManager.java:137 - Not submitting build tasks for views in keyspace system_schema as storage service is not initialized
ERROR [main] 2023-09-02 23:59:13,982 CassandraDaemon.java:706 - Exception encountered during startup
java.lang.IllegalArgumentException: null
        at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_151]
        at org.apache.cassandra.io.compress.LZ4Compressor.uncompress(LZ4Compressor.java:163) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.util.CompressedChunkReader$Mmap.readChunk(CompressedChunkReader.java:192) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cache.ChunkCache.load(ChunkCache.java:157) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cache.ChunkCache.load(ChunkCache.java:39) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:2949) ~[caffeine-2.2.6.jar:na]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$15(BoundedLocalCache.java:1807) ~[caffeine-2.2.6.jar:na]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[na:1.8.0_151]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1805) ~[caffeine-2.2.6.jar:na]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1788) ~[caffeine-2.2.6.jar:na]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:97) ~[caffeine-2.2.6.jar:na]
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66) ~[caffeine-2.2.6.jar:na]
        at org.apache.cassandra.cache.ChunkCache$CachingRebufferer.rebuffer(ChunkCache.java:235) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cache.ChunkCache$CachingRebufferer.rebuffer(ChunkCache.java:213) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.util.RandomAccessReader.reBufferAt(RandomAccessReader.java:65) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.util.RandomAccessReader.seek(RandomAccessReader.java:207) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.util.FileHandle.createReader(FileHandle.java:150) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.sstable.format.SSTableReader.getFileDataInput(SSTableReader.java:1767) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.columniterator.AbstractSSTableIterator.<init>(AbstractSSTableIterator.java:103) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.columniterator.SSTableIterator.<init>(SSTableIterator.java:49) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.sstable.format.big.BigTableReader.iterator(BigTableReader.java:72) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.io.sstable.format.big.BigTableReader.iterator(BigTableReader.java:65) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.rows.UnfilteredRowIteratorWithLowerBound.initializeIterator(UnfilteredRowIteratorWithLowerBound.java:107) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.maybeInit(LazilyInitializedUnfilteredRowIterator.java:48) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.rows.LazilyInitializedUnfilteredRowIterator.partitionLevelDeletion(LazilyInitializedUnfilteredRowIterator.java:81) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.rows.UnfilteredRowIteratorWithLowerBound.partitionLevelDeletion(UnfilteredRowIteratorWithLowerBound.java:167) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.SinglePartitionReadCommand.queryMemtableAndDiskInternal(SinglePartitionReadCommand.java:609) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.SinglePartitionReadCommand.queryMemtableAndDisk(SinglePartitionReadCommand.java:514) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.SinglePartitionReadCommand.queryStorage(SinglePartitionReadCommand.java:376) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.ReadCommand.executeLocally(ReadCommand.java:407) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.SinglePartitionReadCommand$Group.executeLocally(SinglePartitionReadCommand.java:1056) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.db.SinglePartitionReadCommand$Group.executeInternal(SinglePartitionReadCommand.java:1033) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:420) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:406) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.statements.SelectStatement.executeInternal(SelectStatement.java:79) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:306) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.query(SchemaKeyspace.java:1319) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchDroppedColumns(SchemaKeyspace.java:1106) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:1027) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:980) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:939) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:916) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:904) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:90) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:80) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:262) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689) [apache-cassandra-3.11.0.jar:3.11.0]
INFO  [main] 2023-09-02 23:59:19,397 YamlConfigurationLoader.java:89 - Configuration location: file:/opt/cassandra/conf/cassandra.yaml

```
</details>

Then only one node will fail to start cassandra.

``` sh
$ cassandra -v
3.11.0
$ medusa --version
0.15.0
```

[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37667625)

**Comment by ei-show** [comment]
In cassandra.log, there is a failure when loading system_schema.
Therefore, I deleted the files under data/system_schema/ and was able to start it.
``` sh
sudo rm -rf /cassandra-data/data/system_schema/*
```
Is there any possible cause?

**Comment by adejanovski** [comment]
Interesting, it looks like the chunk cache is what caused the issue in the first place 🤔 
That would mean we're not cleaning it up properly.
We'll investigate that.

**Comment by ei-show** [comment]
snapshotをしゅとくした

**Comment by ei-show** [comment]
The cause seems to be that the backup ended prematurely in the environment where the snapshot was taken.
  When I reacquired the snapshot, I was able to restore it in another environment without any problems.
   
 Thank you.
