### ISSUE TITLE
Cluster restore on same hardware is not working

### ISSUE THREAD

**Issue by sandeepmallik** [thelastpickle/cassandra-medusa#74]
Cluster restore on same hardware is not working. This is three node cluster. Made sure agent forwarding is working. medusa and medusa-wrapper paths are fine. medusa is stopping cassandra service but restore is not working. OS is CentOS 6.10.

[svarupula@test1 ~]$ ssh -A root@localhost
Last login: Tue Feb 11 09:12:30 2020 from test2.sandbox.com

[root@test1 ~]# env | grep SSH_AUTH_SOCK
SSH_AUTH_SOCK=/tmp/ssh-bSGtkZ5120/agent.5120

[root@test1 ~]# medusa restore-cluster --backup-name=test --seed-target test2.sandbox.com
[2020-02-11 09:15:58,500] INFO: Monitoring provider is noop
[2020-02-11 09:15:58,500] INFO: system_auth keyspace will be overwritten with the backup on target nodes
[2020-02-11 09:15:58,649] INFO: Ensuring the backup is found and is complete
[2020-02-11 09:15:58,675] INFO: Restore will happen "In-Place", no new hardware is involved
[2020-02-11 09:15:59,459] INFO: Starting Restore on all the nodes in this list: None
[2020-02-11 09:15:59,459] INFO: Starting cluster restore...
[2020-02-11 09:15:59,459] INFO: Working directory for this execution: /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
[2020-02-11 09:15:59,460] INFO: About to restore on test1.sandbox.com using {'source': ['test1.sandbox.com'], 'seed': False} as backup source
[2020-02-11 09:15:59,460] INFO: About to restore on test2.sandbox.com using {'source': ['test2.sandbox.com'], 'seed': False} as backup source
[2020-02-11 09:15:59,460] INFO: About to restore on test3.sandbox.com using {'source': ['test3.sandbox.com'], 'seed': False} as backup source
[2020-02-11 09:15:59,460] INFO: This will delete all data on the target nodes and replace it with backup test.
Are you sure you want to proceed? (Y/n)Y
[2020-02-11 09:16:06,026] INFO: target seeds : []
[2020-02-11 09:16:06,026] INFO: Stopping Cassandra on all nodes currently up
[2020-02-11 09:16:06,026] INFO: Executing "/etc/init.d/cassandra stop" on all nodes.
[2020-02-11 09:16:06,423] INFO: Job executing "/etc/init.d/cassandra stop" ran and finished Successfully on all nodes.
[2020-02-11 09:16:06,423] INFO: Restoring data on test1.sandbox.com...
[2020-02-11 09:16:06,423] INFO: Restoring data on test2.sandbox.com...
[2020-02-11 09:16:06,423] INFO: Restoring data on test3.sandbox.com...
[2020-02-11 09:16:06,423] INFO: Executing "nohup sh -c "mkdir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a; cd /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a && medusa-wrapper sudo medusa --fqdn=%s -vvv restore-node --in-place  %s --no-verify --backup-name test --temp-dir /tmp   "" on all nodes.
[2020-02-11 09:16:06,840] INFO: Job executing "nohup sh -c "mkdir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a; cd /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a && medusa-wrapper sudo medusa --fqdn=%s -vvv restore-node --in-place  %s --no-verify --backup-name test --temp-dir /tmp   "" ran and finished with errors on following nodes: ['test1.sandbox.com', 'test2.sandbox.com', 'test3.sandbox.com']
[2020-02-11 09:16:06,840] INFO: [test1.sandbox.com]     nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,840] INFO: test1.sandbox.com-stdout: nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,840] INFO: [test2.sandbox.com]     nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,840] INFO: test2.sandbox.com-stdout: nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,841] INFO: [test3.sandbox.com]     nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,841] INFO: test3.sandbox.com-stdout: nohup: ignoring input and appending output to `nohup.out'
[2020-02-11 09:16:06,842] ERROR: Some nodes failed to restore. Exiting
[2020-02-11 09:16:06,842] ERROR: This error happened during the cluster restore: Some nodes failed to restore. Exiting
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 72, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 147, in execute
    self._restore_data()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 349, in _restore_data
    raise Exception(err_msg)
Exception: Some nodes failed to restore. Exiting

[root@test1 ~]# cat nohup.out
sh: medusa-wrapper: command not found

[root@test1 ~]# which medusa-wrapper
/usr/local/bin/medusa-wrapper

[root@test1 ~]# ls -l /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
total 0

[root@test2 ~]# ls -l /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
total 0

[root@test3 ~]# ls -l /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
total 0

**Comment by tabbi** [comment]
i've got same problem

**Comment by adejanovski** [comment]
@sandeepmallik, could you try running `nohup sh -c "mkdir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a; cd /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a && medusa-wrapper sudo medusa -vvv restore-node --in-place --no-verify --backup-name test --temp-dir /tmp` directly and see what you get?
If it doesn't work, can you just run `medusa-wrapper sudo medusa -vvv restore-node --in-place --no-verify --backup-name test --temp-dir /tmp` ?

Thanks

**Comment by sandeepmallik** [comment]
@adejanovski Here is the output. Something to do with medusa-wrapper script

[root@av4c6pmucd01 ~]# ls /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
ls: cannot access /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a: No such file or directory

[root@av4c6pmucd01 ~]# `nohup sh -c "mkdir /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a; cd /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a && medusa-wrapper sudo medusa -vvv restore-node --in-place --no-verify --backup-name test --temp-dir /tmp"`
nohup: ignoring input and appending output to `nohup.out'
[root@av4c6pmucd01 ~]# cat nohup.out
[root@av4c6pmucd01 ~]# ps -ef|grep medusa
root      9677  9525  0 11:08 pts/1    00:00:00 grep medusa
[root@av4c6pmucd01 ~]# ls /tmp/medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a
pid  status  stderr  stdout

[root@av4c6pmucd01 medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a]# ls -lhtr
total 12K
-rw-r--r-- 1 root root  5 Feb 12 11:08 pid
-rw-r--r-- 1 root root  0 Feb 12 11:08 stdout
-rw-r--r-- 1 root root 32 Feb 12 11:08 stderr
-rw-r--r-- 1 root root  2 Feb 12 11:08 status
[root@av4c6pmucd01 medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a]# cat pid
9673
`[root@av4c6pmucd01 medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a]# cat stderr`
`sudo: medusa: command not found`
[root@av4c6pmucd01 medusa-job-bd8a39ca-a5ea-4a3a-820f-0fa6ddc5130a]# cat status
1

Below command executed nothing.

[root@av4c6pmucd01 ~]#
`[root@av4c6pmucd01 ~]# medusa-wrapper sudo medusa -vvv restore-node --in-place --no-verify --backup-name test --temp-dir /tmp`
[root@av4c6pmucd01 ~]#

**Comment by sandeepmallik** [comment]
@adejanovski May be something to do with sudo. I logged in as root. I will check again and see if soft links fixed it.

[root@test1 ~]# medusa-wrapper sudo medusa
[root@test1 ~]# cat stderr
sudo: medusa: command not found

[root@test1 ~]# medusa-wrapper medusa
[root@test1 ~]# cat stdout
Usage: medusa [OPTIONS] COMMAND [ARGS]...

I fixed this with soft link. 

[root@test1 ~]# ln -s /usr/local/bin/medusa /usr/bin/medusa
[root@test1 ~]# ls -lhtr /usr/bin/medusa
lrwxrwxrwx 1 root root 21 Feb 12 13:10 /usr/bin/medusa -> /usr/local/bin/medusa
[root@test1 ~]# sudo medusa
Usage: medusa [OPTIONS] COMMAND [ARGS]...

[root@test1 ~]# ln -s /usr/local/bin/medusa-wrapper /usr/bin/medusa-wrapper
[root@test1 ~]# medusa-wrapper sudo medusa
[root@test1 ~]# cat stdout
Usage: medusa [OPTIONS] COMMAND [ARGS]...

**Comment by sandeepmallik** [comment]
@adejanovski It worked. Issue with sudo.

[root@test1 ~]# medusa restore-cluster --backup-name=test --seed-target test2.sandbox.net
[2020-02-12 13:32:05,328] INFO: Monitoring provider is noop
[2020-02-12 13:32:05,328] INFO: system_auth keyspace will be overwritten with the backup on target nodes
[2020-02-12 13:32:05,711] INFO: Ensuring the backup is found and is complete
[2020-02-12 13:32:05,752] INFO: Restore will happen "In-Place", no new hardware is involved
[2020-02-12 13:32:06,251] INFO: Starting Restore on all the nodes in this list: None
[2020-02-12 13:32:06,251] INFO: Starting cluster restore...
[2020-02-12 13:32:06,251] INFO: Working directory for this execution: /tmp/medusa-job-b3c7cceb-b592-4630-86c7-dcd57288872a
[2020-02-12 13:32:06,251] INFO: About to restore on test1.sandbox.net using {'source': ['test1.sandbox.net'], 'seed': False} as backup source
[2020-02-12 13:32:06,251] INFO: About to restore on test2.sandbox.net using {'source': ['test2.sandbox.net'], 'seed': False} as backup source
[2020-02-12 13:32:06,251] INFO: About to restore on test3.sandbox.net using {'source': ['test3.sandbox.net'], 'seed': False} as backup source
[2020-02-12 13:32:06,252] INFO: This will delete all data on the target nodes and replace it with backup test.
Are you sure you want to proceed? (Y/n)Y
[2020-02-12 13:32:10,637] INFO: target seeds : []
[2020-02-12 13:32:10,637] INFO: Stopping Cassandra on all nodes currently up
[2020-02-12 13:32:10,637] INFO: Executing "/etc/init.d/cassandra stop" on all nodes.
[2020-02-12 13:32:11,024] INFO: Job executing "/etc/init.d/cassandra stop" ran and finished Successfully on all nodes.
[2020-02-12 13:32:11,024] INFO: Restoring data on test1.sandbox.net...
[2020-02-12 13:32:11,025] INFO: Restoring data on test2.sandbox.net...
[2020-02-12 13:32:11,025] INFO: Restoring data on test3.sandbox.net...
[2020-02-12 13:32:11,025] INFO: Executing "nohup sh -c "mkdir /tmp/medusa-job-b3c7cceb-b592-4630-86c7-dcd57288872a; cd /tmp/medusa-job-b3c7cceb-b592-4630-86c7-dcd57288872a && medusa-wrapper sudo medusa --fqdn=%s -vvv restore-node --in-place  %s --no-verify --backup-name test --temp-dir /tmp   "" on all nodes.
[2020-02-12 13:32:36,959] INFO: Job executing "nohup sh -c "mkdir /tmp/medusa-job-b3c7cceb-b592-4630-86c7-dcd57288872a; cd /tmp/medusa-job-b3c7cceb-b592-4630-86c7-dcd57288872a && medusa-wrapper sudo medusa --fqdn=%s -vvv restore-node --in-place  %s --no-verify --backup-name test --temp-dir /tmp   "" ran and finished Successfully on all nodes.
[2020-02-12 13:32:36,960] INFO: Restore process is complete. The cluster should be up shortly.
[2020-02-12 13:32:36,960] INFO: Restore duration: 31
[2020-02-12 13:32:36,960] INFO: Successfully restored the cluster

==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  xxxx  210.56 KiB  32           100.0%            f3996592-b706-40dc-8a30-fda07335fd10  us-east-1a
UN  xxxx 220.07 KiB  32           100.0%            38a345a9-5116-41c1-bf47-1e08bba5a2b3  us-east-1b
UN  xxxx  209.2 KiB  32           100.0%            d0eb88fc-3848-4e72-ba55-e764a3215548  us-east-1c

**Comment by sandeepmallik** [comment]
@tabbi  See above

**Comment by adejanovski** [comment]
thanks for the feedback @sandeepmallik.
Could you tell me how precisely you installed Medusa in the first place? Did you use the `--user` flag with `pip3` or anything else specific?

**Comment by sandeepmallik** [comment]
@adejanovski like this - pip3.6 install cassandra-medusa[S3]. I don't have pip3 on my machine.

**Comment by adejanovski** [comment]
We recommend to use `sudo` when installing medusa in order to have the shell scripts created appropriately and so that the `/etc/medusa` directory can be created as well (unless you ran this using root).

**Comment by sandeepmallik** [comment]
@adejanovski I ran command as root user. I believe some issue with `sudo` on vm's. Closing this ticket.
