### ISSUE TITLE
restore-node failing with "takes 5 positional arguments but 6 were given"

### ISSUE THREAD

**Issue by chrisjmiller1** [thelastpickle/cassandra-medusa#808]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=81896975)

Hi folks, 

I'm currently testing medusa backup and restore using a 3 instance cluster and restore-node is failing with "takes 5 positional arguments but 6 were given". Details below:

Medusa version 0.21.

Backup command executed:
`nohup medusa backup --backup-name=20240930-instance-backup3 &`

Command executed:
`nohup sudo medusa restore-node --backup-name=20240930-instance-backup3 --temp-dir /data/metadata/medusa_tmp &`

There's no error in medusa.log:

```
[2024-10-01 14:22:44,549] INFO: Connecting to s3_compatible with args {'endpoint_url': 'https://xxxxxxxx.compat.objectstorage.us-ashburn-1.oraclecloud.com:443', 'verify': False}
[2024-10-01 14:22:44,553] DEBUG: Downloading  8 files to /data/metadata/medusa_tmp/medusa-restore-e9cffd03-bf01-4396-96aa-dd63af418f64/test/test-92758780339e11ef8abdb7588b09801e
[2024-10-01 14:22:44,554] INFO: [S3 Storage] Stat-ting s3://xxxxxxxx/xxxxxxxx/data/test/test-92758780339e11ef8abdb7588b09801e/nb-3-big-Statistics.db
[2024-10-01 14:22:44,612] DEBUG: Disconnecting from S3...
[2024-10-01 14:22:44,613] DEBUG: Disconnecting from S3...
```

Here's the output from nohup.out
`[2024-10-01 14:18:29,161] INFO: [S3 Storage] Stat-ting s3://xxxxxxxx/xxxxxxxx/data/test/test-92758780339e11ef8abdb7588b09801e/nb-3-big-Statistics.db
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(_args, *_kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, _args, *_kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(_args, *_kwargs)
  File "/usr/local/lib/python3.9/site-packages/medusa/medusacli.py", line 275, in restore_node
    medusa.restore_node.restore_node(medusaconfig, Path(temp_dir), backup_name, in_place, keep_auth, seeds,
  File "/usr/local/lib/python3.9/site-packages/medusa/restore_node.py", line 50, in restore_node
    restore_node_locally(config, temp_dir, backup_name, in_place, keep_auth, seeds, storage,
  File "/usr/local/lib/python3.9/site-packages/medusa/restore_node.py", line 90, in restore_node_locally
    download_data(config.storage, node_backup, fqtns_to_restore, destination=download_dir)
  File "/usr/local/lib/python3.9/site-packages/medusa/download.py", line 56, in download_data
    storage.storage_driver.download_blobs(srcs, dst)
  File "/usr/local/lib/python3.9/site-packages/medusa/storage/abstract_storage.py", line 150, in download_blobs
    loop.run_until_complete(self._download_blobs(srcs, dest))
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/medusa/storage/abstract_storage.py", line 158, in _download_blobs
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/medusa/storage/s3_base_storage.py", line 294, in _download_blob
    await future
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/medusa/storage/s3_base_storage.py", line 297, in __download_blob
    blob = self.__stat_blob(src)
  File "/usr/local/lib/python3.9/site-packages/medusa/storage/s3_base_storage.py", line 346, in __stat_blob`

Any ideas?

Thanks, 

Chris.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/MED-98) by [Unito](https://www.unito.io)
┆Issue Number: MED-98

**Comment by chrisjmiller1** [comment]
HI @adejanovski 

Just wondering if there's any update on this ticket?

Thanks, 

Chris.

**Comment by chrisjmiller1** [comment]
Found root cause - was due to some debugging that was implemented as per another ticket,
