### ISSUE TITLE
Restore-cluster fails on a ScyllaDB Cluster

### ISSUE THREAD

**Issue by alvaropalmeirao** [thelastpickle/cassandra-medusa#81]
When running ```medusa restore-cluster``` or ```medusa restore-node``` the command fails with the following error:
```
[2020-02-18 16:05:52,497] DEBUG: Restoring table view_virtual_columns-08843b6345dc3be29798a0418295cfaa with sstableloader...
Unrecognized option: --storage-port
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 11, in <module>
    load_entry_point('cassandra-medusa==0.6.0.dev0', 'console_scripts', 'medusa')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/medusa/medusacli.py", line 212, in restore_node
    verify, set(keyspaces), set(tables), use_sstableloader)
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_node.py", line 51, in restore_node
    keyspaces, tables)
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_node.py", line 152, in restore_node_sstableloader
    invoke_sstableloader(config, download_dir, keep_auth, fqtns_to_restore, cassandra.storage_port)
  File "/usr/local/lib/python3.5/dist-packages/medusa/restore_node.py", line 176, in invoke_sstableloader
    os.path.join(ks_path, table)])
  File "/usr/local/lib/python3.5/dist-packages/gevent/subprocess.py", line 348, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['sstableloader', '-d', 'scylladb-test-4a53de998b', '--storage-port', '7000', '--username', 'xxx', '--password', 'xxx', '--no-progress', '/tmp/medusa-restore-55d11fa6-7324-499f-b2d3-24faedefa942/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa']' returned non-zero exit status 1
```

The problem is that the sstableloader binary on ScyllaDB is different than Cassandra and it doesn't have the option --storage-port. The workaround that I did was to comment/remove the storage_port arg references on restore_node.py file. With this change, the restore runs successfully.
So I wonder how can we arrange a more elegant workaround to keep compatibility between Cassandra and ScyllaDB.

**Comment by adejanovski** [comment]
I guess we could avoid specifying the storage port explicitly in the sstableloader call if it's already set to the default ones (7000 or 7001) : https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/restore_node.py#L171-L178

**Comment by alvaropalmeirao** [comment]
I will try to remove this line and i will get back with the result: https://github.com/thelastpickle/cassandra-medusa/blob/1aa4699c08edb9198f96146d208fd2b7ede0ee10/medusa/restore_node.py#L174

**Comment by adejanovski** [comment]
Well, you should only remove it if it's the default port then.
Otherwise, you're going to break the integration tests.

**Comment by alvaropalmeirao** [comment]
Ok. 👍

**Comment by alvaropalmeirao** [comment]
Hi,

After reading the documentation I notice that the flag --storage-port only supports the port 7000. The 7001 port is added with --ssl_storage_port flag: https://docs.datastax.com/en/archived/cassandra/3.0/cassandra/tools/toolsBulkloader.html

So, in my case, I will only do the validation if the default port (storage_port) is 7000. But it would be nice to add the flag --ssl_storage_port for Cassandra users.

**Comment by alvaropalmeirao** [comment]
PR: https://github.com/thelastpickle/cassandra-medusa/pull/82

**Comment by alvaropalmeirao** [comment]
Solved.
