### ISSUE TITLE
medusa download fails due to missing parameter

### ISSUE THREAD

**Issue by chebelom** [thelastpickle/cassandra-medusa#90]
`medusa download --backup-name download-broken --download-destination /mnt/temp/`

```
Traceback (most recent call last):
  File "/usr/local/bin/medusa", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/medusa/medusacli.py", line 152, in download
    medusa.download.download_cmd(medusaconfig, backup_name, Path(download_destination))
  File "/usr/local/lib/python3.5/dist-packages/medusa/download.py", line 75, in download_cmd
    download_data(config.storage, node_backup, download_destination)
TypeError: download_data() missing 1 required positional argument: 'destination'
```

**Comment by arodrime** [comment]
Fixed as well. Closing
