### ISSUE TITLE
Syntax error in CQL query

### ISSUE THREAD

**Issue by jagarlamudisrinath** [thelastpickle/cassandra-medusa#94]
Hi Team,

I have a single node Cassandra DB. I have taken the backup using medusa. The backup was completed successfully. while restoring the backup it is giving the below error.

[2020-03-16 12:24:06,522] INFO: Starting Restore on all the nodes in this list: None
[2020-03-16 12:24:06,522] INFO: Starting cluster restore...
[2020-03-16 12:24:06,522] INFO: Working directory for this execution: /tmp/medusa-job-ec5d5e2b-dd3d-4765-86b1-b7695a8f99e2
[2020-03-16 12:24:06,522] INFO: About to restore on ip-10-0-1-103.us-east-2.compute.internal using {'source': ['ip-10-0-1-65.us-east-2.compute.internal'], 'seed': False} as backup source
[2020-03-16 12:24:06,522] INFO: This will delete all data on the target nodes and replace it with backup initial-backup.
[2020-03-16 12:24:06,522] INFO: target seeds : []
[2020-03-16 12:24:06,522] INFO: Restoring schema on the target cluster
[2020-03-16 12:24:06,644] INFO: (Re)creating schema for keyspace taxilla_test
[2020-03-16 12:24:16,761] ERROR: This error happened during the cluster restore: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 's' ([s])">
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 72, in orchestrate
    restore.execute()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 147, in execute
    self._restore_data()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 330, in _restore_data
    self._restore_schema()
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 392, in _restore_schema
    self._create_or_recreate_schema_objects(session, keyspace, schema[keyspace])
  File "/usr/local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 422, in _create_or_recreate_schema_objects
    session.execute(mv[1])
  File "/usr/local/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 197, in execute
    return self.session.execute(query)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:0 no viable alternative at input 's' ([s])">

**Comment by adejanovski** [comment]
Hi @jagarlamudisrinath, 
It seems like you have a Materialized View which contains something (a column?) called `s` which seems to make Cassandra unhappy once Medusa tries to recreate it. 
Could you share with us the schema of your MVs as they appear in the schema.cql file generated by Medusa?

Thanks!

**Comment by adejanovski** [comment]
Closing this ticket due to inactivity.
Feel free to reopen if you still run into that issue.
