### ISSUE TITLE
Does Mesdusa support Cassandra SSL authentication ? 

### ISSUE THREAD

**Issue by Pradeep2get** [thelastpickle/cassandra-medusa#99]
Hi Team,

I have a cluster with SSL authentication and tried a backup using Medusa, It was stuck in the middle and the backup not completed fully. 

I configured the medusa.ini file properly, I can able to take backup properly when using w/o SSL cluster. While using SSL authentication cluster backup stuck in the middle, the logs shown below.

# medusa backup --backup-name=test
[2020-03-26 10:43:39,791] INFO: Monitoring provider is noop
[2020-03-26 10:43:39,799] WARNING: is ccm : 0
[2020-03-26 10:43:39,899] INFO: Creating snapshot
[2020-03-26 10:43:39,899] INFO: Saving tokenmap and schema
[2020-03-26 10:52:00,232] ERROR: This error happened during the backup: ('Unable to connect to any servers', {'10.10.0.10:9042': ConnectionResetError(104, 'Connection reset by peer')})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cassandra_medusa-0.5.1-py3.6.egg/medusa/backup.py", line 252, in main
    schema, tokenmap = get_schema_and_tokenmap(cassandra)
  File "/usr/local/lib/python3.6/site-packages/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/retrying-1.3.3-py3.6.egg/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/site-packages/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/site-packages/six-1.14.0-py3.6.egg/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/site-packages/cassandra_medusa-0.5.1-py3.6.egg/medusa/backup.py", line 296, in get_schema_and_tokenmap
    with cassandra.new_session() as cql_session:
  File "/usr/local/lib/python3.6/site-packages/cassandra_medusa-0.5.1-py3.6.egg/medusa/cassandra_utils.py", line 288, in new_session
    return self._cql_session_provider.new_session()
  File "/usr/local/lib/python3.6/site-packages/cassandra_medusa-0.5.1-py3.6.egg/medusa/cassandra_utils.py", line 86, in new_session
    session = cluster.connect()
  File "cassandra/cluster.py", line 1660, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1696, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1683, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3470, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3515, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'10.10.0.10:9042': ConnectionResetError(104, 'Connection reset by peer')})

Is there any configuration should I need to change for using SSL in medusa.ini 
Any Suggestion...!

**Comment by adejanovski** [comment]
Hi @Pradeep2get,

we do not support yet ssl authentication in Medusa.
This shouldn't be much of a problem to add that feature though, although we haven't planned it yet.

Any contribution would be much appreciated.

**Comment by adejanovski** [comment]
This feature was merged into `master` through #122
